// AnimatedPlaneEffect
// D20469736E1BE3F4BB4D2507D630EEC770507C4F7C5BEB0D60DE1BB9CFFC6A01

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //
            
                preshader
                mul r0.x, c1.x, c1.x
                neg r1.x, r0.x
                lt c14.x, r1.x, r0.x
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c13.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c12.x, r0.x, r1.x
            
            // approximately 10 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_ViewProjection;
            //   float4x4 Matrices_World;
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldInverseTranspose c0       4
            //   Matrices_World                 c4       4
            //   Matrices_ViewProjection        c8       4
            //   Matrices_Texture               c15      2
            //   Fog_Density                    c17      1
            //   Eye                            c18      1
            //   TexelOffset                    c19      1
            //   EyeSign                        c20      1
            //   LevelCenter                    c21      1
            //
            
                vs_2_0
                def c22, 1, 0, 1.44269502, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dp4 r0.x, v0, c4
                dp4 r0.y, v0, c5
                dp4 r0.z, v0, c6
                add r1.xyz, r0, -c21
                dp3 r0.w, r1, c18
                mad r0.xyz, r0.w, c20, r0
                dp4 r0.w, v0, c7
                dp4 oPos.z, r0, c10
                dp4 r1.x, r0, c8
                dp4 r1.y, r0, c9
                dp4 r0.x, r0, c11
                mad oPos.xy, c19, r0.x, r1
                mad r0.yzw, v2.xxyx, c22.xxxy, c22.xyyx
                dp3 oT0.x, r0.yzww, c15
                dp3 oT0.y, r0.yzww, c16
                dp3 oT1.x, v1, c0
                dp3 oT1.y, v1, c1
                dp3 oT1.z, v1, c2
                dp3 oT1.w, v1, c3
                mul r0.y, r0.x, c17.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c22.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c12.x
                mad r0.x, r0.x, r1.x, c13.x
                add r0.x, -r0.x, c22.x
                max r0.x, r0.x, c22.y
                min r0.x, r0.x, c22.x
                mad oT2.x, c14.x, -r0.x, r0.x
            
            // approximately 32 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float Fullbright;
            //   float IgnoreShading;
            //   float SewerHax;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   DiffuseLight    c0       1
            //   BaseAmbient     c1       1
            //   Fullbright      c2       1
            //   AlphaIsEmissive c3       1
            //   IgnoreShading   c4       1
            //   SewerHax        c5       1
            //
            
                preshader
                mul r0.x, c2.x, c2.x
                neg r1.x, r0.x
                cmp c1.x, r1.x, (0), (1)
                mul c2.x, c4.x, c4.x
                neg r0.xyz, c1.xyz
                add c3.xyz, (1, 1, 1), r0.xyz
                mul r0.x, c3.x, c3.x
                neg r1.x, r0.x
                mov c0.x, r0.x
                cmp c4.x, r1.x, (1), (0)
                cmp r0.x, r1.x, (-1), (-0)
                neg r0.yzw, c0.xyz
                add c5.xyz, (1, 1, 1), r0.yzw
                mul r0.y, c5.x, c5.x
                neg r1.x, r0.y
                cmp c7.x, r1.x, (0), r0.x
            
            // approximately 16 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AnimatedSampler;
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   DiffuseLight     c8       1
            //   BaseAmbient      c9       1
            //   Material_Opacity c10      1
            //   AnimatedSampler  s0       1
            //
            
                ps_2_0
                def c11, 1, 0.00999999978, 0.600000024, 0.300000012
                def c12, -0.00390625, 0.75, 0, 1
                def c13, 0.5, 0, 0, 0
                dcl t0.xy
                dcl t1.xyz
                dcl t2.x
                dcl_2d s0
                texld r0, t0, s0
                mov r1.w, c12.x
                mad r0.y, c10.x, r0.w, r1.w
                mul r1, r0.y, c4.x
                texkill r1
                abs r0.y, t1.z
                mul r1.xyz, r0.y, c3
                dp3_sat r1.w, t1, c11.x
                mov r2.w, c0.x
                cmp r0.y, -r2.w, c1.x, r0.w
                mov r2.x, c11.x
                cmp r0.z, -c2.x, r0.y, r2.x
                mul r2.xyz, r0.y, c5
                add_sat r3.xyz, r0.z, c9
                mad r3.xyz, r1.w, c3, r3
                mad r1.xyz, r1, c11.z, r3
                add r1.w, t1.z, c11.y
                cmp r1.xyz, r1.w, r3, r1
                abs r1.w, t1.x
                mul r3.xyz, r1.w, c3
                mad r3.xyz, r3, c11.w, r1
                add r1.w, t1.x, c11.y
                cmp_sat r1.xyz, r1.w, r1, r3
                mad r1.xyz, r1, c8, r2
                lrp r2.xyz, t2.x, c11.x, r1
                add r0.x, -r0.x, c12.y
                mul r0.y, r0.w, c10.x
                cmp r1.w, -r2.w, r0.y, c10.x
                cmp r2.w, r0.x, c12.z, c12.w
                cmp r0.xyz, c7.x, r2, r2.w
                mul r1.xyz, r0, c13.x
                mov oC0, r1
            
            // approximately 32 instruction slots used (1 texture, 31 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //
            
                preshader
                mul r0.x, c1.x, c1.x
                neg r1.x, r0.x
                lt c14.x, r1.x, r0.x
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c13.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c12.x, r0.x, r1.x
            
            // approximately 10 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_ViewProjection;
            //   float4x4 Matrices_World;
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldInverseTranspose c0       4
            //   Matrices_World                 c4       4
            //   Matrices_ViewProjection        c8       4
            //   Matrices_Texture               c15      2
            //   Fog_Density                    c17      1
            //   Eye                            c18      1
            //   TexelOffset                    c19      1
            //   EyeSign                        c20      1
            //   LevelCenter                    c21      1
            //
            
                vs_2_0
                def c22, 1, 0, 1.44269502, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dp4 r0.x, v0, c4
                dp4 r0.y, v0, c5
                dp4 r0.z, v0, c6
                add r1.xyz, r0, -c21
                dp3 r0.w, r1, c18
                mad r0.xyz, r0.w, c20, r0
                dp4 r0.w, v0, c7
                dp4 oPos.z, r0, c10
                dp4 r1.x, r0, c8
                dp4 r1.y, r0, c9
                dp4 r0.x, r0, c11
                mad oPos.xy, c19, r0.x, r1
                mad r0.yzw, v2.xxyx, c22.xxxy, c22.xyyx
                dp3 oT0.x, r0.yzww, c15
                dp3 oT0.y, r0.yzww, c16
                dp3 oT1.x, v1, c0
                dp3 oT1.y, v1, c1
                dp3 oT1.z, v1, c2
                dp3 oT1.w, v1, c3
                mul r0.y, r0.x, c17.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c22.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c12.x
                mad r0.x, r0.x, r1.x, c13.x
                add r0.x, -r0.x, c22.x
                max r0.x, r0.x, c22.y
                min r0.x, r0.x, c22.x
                mad oT2.x, c14.x, -r0.x, r0.x
            
            // approximately 32 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   AlphaIsEmissive c0       1
            //
            
                preshader
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                mov c0.x, r0.x
                cmp c1.x, r1.x, (1), (0)
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AnimatedSampler;
            //   float3 Fog_Color;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Fog_Color        c2       1
            //   Material_Diffuse c3       1
            //   Material_Opacity c4       1
            //   AnimatedSampler  s0       1
            //
            
                ps_2_0
                def c5, -0.00390625, 0, 0, 0
                dcl t0.xy
                dcl t2.x
                dcl_2d s0
                texld r0, t0, s0
                mov r1.w, c4.x
                mad r1.x, r1.w, r0.w, c5.x
                mul r2, r1.x, c1.x
                texkill r2
                mul r1.xyz, r0, c3
                mov r2.xyz, c3
                mad r0.xyz, r0, -r2, c2
                mul r0.w, r0.w, c4.x
                cmp r2.w, -c0.x, r0.w, r1.w
                mad r2.xyz, t2.x, r0, r1
                mov oC0, r2
            
            // approximately 12 instruction slots used (1 texture, 11 arithmetic)
            };
    }
}

