// BasicPostEffect
// A5F81A53692096CE39B051CD848470510BEE9E465E64D46030E9878434E03DCF

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Matrices_Texture c0       2
            //   TexelOffset      c2       1
            //
            
                vs_2_0
                def c3, 1, 0, 0, 0
                dcl_position v0
                dcl_texcoord v1
                mad oPos.xy, c2, v0.w, v0
                mad r0.xyz, v1.xyxw, c3.xxyw, c3.yyxw
                dp3 oT0.x, r0, c0
                dp3 oT0.y, r0, c1
                mov oPos.zw, v0
            
            // approximately 5 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   Material_Opacity c1       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c2, -0.00390625, 0, 0, 0
                dcl t0.xy
                dcl_2d s0
                texld r0, t0, s0
                mov r1.w, c1.x
                mad r1, r0.w, r1.w, c2.x
                texkill r1
                mul r1.w, r0.w, c1.x
                mul r1.xyz, r0, c0
                mov oC0, r1
            
            // approximately 7 instruction slots used (1 texture, 6 arithmetic)
            };
    }
}

