// BurnInPostEffect
// 42F99AA09C24C293A44E519631A57B3DA30A358692D099026E04B4907DE07AD0

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass P0
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Matrices_Texture c0       2
            //   TexelOffset      c2       1
            //
            
                vs_2_0
                def c3, 1, 0, 0, 0
                dcl_position v0
                dcl_texcoord v1
                mad oPos.xy, c2, v0.w, v0
                mad r0.xyz, v1.xyxw, c3.xxyw, c3.yyxw
                dp3 oT0.x, r0, c0
                dp3 oT0.y, r0, c1
                mov oPos.zw, v0
            
            // approximately 5 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 AcceptColor;
            //   sampler2D NewFrameSampler;
            //   sampler2D OldFrameSampler;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   AcceptColor     c0       1
            //   NewFrameSampler s0       1
            //   OldFrameSampler s1       1
            //
            
                ps_2_0
                def c1, 1, 0.25, 0.75, 0
                dcl t0.xy
                dcl_2d s0
                dcl_2d s1
                texld r0, t0, s0
                texld r1, t0, s1
                add r0.xyz, -r0, c0
                abs r0.xyz, r0
                add r0.xyz, -r0, c1.x
                mul r1.w, r0.y, r0.x
                mul r1.w, r0.z, r1.w
                mul r1.w, r1.w, r1.w
                mul r0.xyz, r1.w, c0
                mul r0.xyz, r0, c1.y
                mad r0.xyz, r1, c1.z, r0
                mov r0.w, c1.x
                mov oC0, r0
            
            // approximately 13 instruction slots used (2 texture, 11 arithmetic)
            };
    }
}

