// CausticsEffect
// E9DB19AD123B12157D5543BC803E3A83A19371EC45655285AF1B06E8B266DC86

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 NextFrameData;
            //
            //
            // Registers:
            //
            //   Name          Reg   Size
            //   ------------- ----- ----
            //   NextFrameData c0       3
            //
            
                preshader
                mov c9.x, c2.z
            
            // approximately 1 instruction used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_WorldViewProjection;
            //   float3x3 NextFrameData;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Matrices_Texture             c4       2
            //   NextFrameData                c6       2
            //   TexelOffset                  c8       1
            //
            
                vs_2_0
                def c10, 1, 0, 0, 0
                dcl_position v0
                dcl_texcoord v1
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c8, r0.z, r0
                mov oPos.w, r0.z
                mad r0.xyz, v1.xyxw, c10.xxyw, c10.yyxw
                dp3 oT0.x, r0, c4
                dp3 oT0.y, r0, c5
                add oT1.x, -v0.y, c10.x
                dp3 oT2.x, r0, c6
                dp3 oT2.y, r0, c7
                mov oT3.x, c9.x
            
            // approximately 13 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //
            
                preshader
                mul c1.xyz, (0.5, 0.5, 0.5), c0.xyz
            
            // approximately 1 instruction used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AnimatedSampler;
            //   float3 Material_Diffuse;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   AnimatedSampler  s0       1
            //
            
                ps_2_0
                def c2, 0.400000006, -0.00390625, 0, 0
                dcl t0.xy
                dcl t1.x
                dcl t2.xy
                dcl t3.x
                dcl_2d s0
                texld r0, t0, s0
                texld r1, t2, s0
                lrp r2, t3.x, r1, r0
                mul r0.x, t1.x, t1.x
                mul r2.w, r0.x, r2.w
                mul r0.yzw, r2.wzyx, c0.wzyx
                mul r0.xyz, r0.x, r0.wzyx
                mov r0.w, c2.x
                mad r0.xyz, r0, r0.w, c1
                mad r1, r2.w, c2.x, c2.y
                mul r0.w, r2.w, c2.x
                mov oC0, r0
                texkill r1
            
            // approximately 13 instruction slots used (2 texture, 11 arithmetic)
            };
    }
}

