// CloudShadowEffect
// 5AF26C88082387477D4B10A9D4F5FA041EDB38B04C365204CA62C4468258F8B4

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Standard
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Matrices_Texture             c4       2
            //   TexelOffset                  c6       1
            //
            
                vs_2_0
                def c7, 1, 0, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c6, r0.z, r0
                mov oPos.w, r0.z
                mad r0.xyz, v2.xyxw, c7.xxyw, c7.yyxw
                dp3 oT0.x, r0, c4
                dp3 oT0.y, r0, c5
                mov oT1.xyz, v1
            
            // approximately 10 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c0       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c1, 1, 0, 0, 0
                dcl t0.xy
                dcl_2d s0
                texld r0, t0, s0
                mov r1.w, c1.x
                mad r0.xyz, r0.x, -c0.x, r1.w
                mov r0.w, c1.x
                mov oC0, r0
            
            // approximately 5 instruction slots used (1 texture, 4 arithmetic)
            };
    }
    pass Canopy
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Matrices_Texture             c4       2
            //   TexelOffset                  c6       1
            //
            
                vs_2_0
                def c7, 1, 0, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c6, r0.z, r0
                mov oPos.w, r0.z
                mad r0.xyz, v2.xyxw, c7.xxyw, c7.yyxw
                dp3 oT0.x, r0, c4
                dp3 oT0.y, r0, c5
                mov oT1.xyz, v1
            
            // approximately 10 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   BaseAmbient  c1       1
            //
            
                preshader
                mul c3.xyz, (0.5, 0.5, 0.5), c1.xyz
                mul c2.xyz, (0.5, 0.5, 0.5), c0.xyz
                max r0.xyz, (0, 0, 0), c1.xyz
                min c1.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
            
            // approximately 6 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c4       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c5, 1, 0.00999999978, 0.600000024, 0.300000012
                def c6, 0.75, 0, 0, 0
                dcl t0.xy
                dcl t1.xyz
                dcl_2d s0
                texld r0, t0, s0
                abs r0.y, t1.z
                mul r0.yzw, r0.y, c0.wzyx
                dp3_sat r1.w, t1, c5.x
                mov r1.xyz, c0
                mad r1.xyz, r1.w, r1, c1
                mad r0.yzw, r0, c5.z, r1.wzyx
                add r1.w, t1.z, c5.y
                cmp r0.yzw, r1.w, r1.wzyx, r0
                abs r1.x, t1.x
                mul r1.xyz, r1.x, c0
                mad r1.xyz, r1, c5.w, r0.wzyx
                add r1.w, t1.x, c5.y
                cmp_sat r0.yzw, r1.w, r0, r1.wzyx
                add r1.xyz, -r0.wzyx, c5.x
                mad r0.yzw, r1.wzyx, c6.x, r0
                mov r1.xyz, c3
                mad r0.yzw, r0, c2.wzyx, -r1.wzyx
                mov r1.x, c5.x
                mad r0.x, r0.x, -c4.x, r1.x
                mad r0.xyz, r0.wzyx, r0.x, c3
                mov r0.w, c5.x
                mov oC0, r0
            
            // approximately 23 instruction slots used (1 texture, 22 arithmetic)
            };
    }
}

