// CombineEffect
// EC7FD1032031BC9352447B5964B635E282D7E9B94CEDA61070B909B99C62C688

//listing of all techniques and passes with embedded asm listings 

technique ShaderModel2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelOffset  c0       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_texcoord v1
                mad oPos.xy, c0, v0.w, v0
                mov oT0.xy, v1
                mov oPos.zw, v0
            
            // approximately 3 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float RedGamma;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   RedGamma     c0       1
            //
            
                preshader
                rcp c6.x, c0.x
            
            // approximately 1 instruction used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 LeftFilter;
            //   sampler2D LeftSampler;
            //   float3x3 RightFilter;
            //   sampler2D RightSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   LeftFilter   c0       3
            //   RightFilter  c3       3
            //   LeftSampler  s0       1
            //   RightSampler s1       1
            //
            
                ps_2_0
                dcl t0.xy
                dcl_2d s0
                dcl_2d s1
                texld r0, t0, s0
                texld r1, t0, s1
                mul r2.xyz, r0.y, c1
                mad r2.xyz, c0, r0.x, r2
                mad r0.xyz, c2, r0.z, r2
                mul r2.xyz, r1.y, c4
                mad r2.xyz, c3, r1.x, r2
                mad r1.xyz, c5, r1.z, r2
                max r2.w, r0.w, r1.w
                add r0.xyz, r0, r1
                pow r2.x, r0.x, c6.x
                mov r2.yz, r0
                mov oC0, r2
            
            // approximately 15 instruction slots used (2 texture, 13 arithmetic)
            };
    }
}

