// CubemappedEffect
// AD296A9BA42B7803025C1F7CD6A009F707EA411D49C6E6A5476E178D1F7C6273

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //
            
                preshader
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c9.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c8.x, r0.x, r1.x
            
            // approximately 7 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Density;
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldViewProjection   c0       4
            //   Matrices_WorldInverseTranspose c4       4
            //   Fog_Density                    c10      1
            //   TexelOffset                    c11      1
            //
            
                vs_2_0
                def c12, 1.44269502, 1, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c11, r0.z, r0
                dp3 oT0.x, v1, c4
                dp3 oT0.y, v1, c5
                dp3 oT0.z, v1, c6
                dp3 oT0.w, v1, c7
                mul r0.x, r0.z, c10.x
                mov oPos.w, r0.z
                mul r0.y, r0.x, r0.x
                mul r0.x, r0.y, r0.x
                mul r0.x, r0.x, c12.x
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c8.x
                mad r0.x, r0.x, r1.x, c9.x
                add oT1.x, -r0.x, c12.y
                mov oT2.xy, v2
            
            // approximately 20 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   DiffuseLight     c0       1
            //   BaseAmbient      c1       1
            //   Material_Opacity c2       1
            //
            
                preshader
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
                mov c2.x, c2.x
            
            // approximately 5 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D CubemapSampler;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name           Reg   Size
            //   -------------- ----- ----
            //   DiffuseLight   c3       1
            //   BaseAmbient    c4       1
            //   CubemapSampler s0       1
            //
            
                ps_2_0
                def c5, 1, 0.00999999978, 0.600000024, 0.300000012
                def c6, 0.5, 0, 0, 0
                dcl t0.xyz
                dcl t2.xy
                dcl_2d s0
                texld r0, t2, s0
                abs r0.x, t0.z
                mul r0.xyz, r0.x, c0
                dp3_sat r1.w, t0, c5.x
                add_sat r1.xyz, r0.w, c4
                mul r2.xyz, r0.w, c1
                mad r1.xyz, r1.w, c0, r1
                mad r0.xyz, r0, c5.z, r1
                add r0.w, t0.z, c5.y
                cmp r0.xyz, r0.w, r1, r0
                abs r0.w, t0.x
                mul r1.xyz, r0.w, c0
                mad r1.xyz, r1, c5.w, r0
                add r0.w, t0.x, c5.y
                cmp_sat r0.xyz, r0.w, r0, r1
                mad r0.xyz, r0, c3, r2
                mul r0.xyz, r0, c6.x
                mov r0.w, c2.x
                mov oC0, r0
            
            // approximately 19 instruction slots used (1 texture, 18 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //
            
                preshader
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c9.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c8.x, r0.x, r1.x
            
            // approximately 7 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Density;
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldViewProjection   c0       4
            //   Matrices_WorldInverseTranspose c4       4
            //   Fog_Density                    c10      1
            //   TexelOffset                    c11      1
            //
            
                vs_2_0
                def c12, 1.44269502, 1, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c11, r0.z, r0
                dp3 oT0.x, v1, c4
                dp3 oT0.y, v1, c5
                dp3 oT0.z, v1, c6
                dp3 oT0.w, v1, c7
                mul r0.x, r0.z, c10.x
                mov oPos.w, r0.z
                mul r0.y, r0.x, r0.x
                mul r0.x, r0.y, r0.x
                mul r0.x, r0.x, c12.x
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c8.x
                mad r0.x, r0.x, r1.x, c9.x
                add oT1.x, -r0.x, c12.y
                mov oT2.xy, v2
            
            // approximately 20 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float ForceShading;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   DiffuseLight     c0       1
            //   BaseAmbient      c1       1
            //   Material_Opacity c2       1
            //   ForceShading     c3       1
            //
            
                preshader
                mul c0.x, c3.x, c3.x
                neg r0.xyz, c1.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c2.xyz, (1, 1, 1), r0.xyz
                mov c3.x, c2.x
            
            // approximately 6 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D CubemapSampler;
            //   float3 DiffuseLight;
            //   float3 Fog_Color;
            //   float3 Material_Diffuse;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   DiffuseLight     c4       1
            //   Fog_Color        c5       1
            //   BaseAmbient      c6       1
            //   Material_Diffuse c7       1
            //   CubemapSampler   s0       1
            //
            
                ps_2_0
                def c8, 1, 0.00999999978, 0.600000024, 0.300000012
                dcl t0.xyz
                dcl t1.x
                dcl t2.xy
                dcl_2d s0
                texld r0, t2, s0
                abs r1.w, t0.x
                mul r1.xyz, r1.w, c1
                add r1.w, t0.z, c8.y
                abs r2.w, t0.z
                mul r2.xyz, r2.w, c1
                dp3_sat r2.w, t0, c8.x
                add_sat r3.xyz, r0.w, c6
                mad r3.xyz, r2.w, c1, r3
                mad r2.xyz, r2, c8.z, r3
                cmp r2.xyz, r1.w, r3, r2
                mad r1.xyz, r1, c8.w, r2
                add r1.w, t0.x, c8.y
                cmp_sat r1.xyz, r1.w, r2, r1
                mul r2.xyz, r0.w, c2
                mul r0.xyz, r0, c7
                mad r1.xyz, r1, c4, r2
                mul r1.xyz, r0, r1
                cmp r0.xyz, -c0.x, r0, r1
                lrp r1.xyz, t1.x, c5, r0
                mov r1.w, c3.x
                mov oC0, r1
            
            // approximately 22 instruction slots used (1 texture, 21 arithmetic)
            };
    }
}

