// DefaultEffect_TexturedVertexColored
// 8C85DFBC0C649AABB69DF33454F1CEAB82AD8A6C2171450FC683E7D15124A11A

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Matrices_Texture             c4       2
            //   TexelOffset                  c6       1
            //
            
                vs_2_0
                def c7, 1, 0, 0, 0
                dcl_position v0
                dcl_color v1
                dcl_texcoord v2
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c6, r0.z, r0
                mov oPos.w, r0.z
                mad r0.xyz, v2.xyxw, c7.xxyw, c7.yyxw
                dp3 oT1.x, r0, c4
                dp3 oT1.y, r0, c5
                mov oT0, v1
            
            // approximately 10 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   AlphaIsEmissive c0       1
            //
            
                preshader
                mul c2.x, c0.x, c0.x
            
            // approximately 1 instruction used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   Material_Opacity c1       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                dcl t0
                dcl t1.xy
                dcl_2d s0
                texld r0, t1, s0
                mul r1.w, t0.w, c1.x
                mul r0.w, r0.w, r1.w
                cmp r1.w, -c2.x, r0.w, r1.w
                mul r2.xyz, t0, c0
                mul r1.xyz, r0, r2
                mov oC0, r1
            
            // approximately 7 instruction slots used (1 texture, 6 arithmetic)
            };
    }
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Matrices_Texture             c4       2
            //   TexelOffset                  c6       1
            //
            
                vs_2_0
                def c7, 1, 0, 0, 0
                dcl_position v0
                dcl_color v1
                dcl_texcoord v2
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c6, r0.z, r0
                mov oPos.w, r0.z
                mad r0.xyz, v2.xyxw, c7.xxyw, c7.yyxw
                dp3 oT1.x, r0, c4
                dp3 oT1.y, r0, c5
                mov oT0, v1
            
            // approximately 10 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //   float Fullbright;
            //   float TextureEnabled;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   TextureEnabled  c0       1
            //   AlphaIsEmissive c1       1
            //   Fullbright      c2       1
            //
            
                preshader
                mul c0.x, c2.x, c2.x
                mul c1.x, c0.x, c0.x
                mul c2.x, c1.x, c1.x
            
            // approximately 3 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float Emissive;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c3       1
            //   Material_Opacity c4       1
            //   Emissive         c5       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c6, 0.333333343, 1, 0.5, 0
                dcl t1.xy
                dcl_2d s0
                texld r0, t1, s0
                dp3 r0.x, r0, c6.x
                cmp r0.x, -c2.x, r0.x, r0.w
                mov r1.w, c1.x
                cmp r0.x, -r1.w, c5.x, r0.x
                mov r0.y, c6.y
                cmp r0.x, -c0.x, r0.x, r0.y
                mul r0.yzw, r0.x, c3.wzyx
                mul r1.w, r0.x, c4.x
                mul r0.xyz, r0.wzyx, c6.z
                mov r1.xyz, c6.z
                mov r0.w, c6.y
                cmp r0, -c2.x, r1, r0
                mov oC0, r0
            
            // approximately 14 instruction slots used (1 texture, 13 arithmetic)
            };
    }
}

