// DefaultEffect_LitTexturedVertexColored
// 36316EC6700D7D3A79ABA5E02852D91B3106EE1E0E4DF956362B8F851B2DD9C6

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldViewProjection   c0       4
            //   Matrices_WorldInverseTranspose c4       3
            //   Matrices_Texture               c7       2
            //   TexelOffset                    c9       1
            //
            
                vs_2_0
                def c10, 1, 0, 0, 0
                dcl_position v0
                dcl_color v1
                dcl_normal v2
                dcl_texcoord v3
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c9, r0.z, r0
                mov oPos.w, r0.z
                dp3 r0.x, v2, c4
                dp3 r0.y, v2, c5
                dp3 r0.z, v2, c6
                dp3 r0.w, r0, r0
                rsq r0.w, r0.w
                mul oT0.xyz, r0.w, r0
                mad r0.xyz, v3.xyxw, c10.xxyw, c10.yyxw
                dp3 oT2.x, r0, c7
                dp3 oT2.y, r0, c8
                mov oT1, v1
            
            // approximately 16 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float Emissive;
            //   float3 Eye;
            //   float Fullbright;
            //   float SpecularEnabled;
            //   float TextureEnabled;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   DiffuseLight    c0       1
            //   BaseAmbient     c1       1
            //   Eye             c2       1
            //   TextureEnabled  c3       1
            //   SpecularEnabled c4       1
            //   AlphaIsEmissive c5       1
            //   Fullbright      c6       1
            //   Emissive        c7       1
            //
            
                preshader
                mul r0.x, c6.x, c6.x
                neg r1.x, r0.x
                cmp c2.x, r1.x, c7.x, (1)
                mul c0.x, c3.x, c3.x
                mul c1.x, c5.x, c5.x
                neg r0.xyz, c1.xyz
                add c3.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c4.xyz, (1, 1, 1), r0.xyz
                mul c5.x, c4.x, c4.x
                add c6.xyz, c2.xyz, (-0, -0.25, -0)
            
            // approximately 11 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D BaseSampler;
            //   float3 DiffuseLight;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   DiffuseLight     c7       1
            //   BaseAmbient      c8       1
            //   Material_Diffuse c9       1
            //   Material_Opacity c10      1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c11, 1, 0.00999999978, 0.600000024, 0.300000012
                def c12, 0.5, 0, 0, 0
                dcl t0.xyz
                dcl t1
                dcl t2.xy
                dcl_2d s0
                texld r0, t2, s0
                abs r1.w, t0.z
                mul r1.xyz, r1.w, c3
                mov r2.y, c2.x
                mul r3.x, t1.w, c10.x
                mul r2.x, r0.w, r3.x
                mov r3.y, r0.w
                cmp r2.xy, -c1.x, r2, r3
                mov r3.z, c2.x
                cmp r3.x, -c0.x, r3.x, r2.x
                cmp r3.y, -c0.x, r3.z, r2.y
                add_sat r2.xyz, r3.y, c8
                dp3_sat r0.w, t0, c11.x
                mad r2.xyz, r0.w, c3, r2
                mad r1.xyz, r1, c11.z, r2
                add r0.w, t0.z, c11.y
                cmp r1.xyz, r0.w, r2, r1
                abs r0.w, t0.x
                mul r2.xyz, r0.w, c3
                mad r2.xyz, r2, c11.w, r1
                add r0.w, t0.x, c11.y
                cmp_sat r1.xyz, r0.w, r1, r2
                mul r2.xyz, r3.y, c4
                mov r3.w, r3.x
                mad r1.xyz, r1, c7, r2
                mul r2.xyz, t1, c9
                mul r0.xyz, r0, r2
                cmp r0.xyz, -c0.x, r2, r0
                mul r0.xyz, r1, r0
                dp3 r0.w, c6, t0
                mul r0.w, r0.w, r0.w
                mul r0.w, r0.w, r0.w
                mul_sat r0.w, r0.w, r0.w
                mad r1.xyz, r0.w, c12.x, r0
                cmp r3.xyz, -c5.x, r0, r1
                mov oC0, r3
            
            // approximately 36 instruction slots used (1 texture, 35 arithmetic)
            };
    }
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldViewProjection   c0       4
            //   Matrices_WorldInverseTranspose c4       3
            //   Matrices_Texture               c7       2
            //   TexelOffset                    c9       1
            //
            
                vs_2_0
                def c10, 1, 0, 0, 0
                dcl_position v0
                dcl_color v1
                dcl_normal v2
                dcl_texcoord v3
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c9, r0.z, r0
                mov oPos.w, r0.z
                dp3 r0.x, v2, c4
                dp3 r0.y, v2, c5
                dp3 r0.z, v2, c6
                dp3 r0.w, r0, r0
                rsq r0.w, r0.w
                mul oT0.xyz, r0.w, r0
                mad r0.xyz, v3.xyxw, c10.xxyw, c10.yyxw
                dp3 oT2.x, r0, c7
                dp3 oT2.y, r0, c8
                mov oT1, v1
            
            // approximately 16 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //   float Fullbright;
            //   float TextureEnabled;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   TextureEnabled  c0       1
            //   AlphaIsEmissive c1       1
            //   Fullbright      c2       1
            //
            
                preshader
                mul c0.x, c2.x, c2.x
                mul c1.x, c0.x, c0.x
                mul c2.x, c1.x, c1.x
            
            // approximately 3 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float Emissive;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c3       1
            //   Material_Opacity c4       1
            //   Emissive         c5       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c6, 0.333333343, 1, 0.5, 0
                dcl t2.xy
                dcl_2d s0
                texld r0, t2, s0
                dp3 r0.x, r0, c6.x
                cmp r0.x, -c2.x, r0.x, r0.w
                mov r1.w, c1.x
                cmp r0.x, -r1.w, c5.x, r0.x
                mov r0.y, c6.y
                cmp r0.x, -c0.x, r0.x, r0.y
                mul r0.yzw, r0.x, c3.wzyx
                mul r1.w, r0.x, c4.x
                mul r0.xyz, r0.wzyx, c6.z
                mov r1.xyz, c6.z
                mov r0.w, c6.y
                cmp r0, -c2.x, r1, r0
                mov oC0, r0
            
            // approximately 14 instruction slots used (1 texture, 13 arithmetic)
            };
    }
}

