// DefaultEffect_LitTextured
// F2EFE4BF0C543A3BC39D3425E0F2AD8657C1599A5E9E227D16FCBA7577DF5928

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldViewProjection   c0       4
            //   Matrices_WorldInverseTranspose c4       3
            //   Matrices_Texture               c7       2
            //   TexelOffset                    c9       1
            //
            
                vs_2_0
                def c10, 1, 0, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c9, r0.z, r0
                mov oPos.w, r0.z
                mad r0.xyz, v2.xyxw, c10.xxyw, c10.yyxw
                dp3 oT0.x, r0, c7
                dp3 oT0.y, r0, c8
                dp3 r0.x, v1, c4
                dp3 r0.y, v1, c5
                dp3 r0.z, v1, c6
                dp3 r0.w, r0, r0
                rsq r0.w, r0.w
                mul oT1.xyz, r0.w, r0
            
            // approximately 15 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float Emissive;
            //   float3 Eye;
            //   float Fullbright;
            //   float SpecularEnabled;
            //   float TextureEnabled;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   DiffuseLight    c0       1
            //   BaseAmbient     c1       1
            //   Eye             c2       1
            //   TextureEnabled  c3       1
            //   SpecularEnabled c4       1
            //   AlphaIsEmissive c5       1
            //   Fullbright      c6       1
            //   Emissive        c7       1
            //
            
                preshader
                mul r0.x, c6.x, c6.x
                neg r1.x, r0.x
                cmp c2.x, r1.x, c7.x, (1)
                mul c0.x, c3.x, c3.x
                mul c1.x, c5.x, c5.x
                neg r0.xyz, c1.xyz
                add c3.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c4.xyz, (1, 1, 1), r0.xyz
                mul c5.x, c4.x, c4.x
                add c6.xyz, c2.xyz, (-0, -0.25, -0)
            
            // approximately 11 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D BaseSampler;
            //   float3 DiffuseLight;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   DiffuseLight     c7       1
            //   BaseAmbient      c8       1
            //   Material_Diffuse c9       1
            //   Material_Opacity c10      1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c11, -0.00390625, 1, 0.00999999978, 0.600000024
                def c12, 0.300000012, 0.5, 0, 0
                dcl t0.xy
                dcl t1.xyz
                dcl_2d s0
                texld r0, t0, s0
                mul r1.w, r0.w, c10.x
                mov r1.x, c10.x
                cmp r1.y, -c1.x, r1.w, r1.x
                cmp r1.w, -c0.x, r1.x, r1.y
                add r2, r1.w, c11.x
                texkill r2
                abs r2.x, t1.z
                mul r2.xyz, r2.x, c3
                mov r2.w, c2.x
                cmp r0.w, -c1.x, r2.w, r0.w
                mul r0.xyz, r0, c9
                mov r3.xyz, c9
                cmp r0.xyz, -c0.x, r3, r0
                mov r2.w, c0.x
                cmp r0.w, -r2.w, c2.x, r0.w
                add_sat r3.xyz, r0.w, c8
                mul r4.xyz, r0.w, c4
                dp3_sat r0.w, t1, c11.y
                mad r3.xyz, r0.w, c3, r3
                mad r2.xyz, r2, c11.w, r3
                add r0.w, t1.z, c11.z
                cmp r2.xyz, r0.w, r3, r2
                abs r0.w, t1.x
                mul r3.xyz, r0.w, c3
                mad r3.xyz, r3, c12.x, r2
                add r0.w, t1.x, c11.z
                cmp_sat r2.xyz, r0.w, r2, r3
                mad r2.xyz, r2, c7, r4
                mul r0.xyz, r0, r2
                dp3 r0.w, c6, t1
                mul r0.w, r0.w, r0.w
                mul r0.w, r0.w, r0.w
                mul_sat r0.w, r0.w, r0.w
                mad r2.xyz, r0.w, c12.y, r0
                cmp r1.xyz, -c5.x, r0, r2
                mov oC0, r1
            
            // approximately 37 instruction slots used (1 texture, 36 arithmetic)
            };
    }
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldViewProjection   c0       4
            //   Matrices_WorldInverseTranspose c4       3
            //   Matrices_Texture               c7       2
            //   TexelOffset                    c9       1
            //
            
                vs_2_0
                def c10, 1, 0, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c9, r0.z, r0
                mov oPos.w, r0.z
                mad r0.xyz, v2.xyxw, c10.xxyw, c10.yyxw
                dp3 oT0.x, r0, c7
                dp3 oT0.y, r0, c8
                dp3 r0.x, v1, c4
                dp3 r0.y, v1, c5
                dp3 r0.z, v1, c6
                dp3 r0.w, r0, r0
                rsq r0.w, r0.w
                mul oT1.xyz, r0.w, r0
            
            // approximately 15 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //   float Fullbright;
            //   float TextureEnabled;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   TextureEnabled  c0       1
            //   AlphaIsEmissive c1       1
            //   Fullbright      c2       1
            //
            
                preshader
                mul c0.x, c2.x, c2.x
                mul c1.x, c0.x, c0.x
                mul c2.x, c1.x, c1.x
            
            // approximately 3 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float Emissive;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c3       1
            //   Material_Opacity c4       1
            //   Emissive         c5       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c6, 0.333333343, 1, 0.5, 0
                dcl t0.xy
                dcl_2d s0
                texld r0, t0, s0
                dp3 r0.x, r0, c6.x
                cmp r0.x, -c2.x, r0.x, r0.w
                mov r1.w, c1.x
                cmp r0.x, -r1.w, c5.x, r0.x
                mov r0.y, c6.y
                cmp r0.x, -c0.x, r0.x, r0.y
                mul r0.yzw, r0.x, c3.wzyx
                mul r1.w, r0.x, c4.x
                mul r0.xyz, r0.wzyx, c6.z
                mov r1.xyz, c6.z
                mov r0.w, c6.y
                cmp r0, -c2.x, r1, r0
                mov oC0, r0
            
            // approximately 14 instruction slots used (1 texture, 13 arithmetic)
            };
    }
}

