// DefaultEffect_VertexColored
// 2899B01F2494D82D5F258560662D1C4C32C63F3EA0B124B4D6523D031DF50E96

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c4       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_color v1
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c4, r0.z, r0
                mov oPos.w, r0.z
                mov oT0, v1
            
            // approximately 7 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   Material_Opacity c1       1
            //
            
                ps_2_0
                dcl t0
                mul r0.w, t0.w, c1.x
                mul r0.xyz, t0, c0
                mov oC0, r0
            
            // approximately 3 instruction slots used
            };
    }
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c4       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_color v1
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c4, r0.z, r0
                mov oPos.w, r0.z
                mov oT0, v1
            
            // approximately 7 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //   float Emissive;
            //   float Fullbright;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   Material_Opacity c1       1
            //   AlphaIsEmissive  c2       1
            //   Fullbright       c3       1
            //   Emissive         c4       1
            //
            
                preshader
                mul r0.x, c2.x, c2.x
                neg r1.x, r0.x
                mul r0.x, c3.x, c3.x
                neg r1.y, r0.x
                cmp r0.x, r1.y, c4.x, (1)
                mul r1.yzw, r0.x, c0.xyz
                mul r2.w, r0.x, c1.x
                mul r0.xyz, (0.5, 0.5, 0.5), r1.yzw
                mov r2.x, (0.5)
                mov r2.y, (0.5)
                mov r2.z, (0.5)
                mov r0.w, (1)
                cmp c0.x, r1.x, r2.x, r0.x
                cmp c0.y, r1.x, r2.y, r0.y
                cmp c0.z, r1.x, r2.z, r0.z
                cmp c0.w, r1.x, r2.w, r0.w
            
            // approximately 16 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                mov oC0, c0
            
            // approximately 1 instruction slot used
            };
    }
}

