// DefaultEffect_LitVertexColored
// FFC3533698B804B7EB0D25CB87B09C60C9FFD2C70DB9E84FF67143FCE17C9F41

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldViewProjection   c0       4
            //   Matrices_WorldInverseTranspose c4       3
            //   TexelOffset                    c7       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_color v1
                dcl_normal v2
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c7, r0.z, r0
                mov oPos.w, r0.z
                dp3 r0.x, v2, c4
                dp3 r0.y, v2, c5
                dp3 r0.z, v2, c6
                dp3 r0.w, r0, r0
                rsq r0.w, r0.w
                mul oT0.xyz, r0.w, r0
                mov oT1, v1
            
            // approximately 13 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float Emissive;
            //   float3 Eye;
            //   float Fullbright;
            //   float SpecularEnabled;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   DiffuseLight    c0       1
            //   BaseAmbient     c1       1
            //   Eye             c2       1
            //   SpecularEnabled c3       1
            //   Fullbright      c4       1
            //   Emissive        c5       1
            //
            
                preshader
                mul r0.x, c4.x, c4.x
                neg r1.x, r0.x
                cmp r0.x, r1.x, c5.x, (1)
                add r1.xyz, r0.x, c1.xyz
                max r0.yzw, (0, 0, 0), r1.xyz
                min c1.xyz, (1, 1, 1), r0.yzw
                neg r0.yzw, c1.xyz
                add c0.xyz, (1, 1, 1), r0.yzw
                neg r0.yzw, c0.xyz
                add r1.xyz, (1, 1, 1), r0.yzw
                mul c2.xyz, r0.x, r1.xyz
                mul c3.x, c3.x, c3.x
                add c4.xyz, c2.xyz, (-0, -0.25, -0)
            
            // approximately 13 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 DiffuseLight;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   DiffuseLight     c5       1
            //   Material_Diffuse c6       1
            //   Material_Opacity c7       1
            //
            
                ps_2_0
                def c8, 1, 0.00999999978, 0.600000024, 0.300000012
                def c9, 0.5, 0, 0, 0
                dcl t0.xyz
                dcl t1
                abs r0.w, t0.z
                mul r0.xyz, r0.w, c0
                dp3_sat r0.w, t0, c8.x
                mov r1.xyz, c0
                mad r1.xyz, r0.w, r1, c1
                mad r0.xyz, r0, c8.z, r1
                add r0.w, t0.z, c8.y
                cmp r0.xyz, r0.w, r1, r0
                abs r0.w, t0.x
                mul r1.xyz, r0.w, c0
                mad r1.xyz, r1, c8.w, r0
                add r0.w, t0.x, c8.y
                cmp_sat r0.xyz, r0.w, r0, r1
                mov r1.xyz, c5
                mad r0.xyz, r0, r1, c2
                mul r1.xyz, t1, c6
                mul r0.xyz, r0, r1
                dp3 r0.w, c4, t0
                mul r0.w, r0.w, r0.w
                mul r0.w, r0.w, r0.w
                mul_sat r0.w, r0.w, r0.w
                mad r1.xyz, r0.w, c9.x, r0
                cmp r0.xyz, -c3.x, r0, r1
                mul r0.w, t1.w, c7.x
                mov oC0, r0
            
            // approximately 25 instruction slots used
            };
    }
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldViewProjection   c0       4
            //   Matrices_WorldInverseTranspose c4       3
            //   TexelOffset                    c7       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_color v1
                dcl_normal v2
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c7, r0.z, r0
                mov oPos.w, r0.z
                dp3 r0.x, v2, c4
                dp3 r0.y, v2, c5
                dp3 r0.z, v2, c6
                dp3 r0.w, r0, r0
                rsq r0.w, r0.w
                mul oT0.xyz, r0.w, r0
                mov oT1, v1
            
            // approximately 13 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //   float Emissive;
            //   float Fullbright;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   Material_Opacity c1       1
            //   AlphaIsEmissive  c2       1
            //   Fullbright       c3       1
            //   Emissive         c4       1
            //
            
                preshader
                mul r0.x, c2.x, c2.x
                neg r1.x, r0.x
                mul r0.x, c3.x, c3.x
                neg r1.y, r0.x
                cmp r0.x, r1.y, c4.x, (1)
                mul r1.yzw, r0.x, c0.xyz
                mul r2.w, r0.x, c1.x
                mul r0.xyz, (0.5, 0.5, 0.5), r1.yzw
                mov r2.x, (0.5)
                mov r2.y, (0.5)
                mov r2.z, (0.5)
                mov r0.w, (1)
                cmp c0.x, r1.x, r2.x, r0.x
                cmp c0.y, r1.x, r2.y, r0.y
                cmp c0.z, r1.x, r2.z, r0.z
                cmp c0.w, r1.x, r2.w, r0.w
            
            // approximately 16 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                mov oC0, c0
            
            // approximately 1 instruction slot used
            };
    }
}

