// DotEffect
// 735B2C5FDECA1A372AABF1690291B8F916EF26D55851D42A998040CF7E98169B

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c0       1
            //
            
                preshader
                mov c7.x, c0.x
            
            // approximately 1 instruction used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float HueOffset;
            //   float3 Material_Diffuse;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c4       1
            //   Material_Diffuse             c5       1
            //   HueOffset                    c6       1
            //
            
                vs_2_0
                def c8, 6, 1, 12, -6
                def c9, -1, -2, -3, -4
                def c10, 0.349999994, 0, 0, 0
                dcl_position v0
                dcl_color v1
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c4, r0.z, r0
                mov oPos.w, r0.z
                add r0.x, v1.x, c6.x
                mul r0.y, r0.x, c8.x
                frc r0.z, r0.y
                add r0.y, -r0.z, r0.y
                mul r0.z, r0.y, c8.x
                sge r0.z, r0.z, -r0.z
                mad r0.z, r0.z, c8.z, c8.w
                rcp r0.w, r0.z
                mul r0.w, r0.w, r0.y
                mad r0.x, r0.x, c8.x, -r0.y
                frc r0.y, r0.w
                mul r0.y, r0.y, r0.z
                frc r0.z, r0.y
                add r0.w, r0.y, -r0.z
                slt r0.y, r0.y, -r0.y
                slt r0.z, -r0.z, r0.z
                mad r0.y, r0.y, r0.z, r0.w
                add r1, r0.y, c9
                mul r0.y, r0.y, r0.y
                sge r0.y, -r0.y, r0.y
                mul r1, r1, r1
                sge r1, -r1, r1
                add r0.z, -r0.x, c8.y
                mad r0.x, r0.x, -v1.y, c8.y
                mul r2.x, r0.x, v1.z
                mad r0.x, r0.z, -v1.y, c8.y
                mul r0.x, r0.x, v1.z
                mov r0.z, v1.z
                mov r2.y, v1.z
                lrp r3.xz, r1.w, r0, r2.yyxw
                mov r2.w, r0.x
                add r0.x, -v1.y, c8.y
                mul r3.y, r0.x, v1.z
                mov r2.z, r3.y
                lrp r0.xzw, r1.z, r2.zyxy, r3.xyyz
                lrp r3.xyz, r1.y, r2.zyww, r0.xzww
                lrp r0.xzw, r1.x, r2.xyyz, r3.xyyz
                lrp r1.xyz, r0.y, r2.ywzw, r0.xzww
                mul r0.xyz, r1, c5
                mul oT0.xyz, r0, c10.x
                mov oT0.w, c7.x
            
            // approximately 47 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                dcl t0
                mov oC0, t0
            
            // approximately 1 instruction slot used
            };
    }
}

