// FakePointSpritesEffect
// 7F3881827B65EADDD2404E42BC6BCB297FD9D42C49135053BD76179128646E8B

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float2 TexelOffset;
            //   float ViewScale;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelOffset  c0       1
            //   ViewScale    c1       1
            //
            
                preshader
                neg r0.xy, c0.xy
                mul c5.xy, c1.x, r0.xy
            
            // approximately 2 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Material_Opacity;
            //   float4x4 Matrices_WorldViewProjection;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Material_Opacity             c4       1
            //
            
                vs_2_0
                def c6, 2, 0.00175000005, 1.44269502, 1
                def c7, 0, 0, 0, 0
                dcl_position v0
                dcl_color v1
                dcl_texcoord v2
                dcl_texcoord1 v3
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mul r1.xy, r0.z, v3
                mul r1.xy, r1, c5
                mad oPos.xy, r1, c6.x, r0
                mov r0.x, c4.x
                mov r0.w, v1.w
                mul r1, r0.xxxw, v1
                mul oD0, r0.wwwx, r1
                mul r0.x, r0.z, c6.y
                mov oPos.w, r0.z
                mul r0.y, r0.x, r0.x
                mul r0.x, r0.y, r0.x
                mul r0.x, r0.x, c6.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                add r0.x, -r0.x, c6.w
                max r0.x, r0.x, c7.x
                min oT1.x, r0.x, c6.w
                mov oT0.xy, v2
            
            // approximately 22 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c0, 0, 0, 0, 1
                dcl v0
                dcl t0.xy
                dcl t1.x
                dcl_2d s0
                texld r0, t0, s0
                add r1, -v0, c0
                mov r2, v0
                mad r1, t1.x, r1, r2
                mul r0, r0, r1
                mov oC0, r0
            
            // approximately 6 instruction slots used (1 texture, 5 arithmetic)
            };
    }
}

