// FarAwayEffect
// 6BD67ADFAF58B798C67FAA2C6112F91097CD1877399BE2A3C775FF59921128E9

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c4       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_texcoord v1
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c4, r0.z, r0
                mov oPos.w, r0.z
                mov oT0.xy, v1
            
            // approximately 7 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float ActualOpacity;
            //   sampler2D BaseSampler;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   Material_Opacity c1       1
            //   ActualOpacity    c2       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c3, -0.00390625, 0, 0, 0
                dcl t0.xy
                dcl_2d s0
                texld r0, t0, s0
                mov r1.w, c2.x
                mad r1, r0.w, r1.w, c3.x
                texkill r1
                add r0.xyz, r0, -c0
                mul r1.w, r0.w, c2.x
                mov r2.xyz, c0
                mad r1.xyz, c1.x, r0, r2
                mov oC0, r1
            
            // approximately 9 instruction slots used (1 texture, 8 arithmetic)
            };
    }
}

