// FastBlurEffect
// D425FF55A5564CA9ACDAA0B19989939F9D2AC33A88C40CE570BE157AE5538F0A

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float BlurWidth;
            //   float2 Direction;
            //   float2 TexelSize;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelSize    c0       1
            //   BlurWidth    c1       1
            //   Direction    c2       1
            //
            
                preshader
                mul r0.xy, c0.xy, c2.xy
                mul c0.xy, c1.x, r0.xy
            
            // approximately 2 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                vs_2_0
                dcl_position v0
                dcl_texcoord v1
                mov oT0.xy, v1
                mov oT1.xy, c0
                mov oPos, v0
            
            // approximately 3 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Offsets[5];
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Offsets      c0       5
            //
            
                preshader
                add c5.x, c4.x, (7.5)
                add c6.x, c3.x, (5.5)
                add c7.x, c2.x, (3.5)
                add c8.x, c1.x, (1.5)
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float Weights[5];
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Weights      c0       5
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                dcl t0.xy
                dcl t1.xy
                dcl_2d s0
                mov r0.xy, t0
                mad r1.xy, t1, -c6.x, r0
                mad r2.xy, t1, -c5.x, r0
                mad r3.xy, t1, -c7.x, r0
                mad r4.xy, t1, -c8.x, r0
                mad r5.xy, t1, c8.x, r0
                mad r6.xy, t1, c7.x, r0
                mad r7.xy, t1, c6.x, r0
                mad r0.xy, t1, c5.x, r0
                texld r1, r1, s0
                texld r2, r2, s0
                texld r3, r3, s0
                texld r4, r4, s0
                texld r8, t0, s0
                texld r5, r5, s0
                texld r6, r6, s0
                texld r7, r7, s0
                texld r0, r0, s0
                mul r1, r1, c3.x
                mad r1, r2, c4.x, r1
                mad r1, r3, c2.x, r1
                mad r1, r4, c1.x, r1
                mad r1, r8, c0.x, r1
                mad r1, r5, c1.x, r1
                mad r1, r6, c2.x, r1
                mad r1, r7, c3.x, r1
                mad r0, r0, c4.x, r1
                mov oC0, r0
            
            // approximately 28 instruction slots used (9 texture, 19 arithmetic)
            };
    }
}

