// FoamEffect
// D5A74AD87A7BC194B7BE3F243B75D1A20F24CA7F5372C505A052D91B1A43EB15

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float IsEmerged;
            //   float IsWobbling;
            //   float ShoreTotalWidth;
            //   float TimeAccumulator;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   TimeAccumulator c0       1
            //   ShoreTotalWidth c1       1
            //   IsEmerged       c2       1
            //   IsWobbling      c3       1
            //
            
                preshader
                mul r0.x, c3.x, c3.x
                neg r1.x, r0.x
                lt c4.x, r1.x, r0.x
                rcp c0.x, c1.x
                mul c1.x, c0.x, (3)
                mul r0.x, c2.x, c2.x
                neg r1.x, r0.x
                lt c3.x, r1.x, r0.x
            
            // approximately 8 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldViewProjection;
            //   float ScreenCenterSide;
            //   float ShoreTotalWidth;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c5       4
            //   TexelOffset                  c9       1
            //   ShoreTotalWidth              c10      1
            //   ScreenCenterSide             c11      1
            //
            
                vs_2_0
                def c12, 0.5, 2, 0.159154937, -1
                def c13, 6.28318548, -3.14159274, 3, 0.333333343
                def c14, -1.55009923e-006, -2.17013894e-005, 0.00260416674, 0.00026041668
                def c15, -0.020833334, -0.125, 1, 0.5
                dcl_position v0
                dcl_normal v1
                add r0.x, v1.x, -c11.x
                slt r0.y, -r0.x, r0.x
                slt r0.z, r0.x, -r0.x
                add r0.y, -r0.z, r0.y
                mul r0.y, r0.y, c10.x
                mad r0.x, r0.y, c12.x, r0.x
                mul r0.x, r0.x, c0.x
                frc r0.y, r0.x
                add r0.z, r0.x, -r0.y
                slt r0.x, r0.x, -r0.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mad r0.x, r0.x, -c10.x, v1.x
                mov r0.y, c12.y
                mad r0.y, r0.x, r0.y, c1.x
                add r1.x, r0.x, v0.x
                mad r0.x, r0.y, c12.z, c12.x
                frc r0.x, r0.x
                mad r0.x, r0.x, c13.x, c13.y
                sincos r2.y, r0.x, c14, c15
                slt r0.x, -r2.y, r2.y
                slt r0.y, r2.y, -r2.y
                abs r0.z, r2.y
                add r0.z, -r0.z, c13.z
                add r0.x, -r0.y, r0.x
                add r0.x, r0.x, c12.w
                mul r0.x, r0.x, r0.x
                slt r0.y, -r0.x, r0.x
                sge r0.x, -r0.x, r0.x
                rcp r0.w, r0.z
                mul r0.z, r0.z, c13.w
                mad r0.w, r0.w, c13.z, -r0.z
                mad r0.y, r0.y, r0.w, r0.z
                mad r0.x, r0.x, r0.w, r0.z
                lrp r1.z, c3.x, r0.y, r0.x
                mul r1.y, r1.z, v0.y
                lrp r0.xy, c4.x, r1, v0
                mov r0.zw, v0
                dp4 oPos.z, r0, c7
                dp4 r1.x, r0, c5
                dp4 r1.y, r0, c6
                dp4 r0.x, r0, c8
                mad oPos.xy, c9, r0.x, r1
                mov oPos.w, r0.x
            
            // approximately 51 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   Material_Opacity c1       1
            //
            
                preshader
                mov c0.xyz, c0.xyz
                mov c0.w, c1.x
            
            // approximately 2 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                mov oC0, c0
            
            // approximately 1 instruction slot used
            };
    }
}

