// GammaCorrection
// C66DCEA588F5465A1ED8465A55EAD038312BA4CFCE7B056E9E8A7B8F2A38FA0B

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass GammaCorrect
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelOffset  c0       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_texcoord v1
                mad oPos.xy, c0, v0.w, v0
                mov oT0.xy, v1
                mov oPos.zw, v0
            
            // approximately 3 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Brightness;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Brightness   c0       1
            //
            
                preshader
                add r0.x, c0.x, (-0.5)
                mul c1.x, r0.x, (0.25)
                add r0.x, c0.x, (0.5)
                rcp c0.x, r0.x
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D MainBufferSampler;
            //
            //
            // Registers:
            //
            //   Name              Reg   Size
            //   ----------------- ----- ----
            //   MainBufferSampler s0       1
            //
            
                ps_2_0
                def c2, 1, 0, 0, 0
                dcl t0.xy
                dcl_2d s0
                texld r0, t0, s0
                log r1.x, r0.x
                log r1.y, r0.y
                log r1.z, r0.z
                mul r0.xyz, r1, c0.x
                exp r1.x, r0.x
                exp r1.y, r0.y
                exp r1.z, r0.z
                add_sat r0.xyz, r1, c1.x
                mov r0.w, c2.x
                mov oC0, r0
            
            // approximately 11 instruction slots used (1 texture, 10 arithmetic)
            };
    }
}

