// GlitchyPostEffect
// 2B68A10233805944DD6564BDE029B9641E7752BA24BFE829C1D8ABF899C20D52

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass P0
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 InstanceData[60];
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   InstanceData c0     240
            //
            
                vs_2_0
                def c240, 4, 1, 0, -1
                def c241, 0.0375002325, 0.0666666701, 1, 0.0234378669
                def c242, 0, 0.0234378669, 0, 0
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord1 v2
                mov r0.w, c240.y
                mov r1.z, v0.z
                mad r2, v0.xyzx, c240.yyyz, c240.zzzy
                slt r1.w, v2.x, -v2.x
                frc r3.x, v2.x
                add r3.y, -r3.x, v2.x
                slt r3.x, -r3.x, r3.x
                mad r1.w, r1.w, r3.x, r3.y
                mul r1.w, r1.w, c240.x
                mova a0.x, r1.w
                mov r3.yzw, c240
                mul r4.xy, r3.yzzw, c2[a0.x].x
                mov r4.w, c0[a0.x].x
                dp4 r1.x, r2, r4.xyyw
                mov r2.xyz, v0
                mov r2.w, c1[a0.x].x
                mad r4, c3[a0.x].x, r3.zyzz, r3.zzzy
                dp4 r1.y, r2, r4
                mad r0.xyz, r1, c241, r3.wwzw
                mul r1.x, c3[a0.x].w, c3[a0.x].w
                slt r1.x, -r1.x, r1.x
                mad oPos, r1.x, -r0, r0
                mad r0.xyz, v1.xyxw, c240.yyzw, c240.zzyw
                mov r1.x, c2[a0.x].x
                mul r1.xy, r1.x, c242.yxzw
                mov r1.z, c0[a0.x].w
                dp3 oT0.x, r0, r1
                mov r0.xy, v1
                mov r1.x, c3[a0.x].x
                mad r0.w, r1.x, -c241.w, c241.z
                add r0.z, r0.w, c1[a0.x].w
                mov r1.yz, c240
                mad r1.xyz, r1.x, c242.xyxw, r1.zzyw
                dp3 oT0.y, r0, r1
                mov oT1.x, c0[a0.x].y
                mov oT1.y, c1[a0.x].y
                mov oT1.z, c2[a0.x].y
                mov oT1.w, c3[a0.x].y
                mov oT2.x, c0[a0.x].z
                mov oT2.y, c1[a0.x].z
                mov oT2.z, c2[a0.x].z
            
            // approximately 41 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D GlitchSampler;
            //
            //
            // Registers:
            //
            //   Name          Reg   Size
            //   ------------- ----- ----
            //   GlitchSampler s0       1
            //
            
                ps_2_0
                def c0, 1, 0.333333343, 0, -0.5
                dcl t0.xy
                dcl t1
                dcl t2.xyz
                dcl_2d s0
                texld r0, t0, s0
                mul r1.w, t2.y, t2.y
                mul r1.x, t1.y, t1.y
                mul r1.y, t1.x, t1.x
                cmp r2.x, -r1.y, r0.x, r0.y
                cmp r2.y, -r1.y, r0.y, r0.x
                mov r0.x, r2.y
                mov r0.y, r0.z
                add r0.z, -r0.w, c0.x
                cmp r3.x, -r1.x, r0.x, r0.y
                cmp r3.y, -r1.x, r0.y, r0.x
                add r0.x, -r3.x, c0.x
                cmp r1.y, -r1.w, r3.x, r0.x
                mov r2.y, r3.y
                mul r0.x, t1.z, t1.z
                cmp r3.x, -r0.x, r2.x, r2.y
                cmp r3.y, -r0.x, r2.y, r2.x
                add r0.x, -r3.x, c0.x
                mul r0.y, t2.x, t2.x
                cmp r1.x, -r0.y, r3.x, r0.x
                add r0.x, -r3.y, c0.x
                mul r0.y, t2.z, t2.z
                cmp r1.z, -r0.y, r3.y, r0.x
                dp3 r0.x, r1, c0.y
                add r0.y, r0.x, c0.w
                add r0.x, -r0.z, -r0.x
                add r0.y, -r0.z, r0.y
                add r0.x, r0.x, -c0.w
                mul r0.z, t1.w, t1.w
                cmp r0.w, -r0.z, c0.z, c0.x
                cmp r0.z, -r0.z, c0.x, c0.z
                mul r2, r0.z, r0.x
                mul r0, r0.w, r0.y
                texkill r2
                texkill r0
                mov r1.w, c0.x
                mov oC0, r1
            
            // approximately 37 instruction slots used (1 texture, 36 arithmetic)
            };
    }
}

