// GomezEffect
// E7E874FBD447516974FB518CE3131179769605707DF3AA455BF857CEA2EAE606

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //
            
                preshader
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c11.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c10.x, r0.x, r1.x
            
            // approximately 7 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_ViewProjection;
            //   float4x4 Matrices_World;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                    Reg   Size
            //   ----------------------- ----- ----
            //   Matrices_World          c0       4
            //   Matrices_ViewProjection c4       4
            //   Matrices_Texture        c8       2
            //   Fog_Density             c12      1
            //   Eye                     c13      1
            //   TexelOffset             c14      1
            //   EyeSign                 c15      1
            //   LevelCenter             c16      1
            //
            
                vs_2_0
                def c17, 1, 0, 2, -0.387499988
                def c18, 1.44269502, 0, 0, 0
                dcl_position v0
                dcl_texcoord v1
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c2
                add r1.xyz, r0, -c16
                dp3 r0.w, r1, c13
                mad r0.xyz, r0.w, c15, r0
                dp4 r0.w, v0, c3
                dp4 oPos.z, r0, c6
                dp4 r1.x, r0, c4
                dp4 r1.y, r0, c5
                dp4 r0.x, r0, c7
                mad oPos.xy, c14, r0.x, r1
                mad r0.yzw, v1.xxyx, c17.xxxy, c17.xyyx
                dp3 oT2.x, r0.yzww, c8
                dp3 oT2.y, r0.yzww, c9
                mad oT3.x, v1.y, c17.z, c17.w
                mul r0.y, r0.x, c12.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c18.x
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c10.x
                mad r0.x, r0.x, r1.x, c11.x
                max r0.x, r0.x, c17.y
                min oT1.x, r0.x, c17.x
            
            // approximately 27 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 DiffuseLight;
            //   float NoMoreFez;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   NoMoreFez    c1       1
            //
            
                preshader
                mul r0.x, c1.x, c1.x
                neg r1.x, r0.x
                mov c0.x, r0.x
                cmp c1.x, r1.x, (-0), (-1)
                mul c2.xyz, (0.5, 0.5, 0.5), c0.xyz
            
            // approximately 5 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AnimatedSampler;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c3       1
            //   AnimatedSampler  s0       1
            //
            
                ps_2_0
                def c4, -0.00390625, -0.5, 0, -0.25
                def c5, 0, 1, -0, -1
                dcl t2.xy
                dcl t3.x
                dcl_2d s0
                texld r0, t2, s0
                mov r1.xz, c4
                mad r2, r0.w, c3.x, r1.x
                cmp r1.x, -c0.x, r1.z, t3.x
                add r0.x, r0.x, c4.y
                cmp r3, r0.x, c4.z, r1.x
                cmp r0.x, r0.x, c1.x, -r1.z
                add r0.y, r0.y, c4.w
                cmp r1, r0.y, -c4.z, r0.x
                add r0.z, r0.z, c4.y
                cmp r0.x, r0.z, -c4.z, r0.x
                cmp r4, r0.y, r0.x, c4.z
                texkill r2
                texkill r3
                texkill r1
                texkill r4
                mul r0.x, r0.w, c3.x
                cmp r0.y, -r0.x, c5.x, c5.y
                cmp r0.x, r0.x, c5.z, c5.w
                add r0.w, r0.x, r0.y
                mov r0.xyz, c2
                mov oC0, r0
            
            // approximately 22 instruction slots used (1 texture, 21 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //
            
                preshader
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c11.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c10.x, r0.x, r1.x
            
            // approximately 7 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_ViewProjection;
            //   float4x4 Matrices_World;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                    Reg   Size
            //   ----------------------- ----- ----
            //   Matrices_World          c0       4
            //   Matrices_ViewProjection c4       4
            //   Matrices_Texture        c8       2
            //   Fog_Density             c12      1
            //   Eye                     c13      1
            //   TexelOffset             c14      1
            //   EyeSign                 c15      1
            //   LevelCenter             c16      1
            //
            
                vs_2_0
                def c17, 1, 0, 2, -0.387499988
                def c18, 1.44269502, 0, 0, 0
                dcl_position v0
                dcl_texcoord v1
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c2
                add r1.xyz, r0, -c16
                dp3 r0.w, r1, c13
                mad r0.xyz, r0.w, c15, r0
                dp4 r0.w, v0, c3
                dp4 oPos.z, r0, c6
                dp4 r1.x, r0, c4
                dp4 r1.y, r0, c5
                dp4 r0.x, r0, c7
                mad oPos.xy, c14, r0.x, r1
                mad r0.yzw, v1.xxyx, c17.xxxy, c17.xyyx
                dp3 oT2.x, r0.yzww, c8
                dp3 oT2.y, r0.yzww, c9
                mad oT3.x, v1.y, c17.z, c17.w
                mul r0.y, r0.x, c12.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c18.x
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c10.x
                mad r0.x, r0.x, r1.x, c11.x
                max r0.x, r0.x, c17.y
                min oT1.x, r0.x, c17.x
            
            // approximately 27 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float ColorSwap;
            //   float NoMoreFez;
            //   float Silhouette;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Silhouette   c0       1
            //   ColorSwap    c1       1
            //   NoMoreFez    c2       1
            //
            
                preshader
                mul c0.x, c1.x, c1.x
                mul r0.x, c2.x, c2.x
                neg r1.x, r0.x
                mov c1.x, r0.x
                cmp c2.x, r1.x, (-0), (-1)
                mul c3.x, c0.x, c0.x
            
            // approximately 6 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AnimatedSampler;
            //   float Background;
            //   float3 BlackSwap;
            //   float3 Fog_Color;
            //   float3 GraySwap;
            //   float Material_Opacity;
            //   float3 RedSwap;
            //   float3 WhiteSwap;
            //   float3 YellowSwap;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Fog_Color        c4       1
            //   Material_Opacity c5       1
            //   Background       c6       1
            //   RedSwap          c7       1
            //   BlackSwap        c8       1
            //   WhiteSwap        c9       1
            //   YellowSwap       c10      1
            //   GraySwap         c11      1
            //   AnimatedSampler  s0       1
            //
            
                ps_2_0
                def c12, -0.00390625, -0.5, 0.75, 0
                def c13, -0.25, 1, 0, 0
                dcl t1.x
                dcl t2.xy
                dcl t3.x
                dcl_2d s0
                texld r0, t2, s0
                mov r1.xw, c12
                mad r2, r0.w, c5.x, r1.x
                add r1.x, -r0.x, c12.z
                mov r3.xyz, c11
                cmp r1.xyz, r1.x, r3, c9
                add r3.x, r0.z, c12.y
                cmp r1.xyz, r3.x, r1, c10
                add r3.x, r0.y, c12.y
                cmp r1.xyz, r3.x, r1, c7
                add r3.x, r0.x, c12.y
                cmp r1.xyz, r3.x, r1, c8
                cmp r3.xyz, -c0.x, r0, r1
                add r0.x, r3.x, c12.y
                cmp r0.y, -c1.x, r1.w, t3.x
                cmp r4, r0.x, c12.w, r0.y
                cmp r0.x, r0.x, c2.x, -r1.w
                add r0.y, r3.y, c13.x
                cmp r1, r0.y, -c12.w, r0.x
                add r0.z, r3.z, c12.y
                cmp r0.x, r0.z, -c12.w, r0.x
                cmp r5, r0.y, r0.x, c12.w
                texkill r2
                texkill r4
                texkill r1
                texkill r5
                mul r3.w, r0.w, c5.x
                mul r0.w, r3.w, -c12.y
                mov r0.xyz, c12.w
                cmp r0, -c3.x, r3, r0
                mul r1.xyz, r0, c6.x
                mad r1.xyz, r1, c12.y, r0
                add r2.xyz, -r1, c4
                add r1.w, -t1.x, c13.y
                mad r0.xyz, r1.w, r2, r1
                mov oC0, r0
            
            // approximately 36 instruction slots used (1 texture, 35 arithmetic)
            };
    }
}

