// HorizontalTrailsEffect
// 7DF5461DCCFCFEB4B98ACF82D9E9BA368CB88530C40B9F7E142D66F8411348CD

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Timing;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Timing       c0       1
            //
            
                preshader
                mul r0.x, c0.x, (0.166666672)
                mul r1.x, r0.x, r0.x
                mul r0.x, r1.x, r1.x
                mul c4.x, r0.x, (0.100000001)
                mul r1.x, r0.x, (0.400000006)
                mov c7.x, r0.x
                mul r0.x, r1.x, r1.x
                mul r2.x, r0.x, r1.x
                mul r0.x, r2.x, (0.5)
                min r1.x, r0.x, (1)
                neg r0.x, r1.x
                mov c5.x, r1.x
                add c6.x, r0.x, (1)
            
            // approximately 13 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float4x4 Matrices_WorldViewProjection;
            //   float3 Right;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Eye                          c8       1
            //   TexelOffset                  c9       1
            //   Right                        c10      1
            //
            
                vs_2_0
                def c11, 3, 0.333333343, 0, 1
                def c12, 6, 12, -6, 0.5
                def c13, -1, -2, -3, -4
                def c14, 10, 50, 750, 0
                def c15, 1.33333337, 0.25, 0, 0
                dcl_position v0
                dcl_color v1
                rsq r0.x, v1.z
                rcp r0.x, r0.x
                abs r0.y, v1.z
                mul r0.y, r0.y, r0.y
                mad r0.x, r0.y, -r0.y, r0.x
                mul r0.y, r0.y, r0.y
                mad r0.x, c4.x, r0.x, r0.y
                mul r0.y, r0.x, c7.x
                max r0.x, r0.x, c11.z
                min r1.y, r0.x, c11.w
                mul r0.x, r0.y, c12.w
                abs r0.x, r0.x
                pow r2.x, r0.x, c14.x
                mul r0.x, r2.x, c14.y
                min r0.x, r0.x, c14.z
                mul r0.xyz, r0.x, -c10
                add r0.w, v1.w, -c11.w
                mul r0.w, r0.w, r0.w
                sge r0.w, -r0.w, r0.w
                mad r0.xyz, r0.w, r0, v0
                mov r0.w, v0.w
                dp4 oPos.z, r0, c2
                dp4 r2.x, r0, c0
                dp4 r2.y, r0, c1
                dp4 r0.x, r0, c3
                mad oPos.xy, c9, r0.x, r2
                mov oPos.w, r0.x
                dp3 r0.x, v0, c8
                sge oT0.w, r0.x, c11.z
                slt r0.x, r0.x, c11.z
                mul r0.y, v1.x, c11.x
                frc r0.z, r0.y
                add r0.y, -r0.z, r0.y
                mul r0.y, r0.y, c11.y
                max r0.y, r0.y, c11.z
                min r0.y, r0.y, c11.w
                mul r0.z, r0.y, c12.x
                frc r0.w, r0.z
                add r0.z, -r0.w, r0.z
                mul r0.w, r0.z, c12.x
                sge r0.w, r0.w, -r0.w
                mad r0.w, r0.w, c12.y, c12.z
                rcp r2.x, r0.w
                mul r2.x, r0.z, r2.x
                mad r0.y, r0.y, c12.x, -r0.z
                frc r0.z, r2.x
                mul r0.z, r0.z, r0.w
                frc r0.w, r0.z
                add r2.x, r0.z, -r0.w
                slt r0.z, r0.z, -r0.z
                slt r0.w, -r0.w, r0.w
                mad r0.z, r0.z, r0.w, r2.x
                add r2, r0.z, c13
                mul r0.z, r0.z, r0.z
                sge r0.z, -r0.z, r0.z
                mul r2, r2, r2
                sge r2, -r2, r2
                add r0.w, -r0.y, c11.w
                mov r3.w, c11.w
                mad r0.y, r0.y, -c5.x, r3.w
                mul r1.z, r0.y, r1.y
                mad r0.y, r0.w, -c5.x, r3.w
                mul r1.x, r0.y, r1.y
                lrp r3.xz, r2.w, r1.xyyw, r1.yyzw
                mul r3.y, r1.y, c6.x
                mov r1.w, r3.y
                lrp r4.xyz, r2.z, r1.wzyw, r3
                lrp r3.xyz, r2.y, r1.wyxw, r4
                lrp r4.xyz, r2.x, r1.zyww, r3
                lrp r2.xyz, r0.z, r1.yxww, r4
                add r0.y, -v1.w, c11.w
                mad r0.y, r0.y, c15.x, c15.y
                mul r0.yzw, r0.y, r2.xxyz
                mad oT0.xyz, r0.x, -r0.yzww, r0.yzww
            
            // approximately 76 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                dcl t0
                mov oC0, t0
            
            // approximately 1 instruction slot used
            };
    }
}

