// HwGlitchyPostEffect
// 80DFFEDBAC9BF6BF013BD26BB081069CD2508B5D355EC23849F9F618ACB75473

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass P0
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                vs_3_0
                def c0, 1, 0, 0.0375002325, 0.0666666701
                def c1, -1, 0, 0.0234378669, 1
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord2 v2
                dcl_texcoord3 v3
                dcl_texcoord4 v4
                dcl_texcoord5 v5
                dcl_texcoord o0.xy
                dcl_texcoord1 o1
                dcl_texcoord2 o2.xyz
                dcl_position o3
                mov r0.xyz, v0
                mov r0.w, v2.y
                mad r1, v2.zwzz, c0.yxyy, c0.yyyx
                dp4 r0.y, r0, r1
                mad r1, v0.xyzx, c0.xxxy, c0.yyyx
                mul r2, c0.xyyx, v2.zzzx
                dp4 r0.x, r1, r2
                mov r0.z, v0.z
                mov r1.xzw, c0
                mad r0.xyz, r0, r1.zwxw, c1.xxyw
                slt r1.x, -v5_abs.w, v5_abs.w
                mov r0.w, c0.x
                mad o3, r1.x, -r0, r0
                mad r0.xyz, v1.xyxw, c0.xxyw, c0.yyxw
                mul r1.xy, c1.zyzw, v2.z
                mov r1.z, v5.x
                dp3 o0.x, r0, r1
                mov r0.w, v2.w
                mad r0.x, r0.w, -c1.z, v5.y
                add r0.z, r0.x, c0.x
                mov r0.xy, v1
                mad r1.xyz, v2.zwzw, c1.yzyw, c1.yyww
                dp3 o0.y, r0, r1
                mov o1, v3
                mov o2.xyz, v4
            
            // approximately 25 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D GlitchSampler;
            //
            //
            // Registers:
            //
            //   Name          Reg   Size
            //   ------------- ----- ----
            //   GlitchSampler s0       1
            //
            
                ps_3_0
                def c0, 1, 0.333333343, 0, -0.5
                dcl_texcoord v0.xy
                dcl_texcoord1 v1
                dcl_texcoord2 v2.xyz
                dcl_2d s0
                texld r0, v0, s0
                cmp r0.xy, -v1_abs.x, r0, r0.yxzw
                add r1.x, -r0.w, c0.x
                cmp r0.yz, -v1_abs.y, r0, r0.xzyw
                mov r0.w, r0.z
                cmp r0.xz, -v1_abs.z, r0.xyww, r0.wyxw
                add r1.yz, -r0.xxzw, c0.x
                cmp r2.xz, -v2_abs, r0, r1.yyzw
                add r0.x, -r0.y, c0.x
                cmp r2.y, -v2_abs.y, r0.y, r0.x
                dp3 r0.x, r2, c0.y
                mov oC0.xyz, r2
                add r0.y, r0.x, c0.w
                add r0.x, -r1.x, -r0.x
                add r0.y, -r1.x, r0.y
                add r0.x, r0.x, -c0.w
                cmp r0.zw, -v1_abs.w, c0.xyzx, c0.xyxz
                mul r1, r0.z, r0.y
                mul r0, r0.w, r0.x
                texkill r0
                texkill r1
                mov oC0.w, c0.x
            
            // approximately 22 instruction slots used (1 texture, 21 arithmetic)
            };
    }
}

