// HwInstancedArtObjectEffect
// FA04DD1AF77BA1D4DD5C3B35FD9397A2B47679DDA79EFBE13AC62B04B73588BA

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //
            
                preshader
                neg r0.x, c0.x
                max r1.x, r0.x, c0.x
                neg r0.x, r1.x
                ge c5.x, r0.x, r1.x
                add r0.x, c0.x, (-2)
                neg r1.x, r0.x
                max r2.x, r0.x, r1.x
                neg r0.x, r2.x
                ge c4.x, r0.x, r2.x
            
            // approximately 9 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Fog_Density                  c6       1
            //   Eye                          c7       1
            //   TexelOffset                  c8       1
            //   EyeSign                      c9       1
            //   LevelCenter                  c10      1
            //
            
                vs_3_0
                def c11, 2, 1, 1.44269502, 0.5
                def c12, -2, 1, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord2 v3
                dcl_texcoord3 v4
                dcl_texcoord4 v5
                dcl_texcoord5 v6
                dcl_texcoord o0.xyz
                dcl_texcoord1 o1.x
                dcl_texcoord2 o2.xy
                dcl_texcoord3 o3.x
                dcl_texcoord4 o4.x
                dcl_texcoord5 o5.x
                dcl_position o6
                mul r0.x, v5.w, v5.x
                mad r0.y, v5.y, v5.z, -r0.x
                mad r0.x, v5.y, v5.z, r0.x
                add r1.y, r0.x, r0.x
                add r0.z, r0.y, r0.y
                mul r2.xyz, v5, v5
                add r2.xyz, r2.zxxw, r2.yzyw
                mad r2.xyz, r2, -c11.x, c11.y
                mov r0.y, r2.y
                mul r3.xyz, v5.wxww, v5.zzyw
                mad r0.w, v5.x, v5.y, r3.x
                add r0.x, r0.w, r0.w
                dp3 o0.y, v1, r0
                mul r0.xz, r0, v4
                mad r1.w, v5.x, v5.y, -r3.x
                add r4.y, r1.w, r1.w
                add r1.w, r3.z, r3.y
                mad r2.w, v5.z, v5.x, -r3.z
                add r1.x, r2.w, r2.w
                add r4.z, r1.w, r1.w
                mul r3.yz, r4, v4
                mov r3.w, v3.x
                mul r5.xyz, r2, v4
                mov r3.x, r5.x
                dp4 r3.x, v0, r3
                mov r0.y, r5.y
                mov r0.w, v3.y
                dp4 r3.y, v0, r0
                mul r5.xy, r1, v4
                mov r5.w, v3.z
                dp4 r3.z, v0, r5
                add r0.xyz, r3, -c10
                dp3 r0.x, r0, c7
                mad r0.xyz, r0.x, c9, r3
                mov r0.w, v0.w
                dp4 o6.z, r0, c2
                dp4 r3.x, r0, c0
                dp4 r3.y, r0, c1
                dp4 r0.x, r0, c3
                mad o6.xy, c8, r0.x, r3
                mul r0.y, r0.x, c6.x
                mov o6.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c11.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r3.x, c4.x
                mad r0.x, r0.x, r3.x, c5.x
                add o1.x, -r0.x, c11.y
                mov r1.z, r2.z
                mov r4.x, r2.x
                dp3 r0.x, v1, r4
                dp3 r0.z, v1, r1
                slt r0.yw, c11.w, r0.xzzx
                slt r1, -v6_abs, v6_abs
                mul r0.yw, r0, r1.xxzy
                mad r0.y, r0.y, c12.x, c12.y
                lrp r1.x, r0.w, -c11.y, r0.y
                slt r0.yw, r0.xzzx, -c11.w
                mov o0.xz, r0
                mul r0.xy, r0.ywzw, r1.zwzw
                lrp r2.x, r0.x, -c11.y, r1.x
                add r0.x, -r2.x, -c11.y
                mad o3.x, r0.y, r0.x, r2.x
                slt o5.x, -v4_abs.w, v4_abs.w
                mov o2.xy, v2
                mov o4.x, v3.w
            
            // approximately 68 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   BaseAmbient  c1       1
            //
            
                preshader
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D CubemapSampler;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name           Reg   Size
            //   -------------- ----- ----
            //   DiffuseLight   c2       1
            //   BaseAmbient    c3       1
            //   CubemapSampler s0       1
            //
            
                ps_3_0
                def c4, -0.00390625, 1, 0.00999999978, 0.600000024
                def c5, 0.300000012, 0.5, 0, 0
                dcl_texcoord v0.xyz
                dcl_texcoord1 v1.x
                dcl_texcoord2 v2.xy
                dcl_texcoord3 v3.x
                dcl_texcoord4 v4.x
                dcl_2d s0
                mov r0, v3.x
                texkill r0
                add r0, c4.x, v4.x
                texkill r0
                mul r0.xyz, c0, v0_abs.z
                dp3_sat r0.w, v0, c4.y
                texld r1, v2, s0
                add_sat r1.xyz, r1.w, c3
                mul r2.xyz, r1.w, c1
                mad r1.xyz, r0.w, c0, r1
                mad r0.xyz, r0, c4.w, r1
                add r3.xy, c4.z, v0.zxzw
                cmp r0.xyz, r3.x, r1, r0
                mul r1.xyz, c0, v0_abs.x
                mad r1.xyz, r1, c5.x, r0
                cmp_sat r0.xyz, r3.y, r0, r1
                mad r0.xyz, r0, c2, r2
                lrp r1.xyz, v1.x, c4.y, r0
                mul oC0.xyz, r1, c5.y
                mov oC0.w, v4.x
            
            // approximately 20 instruction slots used (1 texture, 19 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //
            
                preshader
                neg r0.x, c0.x
                max r1.x, r0.x, c0.x
                neg r0.x, r1.x
                ge c5.x, r0.x, r1.x
                add r0.x, c0.x, (-2)
                neg r1.x, r0.x
                max r2.x, r0.x, r1.x
                neg r0.x, r2.x
                ge c4.x, r0.x, r2.x
            
            // approximately 9 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Fog_Density                  c6       1
            //   Eye                          c7       1
            //   TexelOffset                  c8       1
            //   EyeSign                      c9       1
            //   LevelCenter                  c10      1
            //
            
                vs_3_0
                def c11, 2, 1, 1.44269502, 0.5
                def c12, -2, 1, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord2 v3
                dcl_texcoord3 v4
                dcl_texcoord4 v5
                dcl_texcoord5 v6
                dcl_texcoord o0.xyz
                dcl_texcoord1 o1.x
                dcl_texcoord2 o2.xy
                dcl_texcoord3 o3.x
                dcl_texcoord4 o4.x
                dcl_texcoord5 o5.x
                dcl_position o6
                mul r0.x, v5.w, v5.x
                mad r0.y, v5.y, v5.z, -r0.x
                mad r0.x, v5.y, v5.z, r0.x
                add r1.y, r0.x, r0.x
                add r0.z, r0.y, r0.y
                mul r2.xyz, v5, v5
                add r2.xyz, r2.zxxw, r2.yzyw
                mad r2.xyz, r2, -c11.x, c11.y
                mov r0.y, r2.y
                mul r3.xyz, v5.wxww, v5.zzyw
                mad r0.w, v5.x, v5.y, r3.x
                add r0.x, r0.w, r0.w
                dp3 o0.y, v1, r0
                mul r0.xz, r0, v4
                mad r1.w, v5.x, v5.y, -r3.x
                add r4.y, r1.w, r1.w
                add r1.w, r3.z, r3.y
                mad r2.w, v5.z, v5.x, -r3.z
                add r1.x, r2.w, r2.w
                add r4.z, r1.w, r1.w
                mul r3.yz, r4, v4
                mov r3.w, v3.x
                mul r5.xyz, r2, v4
                mov r3.x, r5.x
                dp4 r3.x, v0, r3
                mov r0.y, r5.y
                mov r0.w, v3.y
                dp4 r3.y, v0, r0
                mul r5.xy, r1, v4
                mov r5.w, v3.z
                dp4 r3.z, v0, r5
                add r0.xyz, r3, -c10
                dp3 r0.x, r0, c7
                mad r0.xyz, r0.x, c9, r3
                mov r0.w, v0.w
                dp4 o6.z, r0, c2
                dp4 r3.x, r0, c0
                dp4 r3.y, r0, c1
                dp4 r0.x, r0, c3
                mad o6.xy, c8, r0.x, r3
                mul r0.y, r0.x, c6.x
                mov o6.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c11.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r3.x, c4.x
                mad r0.x, r0.x, r3.x, c5.x
                add o1.x, -r0.x, c11.y
                mov r1.z, r2.z
                mov r4.x, r2.x
                dp3 r0.x, v1, r4
                dp3 r0.z, v1, r1
                slt r0.yw, c11.w, r0.xzzx
                slt r1, -v6_abs, v6_abs
                mul r0.yw, r0, r1.xxzy
                mad r0.y, r0.y, c12.x, c12.y
                lrp r1.x, r0.w, -c11.y, r0.y
                slt r0.yw, r0.xzzx, -c11.w
                mov o0.xz, r0
                mul r0.xy, r0.ywzw, r1.zwzw
                lrp r2.x, r0.x, -c11.y, r1.x
                add r0.x, -r2.x, -c11.y
                mad o3.x, r0.y, r0.x, r2.x
                slt o5.x, -v4_abs.w, v4_abs.w
                mov o2.xy, v2
                mov o4.x, v3.w
            
            // approximately 68 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   BaseAmbient  c1       1
            //
            
                preshader
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D CubemapSampler;
            //   float3 DiffuseLight;
            //   float3 Fog_Color;
            //
            //
            // Registers:
            //
            //   Name           Reg   Size
            //   -------------- ----- ----
            //   DiffuseLight   c2       1
            //   Fog_Color      c3       1
            //   BaseAmbient    c4       1
            //   CubemapSampler s0       1
            //
            
                ps_3_0
                def c5, -0.00390625, 1, 0.00999999978, 0.600000024
                def c6, 0.300000012, 0, 0, 0
                dcl_texcoord v0.xyz
                dcl_texcoord1 v1.x
                dcl_texcoord2 v2.xy
                dcl_texcoord3 v3.x
                dcl_texcoord4 v4.x
                dcl_texcoord5 v5.x
                dcl_2d s0
                mov r0, v3.x
                texkill r0
                add r0, c5.x, v4.x
                texkill r0
                mul r0.xyz, c0, v0_abs.x
                mul r1.xyz, c0, v0_abs.z
                dp3_sat r0.w, v0, c5.y
                texld r2, v2, s0
                add_sat r3.xyz, r2.w, c4
                mad r3.xyz, r0.w, c0, r3
                mad r1.xyz, r1, c5.w, r3
                add r4.xy, c5.z, v0.zxzw
                cmp r1.xyz, r4.x, r3, r1
                mad r0.xyz, r0, c6.x, r1
                cmp_sat r0.xyz, r4.y, r1, r0
                mul r1.xyz, r2.w, c1
                mad r0.xyz, r0, c2, r1
                mul r0.xyz, r0, r2
                cmp r0.xyz, -v5.x, r2, r0
                add r1.xyz, -r0, c3
                mad oC0.xyz, v1.x, r1, r0
                mov oC0.w, v4.x
            
            // approximately 22 instruction slots used (1 texture, 21 arithmetic)
            };
    }
}

