// HwInstancedBlackHoleEffect
// 801A7029BD7964B684FAD7CFDBE914E067329F215DC8D9F65BC39E4E0A311239

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Body
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c4       1
            //
            
                vs_3_0
                def c5, 0, 1, 0, 0
                dcl_position v0
                dcl_texcoord2 v1
                dcl_texcoord3 v2
                dcl_texcoord o0.xy
                dcl_texcoord1 o1.xyz
                dcl_position o2
                mad r0, v1.x, c5.xxxy, c5.yxxx
                dp4 r0.x, v0, r0
                mad r1, v1.xxxy, c5.xxxy, c5.xyxx
                dp4 r0.y, v0, r1
                mad r1, v1.xxxz, c5.xxxy, c5.xxyx
                dp4 r0.z, v0, r1
                mov r0.w, v0.w
                dp4 o2.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad o2.xy, c4, r0.x, r1
                mov o2.w, r0.x
                mov o0.xy, c5.x
                mov o1.xyz, v2
            
            // approximately 15 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float IsTextureEnabled;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   IsTextureEnabled c0       1
            //
            
                preshader
                neg r0.x, c0.x
                max r1.x, r0.x, c0.x
                neg r0.x, r1.x
                cmp ob0.x, r0.x, (0), (1)
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_3_0
                def c0, -0.00390625, 1, 0, 0
                dcl_texcoord v0.xy
                dcl_texcoord1 v1.xyz
                dcl_2d s0
                if b0
                  texld r0, v0, s0
                  mul oC0.xyz, r0, v1
                  mov oC0.w, r0.w
                  add r0, r0.w, c0.x
                  texkill r0
                else
                  mad oC0, v1.xyzx, c0.yyyz, c0.zzzy
                endif
            
            // approximately 11 instruction slots used (1 texture, 10 arithmetic)
            };
    }
    pass Fringe
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c4       1
            //
            
                vs_3_0
                def c5, 1, 0, 0, 0
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord2 v2
                dcl_texcoord3 v3
                dcl_texcoord4 v4
                dcl_texcoord5 v5
                dcl_texcoord o0.xy
                dcl_texcoord1 o1.xyz
                dcl_position o2
                mad r0.xyz, v1.xyxw, c5.xxyw, c5.yyxw
                mul r1.xy, c5, v5.x
                mov r1.z, v4.x
                dp3 o0.x, r0, r1
                mov r0.xy, v1
                mov r0.z, v4.y
                mad r1.xyz, v5.xyxw, c5.yxyw, c5.yyxw
                dp3 o0.y, r0, r1
                mad r0, v2.x, c5.yyyx, c5.xyyy
                dp4 r0.x, v0, r0
                mad r1, v2.xxxy, c5.yyyx, c5.yxyy
                dp4 r0.y, v0, r1
                mad r1, v2.xxxz, c5.yyyx, c5.yyxy
                dp4 r0.z, v0, r1
                mov r0.w, v0.w
                dp4 o2.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad o2.xy, c4, r0.x, r1
                mov o2.w, r0.x
                mov o1.xyz, v3
            
            // approximately 22 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float IsTextureEnabled;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   IsTextureEnabled c0       1
            //
            
                preshader
                neg r0.x, c0.x
                max r1.x, r0.x, c0.x
                neg r0.x, r1.x
                cmp ob0.x, r0.x, (0), (1)
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_3_0
                def c0, -0.00390625, 1, 0, 0
                dcl_texcoord v0.xy
                dcl_texcoord1 v1.xyz
                dcl_2d s0
                if b0
                  texld r0, v0, s0
                  mul oC0.xyz, r0, v1
                  mov oC0.w, r0.w
                  add r0, r0.w, c0.x
                  texkill r0
                else
                  mad oC0, v1.xyzx, c0.yyyz, c0.zzzy
                endif
            
            // approximately 11 instruction slots used (1 texture, 10 arithmetic)
            };
    }
}

