// HwInstancedMapEffect
// 8A75D00EA18901A9F3098040A5726370E74624EDA527E6526E344A075E8D1FF6

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Billboard;
            //   float4x4 CameraRotation;
            //
            //
            // Registers:
            //
            //   Name           Reg   Size
            //   -------------- ----- ----
            //   CameraRotation c0       4
            //   Billboard      c4       1
            //
            
                preshader
                add r0, c0, (-1, -0, -0, -0)
                neg r1.x, c4.x
                max r2.x, r1.x, c4.x
                neg r1.x, r2.x
                lt r3.x, r1.x, r2.x
                mul r1, r3.x, r0
                add r0, r1, (1, 0, 0, 0)
                mov c0.x, r0.x
                add r1.x, c1.x, (-0)
                add r1.y, c1.y, (-1)
                add r1.z, c1.z, (-0)
                add r1.w, c1.w, (-0)
                mul r2, r3.x, r1
                add r1.x, r2.x, (0)
                add r1.y, r2.y, (1)
                add r1.z, r2.z, (0)
                add r1.w, r2.w, (0)
                mov c1.x, r1.x
                add r2.x, c2.x, (-0)
                add r2.y, c2.y, (-0)
                add r2.z, c2.z, (-1)
                add r2.w, c2.w, (-0)
                mul r4, r3.x, r2
                add r2.x, r4.x, (0)
                add r2.y, r4.y, (0)
                add r2.z, r4.z, (1)
                add r2.w, r4.w, (0)
                mov c2.x, r2.x
                add r4.x, c3.x, (-0)
                add r4.y, c3.y, (-0)
                add r4.z, c3.z, (-0)
                add r4.w, c3.w, (-1)
                mul r5, r3.x, r4
                mov c13.x, r3.x
                add r3.x, r5.x, (0)
                add r3.y, r5.y, (0)
                add r3.z, r5.z, (0)
                add r3.w, r5.w, (1)
                mov c3.x, r3.x
                mov c4.x, r0.y
                mov c5.x, r1.y
                mov c6.x, r2.y
                mov c7.x, r3.y
                mov c8.x, r0.z
                mov c12.x, r0.w
                mov c9.x, r1.z
                mov c12.y, r1.w
                mov c10.x, r2.z
                mov c12.z, r2.w
                mov c11.x, r3.z
                mov c12.w, r3.w
            
            // approximately 51 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c14      4
            //   TexelOffset                  c18      1
            //
            
                vs_3_0
                def c19, 0, 1, 0, 0
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord2 v2
                dcl_texcoord3 v3
                dcl_texcoord4 v4
                dcl_texcoord5 v5
                dcl_texcoord o0
                dcl_texcoord1 o1.xy
                dcl_position o2
                mov r0.w, c12.w
                mul r1.w, c3.x, v4.x
                mov r0.x, r1.w
                mul r2.w, c7.x, v4.y
                mov r0.y, r2.w
                mul r0.z, c11.x, v4.z
                dp4 r3.w, v0, r0
                mad r4, v2.x, c19.xxxy, c19.yxxx
                dp4 r5.w, c12, r4
                mul r1.x, c0.x, v4.x
                mul r1.y, c1.x, v4.x
                mul r1.z, c2.x, v4.x
                dp4 r5.x, r1, r4.xzzw
                mul r2.x, c4.x, v4.y
                mul r2.y, c5.x, v4.y
                mul r2.z, c6.x, v4.y
                dp4 r5.y, r2, r4.xzzw
                mul r0.x, c8.x, v4.z
                mul r0.y, c9.x, v4.z
                mul r0.w, c10.x, v4.z
                dp4 r5.z, r0.xywz, r4.xzzw
                dp4 r3.x, v0, r5
                mad r4, v2.xxxy, c19.xxxy, c19.xyxx
                dp4 r5.x, r1.yxzw, r4.yzzw
                dp4 r5.y, r2.yxzw, r4.yzzw
                dp4 r5.z, r0.yxwz, r4.yzzw
                dp4 r5.w, c12, r4
                dp4 r3.y, v0, r5
                mad r4, v2.xxxz, c19.xxxy, c19.xxyx
                dp4 r1.x, r1, r4
                dp4 r1.y, r2, r4
                dp4 r1.z, r0.xywz, r4
                dp4 r1.w, c12, r4
                dp4 r3.z, v0, r1
                dp4 o2.z, r3, c16
                dp4 r0.x, r3, c14
                dp4 r0.y, r3, c15
                dp4 r0.z, r3, c17
                mad o2.xy, c18, r0.z, r0
                mov o2.w, r0.z
                add r0.xyz, c19.y, -v3
                mad o0.xyz, c13.x, r0, v3
                mov r0, v5
                mad o1.xy, v1, r0.zwzw, r0
                mov o0.w, v3.w
            
            // approximately 45 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Billboard;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Billboard    c0       1
            //
            
                preshader
                neg r0.x, c0.x
                max c0.x, r0.x, c0.x
            
            // approximately 2 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_3_0
                def c1, -0.00999999978, 1, 0, 0
                dcl_texcoord v0
                dcl_texcoord1 v1.xy
                dcl_2d s0
                add r0, c1.x, v0.w
                texkill r0
                texld r0, v1, s0
                mov r1.y, c1.y
                cmp r0, -c0.x, r1.y, r0
                mul oC0, r0, v0
            
            // approximately 6 instruction slots used (1 texture, 5 arithmetic)
            };
    }
}

