// HwInstancedStaticPlaneEffect
// 47AAF690F11BC1FBF52A8F081A6293BB4CB6E08B73732796335A1815DDACD4D1

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //
            
                preshader
                neg r0.x, c1.x
                max r1.x, r0.x, c1.x
                neg r0.x, r1.x
                lt c6.x, r0.x, r1.x
                neg r0.x, c0.x
                max r1.x, r0.x, c0.x
                neg r0.x, r1.x
                ge c5.x, r0.x, r1.x
                add r0.x, c0.x, (-2)
                neg r1.x, r0.x
                max r2.x, r0.x, r1.x
                neg r0.x, r2.x
                ge c4.x, r0.x, r2.x
            
            // approximately 13 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Fog_Density                  c7       1
            //   Eye                          c8       1
            //   TexelOffset                  c9       1
            //   EyeSign                      c10      1
            //   LevelCenter                  c11      1
            //
            
                vs_3_0
                def c12, 0.5, 0.25, 0.125, 0.0625
                def c13, 2, -1, 1, 1.44269502
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord2 v2
                dcl_texcoord3 v3
                dcl_texcoord4 v4
                dcl_texcoord5 v5
                dcl_texcoord o0.xy
                dcl_texcoord1 o1.xyz
                dcl_texcoord2 o2.x
                dcl_texcoord3 o3
                dcl_texcoord4 o4.x
                dcl_position o5
                slt r0.x, v4.w, -v4.w
                frc r0.y, v4.w
                add r0.z, -r0.y, v4.w
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0, r0.x, c12
                frc r1, r0_abs
                sge r0, r0, -r0
                lrp r2, r0, r1, -r1
                mad r0.x, r2.x, c13.x, c13.y
                sge r0.yzw, r2, c12.x
                add r0.yz, r0.xzww, r0.y
                slt r0.yz, -r0, r0
                sge o4.x, -r0_abs.x, r0_abs.x
                add r0.xw, c13.y, v4.xyzy
                mad r0.xy, r0.yzzw, r0.xwzw, c13.z
                mul o0.xy, r0, v1
                mov r0.w, v2.x
                mul r1.xyz, v3, v3
                add r1.xyz, r1.zxxw, r1.yzyw
                mad r1.xyz, r1, -c13.x, c13.z
                mul r2.xyz, r1, v4
                mov o1.z, r1.z
                mov r0.x, r2.x
                mul r1.xyz, v3.wxww, v3.zzyw
                mad r1.w, v3.x, v3.y, -r1.x
                mul r1.w, r1.w, v4.y
                add r0.y, r1.w, r1.w
                add r1.y, r1.z, r1.y
                add r3.x, r1.y, r1.y
                mul r0.z, r3.x, v4.z
                dp4 r0.x, v0, r0
                mov r4.z, r2.z
                mad r0.w, v3.z, v3.x, -r1.z
                mad r1.x, v3.x, v3.y, r1.x
                mul r1.x, r1.x, v4.x
                add r2.x, r1.x, r1.x
                mul r0.w, r0.w, v4.x
                add r4.x, r0.w, r0.w
                mul r0.w, v3.w, v3.x
                mad r1.x, v3.y, v3.z, r0.w
                mad r0.w, v3.y, v3.z, -r0.w
                add r3.y, r0.w, r0.w
                mul r0.w, r1.x, v4.y
                add r4.y, r0.w, r0.w
                mov r4.w, v2.z
                dp4 r0.z, v0, r4
                mul r2.z, r3.y, v4.z
                mov o1.xy, r3
                mov r2.w, v2.y
                dp4 r0.y, v0, r2
                add r1.xyz, r0, -c11
                dp3 r0.w, r1, c8
                mad r0.xyz, r0.w, c10, r0
                mov r0.w, v0.w
                dp4 o5.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad o5.xy, c9, r0.x, r1
                mul r0.y, r0.x, c7.x
                mov o5.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c13.w
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c4.x
                mad r0.x, r0.x, r1.x, c5.x
                add_sat r0.x, -r0.x, c13.z
                mad o2.x, c6.x, -r0.x, r0.x
                mov o3, v5
            
            // approximately 72 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float SewerHax;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   BaseAmbient  c1       1
            //   SewerHax     c2       1
            //
            
                preshader
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
                neg r0.x, c2.x
                max c2.x, r0.x, c2.x
            
            // approximately 6 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D BaseSampler;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c3       1
            //   BaseAmbient  c4       1
            //   BaseSampler  s0       1
            //
            
                ps_3_0
                def c5, 1, 0.00999999978, 0.600000024, 0.300000012
                def c6, -0.00390625, 0.75, 0, 1
                def c7, 0.5, 0, 0, 0
                dcl_texcoord v0.xy
                dcl_texcoord1 v1.xyz
                dcl_texcoord2 v2.x
                dcl_texcoord3 v3.w
                dcl_texcoord4 v4.x
                dcl_2d s0
                texld r0, v0, s0
                mad r1, v3.w, r0.w, c6.x
                texkill r1
                add_sat r1.xyz, c4, v4.x
                dp3_sat r0.y, v1, c5.x
                mad r1.xyz, r0.y, c0, r1
                mul r2.xyz, c0, v1_abs.z
                mad r2.xyz, r2, c5.z, r1
                add r0.yz, c5.y, v1.xzxw
                cmp r1.xyz, r0.y, r1, r2
                mul r2.xyz, c0, v1_abs.x
                mad r2.xyz, r2, c5.w, r1
                cmp_sat r1.xyz, r0.z, r1, r2
                mul r2.xyz, c1, v4.x
                mad r1.xyz, r1, c3, r2
                lrp r2.xyz, v2.x, c5.x, r1
                add r0.x, -r0.x, c6.y
                mul r0.y, r0.w, v3.w
                mov oC0.w, r0.y
                cmp r0.x, r0.x, c6.z, c6.w
                cmp r0.xyz, -c2.x, r2, r0.x
                mul oC0.xyz, r0, c7.x
            
            // approximately 22 instruction slots used (1 texture, 21 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //
            
                preshader
                neg r0.x, c1.x
                max r1.x, r0.x, c1.x
                neg r0.x, r1.x
                lt c6.x, r0.x, r1.x
                neg r0.x, c0.x
                max r1.x, r0.x, c0.x
                neg r0.x, r1.x
                ge c5.x, r0.x, r1.x
                add r0.x, c0.x, (-2)
                neg r1.x, r0.x
                max r2.x, r0.x, r1.x
                neg r0.x, r2.x
                ge c4.x, r0.x, r2.x
            
            // approximately 13 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Fog_Density                  c7       1
            //   Eye                          c8       1
            //   TexelOffset                  c9       1
            //   EyeSign                      c10      1
            //   LevelCenter                  c11      1
            //
            
                vs_3_0
                def c12, 0.5, 0.25, 0.125, 0.0625
                def c13, 2, -1, 1, 1.44269502
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord2 v2
                dcl_texcoord3 v3
                dcl_texcoord4 v4
                dcl_texcoord5 v5
                dcl_texcoord o0.xy
                dcl_texcoord1 o1.xyz
                dcl_texcoord2 o2.x
                dcl_texcoord3 o3
                dcl_texcoord4 o4.x
                dcl_position o5
                slt r0.x, v4.w, -v4.w
                frc r0.y, v4.w
                add r0.z, -r0.y, v4.w
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0, r0.x, c12
                frc r1, r0_abs
                sge r0, r0, -r0
                lrp r2, r0, r1, -r1
                mad r0.x, r2.x, c13.x, c13.y
                sge r0.yzw, r2, c12.x
                add r0.yz, r0.xzww, r0.y
                slt r0.yz, -r0, r0
                sge o4.x, -r0_abs.x, r0_abs.x
                add r0.xw, c13.y, v4.xyzy
                mad r0.xy, r0.yzzw, r0.xwzw, c13.z
                mul o0.xy, r0, v1
                mov r0.w, v2.x
                mul r1.xyz, v3, v3
                add r1.xyz, r1.zxxw, r1.yzyw
                mad r1.xyz, r1, -c13.x, c13.z
                mul r2.xyz, r1, v4
                mov o1.z, r1.z
                mov r0.x, r2.x
                mul r1.xyz, v3.wxww, v3.zzyw
                mad r1.w, v3.x, v3.y, -r1.x
                mul r1.w, r1.w, v4.y
                add r0.y, r1.w, r1.w
                add r1.y, r1.z, r1.y
                add r3.x, r1.y, r1.y
                mul r0.z, r3.x, v4.z
                dp4 r0.x, v0, r0
                mov r4.z, r2.z
                mad r0.w, v3.z, v3.x, -r1.z
                mad r1.x, v3.x, v3.y, r1.x
                mul r1.x, r1.x, v4.x
                add r2.x, r1.x, r1.x
                mul r0.w, r0.w, v4.x
                add r4.x, r0.w, r0.w
                mul r0.w, v3.w, v3.x
                mad r1.x, v3.y, v3.z, r0.w
                mad r0.w, v3.y, v3.z, -r0.w
                add r3.y, r0.w, r0.w
                mul r0.w, r1.x, v4.y
                add r4.y, r0.w, r0.w
                mov r4.w, v2.z
                dp4 r0.z, v0, r4
                mul r2.z, r3.y, v4.z
                mov o1.xy, r3
                mov r2.w, v2.y
                dp4 r0.y, v0, r2
                add r1.xyz, r0, -c11
                dp3 r0.w, r1, c8
                mad r0.xyz, r0.w, c10, r0
                mov r0.w, v0.w
                dp4 o5.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad o5.xy, c9, r0.x, r1
                mul r0.y, r0.x, c7.x
                mov o5.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c13.w
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c4.x
                mad r0.x, r0.x, r1.x, c5.x
                add_sat r0.x, -r0.x, c13.z
                mad o2.x, c6.x, -r0.x, r0.x
                mov o3, v5
            
            // approximately 72 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float3 Fog_Color;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Color    c0       1
            //   BaseSampler  s0       1
            //
            
                ps_3_0
                def c1, -0.00390625, 0, 0, 0
                dcl_texcoord v0.xy
                dcl_texcoord2 v1.x
                dcl_texcoord3 v2
                dcl_2d s0
                texld r0, v0, s0
                mad r1, v2.w, r0.w, c1.x
                texkill r1
                mad r1.xyz, v2, -r0, c0
                mul r0, r0.wxyz, v2.wxyz
                mad oC0.xyz, v1.x, r1, r0.yzww
                mov oC0.w, r0.x
            
            // approximately 7 instruction slots used (1 texture, 6 arithmetic)
            };
    }
}

