// HwInstancedDotEffect
// 5B9364A58BDEB204C85526A90BD1BDA009F941F22A33C9DD13F2AA80C0054EE8

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float EightShapeStep;
            //   float Material_Opacity;
            //   float Theta;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c0       1
            //   Theta            c1       1
            //   EightShapeStep   c2       1
            //
            
                preshader
                mul c4.x, c1.x, (0.100000001)
                mul c5.x, c2.x, (1.33333337)
                mov c6.x, c0.x
            
            // approximately 3 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float DistanceFactor;
            //   float EightShapeStep;
            //   float ImmobilityFactor;
            //   float3 Material_Diffuse;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //   float Theta;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c7       1
            //   Material_Diffuse             c8       1
            //   Theta                        c9       1
            //   EightShapeStep               c10      1
            //   DistanceFactor               c11      1
            //   ImmobilityFactor             c12      1
            //
            
                vs_3_0
                def c13, 6, 1, 12, -6
                def c14, -1, -2, -3, -4
                def c15, -0.408248305, 0.816496611, 0.408248305, 0.349999994
                def c16, 0.333333343, 0.5, 0.200000003, 1
                def c17, 0.159154937, 0.5, 6.28318548, -3.14159274
                def c18, 0.707106769, 0, 0.577350259, -0.577350259
                def c19, 1, 0, -1, 0.333333343
                dcl_position v0
                dcl_color v1
                dcl_texcoord2 v2
                dcl_texcoord o0
                dcl_position o1
                add r0.x, c9.x, v2.w
                mad r0.x, r0.x, c17.x, c17.y
                frc r0.x, r0.x
                mad r0.x, r0.x, c17.z, c17.w
                sincos r1.xy, r0.x
                mul r0, r1.yxxx, c19.xyyx
                mul r1, r1.xxxy, c19.xyyz
                dp4 r1.x, v0, r1
                dp4 r0.x, v0, r0
                add r0.x, r0.x, c13.y
                mad r0.x, r0.x, c16.x, c16.y
                mul r0.x, r0.x, c19.w
                mov r1.yz, v0
                mul r0.xyz, r0.x, r1
                add r0.w, c5.x, v2.w
                mad r0.w, r0.w, c17.x, c17.y
                frc r0.w, r0.w
                mad r0.w, r0.w, c17.z, c17.w
                sincos r1.y, r0.w
                mad r0.w, r1.y, c16.z, c16.w
                mov r1.y, c13.y
                mad r0.w, r0.w, c11.x, -r1.y
                mad r0.w, c12.x, r0.w, r1.y
                mul r0.xyz, r0.w, r0
                dp3 r1.x, r0.xzyw, c18.xxyw
                dp3 r1.y, r0, c18.zzww
                dp3 r1.z, r0, c15
                add r0.xyz, r1, v2
                add r0.w, c10.x, v2.w
                mad r0.w, r0.w, c17.x, c17.y
                frc r0.w, r0.w
                mad r0.w, r0.w, c17.z, c17.w
                sincos r1.xy, r0.w
                mul r1, r1.yyxx, c19.yxxy
                add r1.xyz, r1.zwww, r1.xyxw
                mad r0.xyz, r1, c12.x, r0
                mov r0.w, c13.y
                dp4 o1.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad o1.xy, c7, r0.x, r1
                mov o1.w, r0.x
                add r0.x, c4.x, v2.w
                add r0.x, r0.x, v1.x
                mul r0.y, r0.x, c13.x
                frc r0.z, r0.y
                add r0.y, -r0.z, r0.y
                mul r0.z, r0.y, c13.x
                sge r0.z, r0.z, -r0.z
                mad r0.z, r0.z, c13.z, c13.w
                rcp r0.w, r0.z
                mul r0.w, r0.w, r0.y
                mad r0.x, r0.x, c13.x, -r0.y
                frc r0.y, r0.w
                mul r0.y, r0.y, r0.z
                frc r0.z, r0.y
                add r0.w, r0.y, -r0.z
                slt r0.y, r0.y, -r0.y
                slt r0.z, -r0.z, r0.z
                mad r0.y, r0.y, r0.z, r0.w
                add r1, r0.y, c14
                sge r0.y, -r0_abs.y, r0_abs.y
                sge r1, -r1_abs, r1_abs
                add r0.z, -r0.x, c13.y
                mad r0.x, r0.x, -v1.y, c13.y
                mul r2.x, r0.x, v1.z
                mad r0.x, r0.z, -v1.y, c13.y
                mul r0.x, r0.x, v1.z
                mov r0.z, v1.z
                mov r2.y, v1.z
                lrp r3.xz, r1.w, r0, r2.yyxw
                mov r2.w, r0.x
                add r0.x, c13.y, -v1.y
                mul r3.y, r0.x, v1.z
                mov r2.z, r3.y
                lrp r0.xzw, r1.z, r2.zyxy, r3.xyyz
                lrp r3.xyz, r1.y, r2.zyww, r0.xzww
                lrp r0.xzw, r1.x, r2.xyyz, r3.xyyz
                lrp r1.xyz, r0.y, r2.ywzw, r0.xzww
                mul r0.xyz, r1, c8
                mul o0.xyz, r0, c15.w
                mov o0.w, c6.x
            
            // approximately 104 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_3_0
                dcl_texcoord v0
                mov oC0, v0
            
            // approximately 1 instruction slot used
            };
    }
}

