// HwInstancedAnimatedPlaneEffect
// 24D2B0C9DCCD387DABD403B291967AFCD8CED2B7888F1B1C371C4DBFB9C3B547

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float2 FrameScale;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //   FrameScale   c2       1
            //
            
                preshader
                neg r0.x, c1.x
                max r1.x, r0.x, c1.x
                neg r0.x, r1.x
                lt c6.x, r0.x, r1.x
                neg r0.x, c0.x
                max r1.x, r0.x, c0.x
                neg r0.x, r1.x
                ge c5.x, r0.x, r1.x
                add r0.x, c0.x, (-2)
                neg r1.x, r0.x
                max r2.x, r0.x, r1.x
                neg r0.x, r2.x
                ge c4.x, r0.x, r2.x
                mov c7.x, c2.y
            
            // approximately 14 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float2 FrameScale;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Fog_Density                  c8       1
            //   Eye                          c9       1
            //   TexelOffset                  c10      1
            //   EyeSign                      c11      1
            //   LevelCenter                  c12      1
            //   FrameScale                   c13      1
            //
            
                vs_3_0
                def c14, 0.5, 0.25, 0.125, 0.0625
                def c15, 2, -1, 1, 1.44269502
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord2 v3
                dcl_texcoord3 v4
                dcl_texcoord4 v5
                dcl_texcoord5 v6
                dcl_texcoord o0.xy
                dcl_texcoord1 o1.xyz
                dcl_texcoord2 o2.x
                dcl_texcoord3 o3
                dcl_texcoord4 o4.xy
                dcl_texcoord5 o5.xy
                dcl_position o6
                slt r0.x, v5.w, -v5.w
                frc r0.y, v5.w
                add r0.z, -r0.y, v5.w
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0, r0.x, c14
                frc r1, r0_abs
                sge r0, r0, -r0
                lrp r2, r0, r1, -r1
                sge r0.yzw, r2, c14.x
                mad r1.x, r2.x, c15.x, c15.y
                sge r0.x, -r1_abs.x, r1_abs.x
                mov o4.xy, r0.xwzw
                add r0.xy, r0.zwzw, r0.y
                slt r0.xy, -r0, r0
                add r0.zw, c15.y, v5.xyxy
                mad r0.xy, r0, r0.zwzw, c15.z
                mul r0.xy, r0, v2
                mov r1.xw, v3.wyzx
                mov r1.y, v5.z
                mad o0.xy, r0, c13, r1
                mul r0.xyz, v4, v4
                add r0.xyz, r0.zxxw, r0.yzyw
                mad r0.xyz, r0, -c15.x, c15.z
                mov r1.x, r0.x
                mul r2.xyz, v4.wxww, v4.zzyw
                mad r0.w, v4.x, v4.y, -r2.x
                add r1.y, r0.w, r0.w
                add r0.w, r2.z, r2.y
                add r1.z, r0.w, r0.w
                dp3 o1.x, v1, r1
                mul r1.y, r1.y, v5.y
                mov r3.y, r0.y
                mad r0.w, v4.x, v4.y, r2.x
                mad r2.x, v4.z, v4.x, -r2.z
                add r2.x, r2.x, r2.x
                add r3.x, r0.w, r0.w
                mul r0.w, v4.w, v4.x
                mad r4.x, v4.y, v4.z, -r0.w
                mad r0.w, v4.y, v4.z, r0.w
                add r2.y, r0.w, r0.w
                add r3.z, r4.x, r4.x
                dp3 o1.y, v1, r3
                mul r3.x, r3.x, v5.x
                mov r2.z, r0.z
                mul r0.xy, r0, v5
                dp3 o1.z, v1, r2
                mul r2.xy, r2, v5
                mov r1.x, r0.x
                mov r3.y, r0.y
                dp4 r0.x, v0, r1
                mov r3.w, v3.y
                dp4 r0.y, v0, r3
                mov r2.w, v3.z
                dp4 r0.z, v0, r2
                add r1.xyz, r0, -c12
                dp3 r0.w, r1, c9
                mad r0.xyz, r0.w, c11, r0
                mov r0.w, v0.w
                dp4 o6.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad o6.xy, c10, r0.x, r1
                mul r0.y, r0.x, c8.x
                mov o6.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c15.w
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c4.x
                mad r0.x, r0.x, r1.x, c5.x
                add_sat r0.x, -r0.x, c15.z
                mad o2.x, c6.x, -r0.x, r0.x
                mov o3, v6
                mov o5.x, v5.z
                mov o5.y, c7.x
            
            // approximately 78 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float IgnoreShading;
            //   float SewerHax;
            //
            //
            // Registers:
            //
            //   Name          Reg   Size
            //   ------------- ----- ----
            //   DiffuseLight  c0       1
            //   BaseAmbient   c1       1
            //   IgnoreShading c2       1
            //   SewerHax      c3       1
            //
            
                preshader
                neg r0.x, c2.x
                max c0.x, r0.x, c2.x
                neg r0.xyz, c1.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c2.xyz, (1, 1, 1), r0.xyz
                neg r0.x, c3.x
                max c3.x, r0.x, c3.x
            
            // approximately 8 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AnimatedSampler;
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   DiffuseLight    c4       1
            //   BaseAmbient     c5       1
            //   AnimatedSampler s0       1
            //
            
                ps_3_0
                def c6, 1, 0.00999999978, 0.600000024, 0.300000012
                def c7, -0.00390625, 0.75, 0, 1
                def c8, 0.5, 0, 0, 0
                dcl_texcoord v0.xy
                dcl_texcoord1 v1.xyz
                dcl_texcoord2 v2.x
                dcl_texcoord3 v3.w
                dcl_texcoord4 v4.xy
                dcl_texcoord5 v5.xy
                dcl_2d s0
                mov r0.x, v5.x
                add r0.x, -r0.x, v0.y
                rcp r0.y, v5.y
                mul r0.x, r0.y, r0.x
                frc r0.x, r0.x
                mad r0.x, r0.x, v5.y, v5.x
                mov r1.xy, v4
                cmp r0.y, -r1.y, v0.y, r0.x
                mov r0.x, v0.x
                texld r0, r0, s0
                mad r2, v3.w, r0.w, c7.x
                texkill r2
                mov r2.x, c6.x
                cmp r0.y, -c0.x, r1.x, r2.x
                add_sat r1.xyz, r0.y, c5
                dp3_sat r0.y, v1, c6.x
                mad r1.xyz, r0.y, c1, r1
                mul r2.xyz, c1, v1_abs.z
                mad r2.xyz, r2, c6.z, r1
                add r0.yz, c6.y, v1.xzxw
                cmp r1.xyz, r0.y, r1, r2
                mul r2.xyz, c1, v1_abs.x
                mad r2.xyz, r2, c6.w, r1
                cmp_sat r1.xyz, r0.z, r1, r2
                mul r2.xyz, c2, v4.x
                mad r1.xyz, r1, c4, r2
                lrp r2.xyz, v2.x, c6.x, r1
                add r0.x, -r0.x, c7.y
                mul r0.y, r0.w, v3.w
                mov oC0.w, r0.y
                cmp r0.x, r0.x, c7.z, c7.w
                cmp r0.xyz, -c3.x, r2, r0.x
                mul oC0.xyz, r0, c8.x
            
            // approximately 33 instruction slots used (1 texture, 32 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float2 FrameScale;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //   FrameScale   c2       1
            //
            
                preshader
                neg r0.x, c1.x
                max r1.x, r0.x, c1.x
                neg r0.x, r1.x
                lt c6.x, r0.x, r1.x
                neg r0.x, c0.x
                max r1.x, r0.x, c0.x
                neg r0.x, r1.x
                ge c5.x, r0.x, r1.x
                add r0.x, c0.x, (-2)
                neg r1.x, r0.x
                max r2.x, r0.x, r1.x
                neg r0.x, r2.x
                ge c4.x, r0.x, r2.x
                mov c7.x, c2.y
            
            // approximately 14 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float2 FrameScale;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Fog_Density                  c8       1
            //   Eye                          c9       1
            //   TexelOffset                  c10      1
            //   EyeSign                      c11      1
            //   LevelCenter                  c12      1
            //   FrameScale                   c13      1
            //
            
                vs_3_0
                def c14, 0.5, 0.25, 0.125, 0.0625
                def c15, 2, -1, 1, 1.44269502
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord2 v3
                dcl_texcoord3 v4
                dcl_texcoord4 v5
                dcl_texcoord5 v6
                dcl_texcoord o0.xy
                dcl_texcoord1 o1.xyz
                dcl_texcoord2 o2.x
                dcl_texcoord3 o3
                dcl_texcoord4 o4.xy
                dcl_texcoord5 o5.xy
                dcl_position o6
                slt r0.x, v5.w, -v5.w
                frc r0.y, v5.w
                add r0.z, -r0.y, v5.w
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0, r0.x, c14
                frc r1, r0_abs
                sge r0, r0, -r0
                lrp r2, r0, r1, -r1
                sge r0.yzw, r2, c14.x
                mad r1.x, r2.x, c15.x, c15.y
                sge r0.x, -r1_abs.x, r1_abs.x
                mov o4.xy, r0.xwzw
                add r0.xy, r0.zwzw, r0.y
                slt r0.xy, -r0, r0
                add r0.zw, c15.y, v5.xyxy
                mad r0.xy, r0, r0.zwzw, c15.z
                mul r0.xy, r0, v2
                mov r1.xw, v3.wyzx
                mov r1.y, v5.z
                mad o0.xy, r0, c13, r1
                mul r0.xyz, v4, v4
                add r0.xyz, r0.zxxw, r0.yzyw
                mad r0.xyz, r0, -c15.x, c15.z
                mov r1.x, r0.x
                mul r2.xyz, v4.wxww, v4.zzyw
                mad r0.w, v4.x, v4.y, -r2.x
                add r1.y, r0.w, r0.w
                add r0.w, r2.z, r2.y
                add r1.z, r0.w, r0.w
                dp3 o1.x, v1, r1
                mul r1.y, r1.y, v5.y
                mov r3.y, r0.y
                mad r0.w, v4.x, v4.y, r2.x
                mad r2.x, v4.z, v4.x, -r2.z
                add r2.x, r2.x, r2.x
                add r3.x, r0.w, r0.w
                mul r0.w, v4.w, v4.x
                mad r4.x, v4.y, v4.z, -r0.w
                mad r0.w, v4.y, v4.z, r0.w
                add r2.y, r0.w, r0.w
                add r3.z, r4.x, r4.x
                dp3 o1.y, v1, r3
                mul r3.x, r3.x, v5.x
                mov r2.z, r0.z
                mul r0.xy, r0, v5
                dp3 o1.z, v1, r2
                mul r2.xy, r2, v5
                mov r1.x, r0.x
                mov r3.y, r0.y
                dp4 r0.x, v0, r1
                mov r3.w, v3.y
                dp4 r0.y, v0, r3
                mov r2.w, v3.z
                dp4 r0.z, v0, r2
                add r1.xyz, r0, -c12
                dp3 r0.w, r1, c9
                mad r0.xyz, r0.w, c11, r0
                mov r0.w, v0.w
                dp4 o6.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad o6.xy, c10, r0.x, r1
                mul r0.y, r0.x, c8.x
                mov o6.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c15.w
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c4.x
                mad r0.x, r0.x, r1.x, c5.x
                add_sat r0.x, -r0.x, c15.z
                mad o2.x, c6.x, -r0.x, r0.x
                mov o3, v6
                mov o5.x, v5.z
                mov o5.y, c7.x
            
            // approximately 78 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AnimatedSampler;
            //   float3 Fog_Color;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   Fog_Color       c0       1
            //   AnimatedSampler s0       1
            //
            
                ps_3_0
                def c1, -0.00390625, 0, 0, 0
                dcl_texcoord v0.xy
                dcl_texcoord2 v1.x
                dcl_texcoord3 v2
                dcl_texcoord5 v3.xy
                dcl_2d s0
                mov r0.x, v3.x
                add r0.x, -r0.x, v0.y
                rcp r0.y, v3.y
                mul r0.x, r0.y, r0.x
                frc r0.x, r0.x
                mad r0.y, r0.x, v3.y, v3.x
                mov r0.x, v0.x
                texld r0, r0, s0
                mad r1, v2.w, r0.w, c1.x
                texkill r1
                mad r1.xyz, v2, -r0, c0
                mul r0, r0.wxyz, v2.wxyz
                mad oC0.xyz, v1.x, r1, r0.yzww
                mov oC0.w, r0.x
            
            // approximately 14 instruction slots used (1 texture, 13 arithmetic)
            };
    }
}

