// HwPlaneParticleEffect
// CC2E9D0C9242C774781649C5E33D80860918C8385A3DDC5AB4661C18E040BDBE

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Eye                          c4       1
            //   TexelOffset                  c5       1
            //   EyeSign                      c6       1
            //   LevelCenter                  c7       1
            //
            
                vs_3_0
                def c8, 0.159154937, 0.5, 6.28318548, -3.14159274
                def c9, 0, 1, 0, 0
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord2 v2
                dcl_texcoord3 v3
                dcl_texcoord4 v4
                dcl_texcoord o0.xy
                dcl_texcoord1 o1
                dcl_position o2
                mad r0.x, v2.w, c8.x, c8.y
                frc r0.x, r0.x
                mad r0.x, r0.x, c8.z, c8.w
                sincos r1.xy, r0.x
                mul r0.x, -r1.y, v3.x
                mul r1.xyz, r1.xyxw, v3.xzzw
                mov r0.y, r1.z
                mov r0.z, v2.z
                dp3 r0.z, v0.xzww, r0
                mov r1.w, v2.x
                dp3 r0.x, v0.xzww, r1.xyww
                mul r1.xy, c9, v3.y
                mov r1.w, v2.y
                dp4 r0.y, v0.xzyw, r1.xxyw
                add r1.xyz, r0, -c7
                dp3 r0.w, r1, c4
                mad r0.xyz, r0.w, c6, r0
                mov r0.w, v0.w
                dp4 o2.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad o2.xy, c5, r0.x, r1
                mov o2.w, r0.x
                mov o0.xy, v1
                mov o1, v4
            
            // approximately 33 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Additive;
            //   float3 DiffuseLight;
            //   float Fullbright;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   Fullbright   c1       1
            //   Additive     c2       1
            //
            
                preshader
                neg r0.x, c2.x
                max c0.x, r0.x, c2.x
                neg r0.xyz, c0.xyz
                add r1.xyz, (1, 1, 1), r0.xyz
                mul r0.xyz, c1.x, r1.xyz
                add c1.xyz, r0.xyz, c0.xyz
            
            // approximately 6 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float Fullbright;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fullbright   c2       1
            //   BaseSampler  s0       1
            //
            
                ps_3_0
                def c3, 1, 0.5, 0, 0
                dcl_texcoord v0.xy
                dcl_texcoord1 v1
                dcl_2d s0
                texld r0, v0, s0
                mul r0, r0, v1
                mul r0.xyz, r0, c2.x
                mov r1.x, c0.x
                cmp r1.xyz, -r1.x, c1, r0
                mov r0.x, c3.x
                cmp r1.w, -c0.x, r0.w, r0.x
                mul oC0, r1, c3.yyyx
            
            // approximately 8 instruction slots used (1 texture, 7 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Eye                          c4       1
            //   TexelOffset                  c5       1
            //   EyeSign                      c6       1
            //   LevelCenter                  c7       1
            //
            
                vs_3_0
                def c8, 0.159154937, 0.5, 6.28318548, -3.14159274
                def c9, 0, 1, 0, 0
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord2 v2
                dcl_texcoord3 v3
                dcl_texcoord4 v4
                dcl_texcoord o0.xy
                dcl_texcoord1 o1
                dcl_position o2
                mad r0.x, v2.w, c8.x, c8.y
                frc r0.x, r0.x
                mad r0.x, r0.x, c8.z, c8.w
                sincos r1.xy, r0.x
                mul r0.x, -r1.y, v3.x
                mul r1.xyz, r1.xyxw, v3.xzzw
                mov r0.y, r1.z
                mov r0.z, v2.z
                dp3 r0.z, v0.xzww, r0
                mov r1.w, v2.x
                dp3 r0.x, v0.xzww, r1.xyww
                mul r1.xy, c9, v3.y
                mov r1.w, v2.y
                dp4 r0.y, v0.xzyw, r1.xxyw
                add r1.xyz, r0, -c7
                dp3 r0.w, r1, c4
                mad r0.xyz, r0.w, c6, r0
                mov r0.w, v0.w
                dp4 o2.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad o2.xy, c5, r0.x, r1
                mov o2.w, r0.x
                mov o0.xy, v1
                mov o1, v4
            
            // approximately 33 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_3_0
                def c0, -0.00390625, 0, 0, 0
                dcl_texcoord v0.xy
                dcl_texcoord1 v1
                dcl_2d s0
                texld r0, v0, s0
                mad r1, v1.w, r0.w, c0.x
                mul r0, r0, v1
                mov oC0, r0
                texkill r1
            
            // approximately 5 instruction slots used (1 texture, 4 arithmetic)
            };
    }
}

