// HwTrileEffect
// A0639906EE6453880556104A62FADC26CF5CB27FA7A718AA775AB106FABD4D71

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Blink;
            //   float Fog_Type;
            //   float Shiny;
            //   float TiltTwoAxis;
            //   float Time;
            //   float Unstable;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Time         c0       1
            //   Fog_Type     c1       1
            //   Blink        c2       1
            //   Unstable     c3       1
            //   TiltTwoAxis  c4       1
            //   Shiny        c5       1
            //
            
                preshader
                neg r0.x, c4.x
                max r1.x, r0.x, c4.x
                neg r0.x, r1.x
                lt c3.x, r0.x, r1.x
                neg r0.x, c5.x
                max r1.x, r0.x, c5.x
                neg r0.x, r1.x
                lt r2.x, r0.x, r1.x
                neg r0.x, c3.x
                max r1.x, r0.x, c3.x
                neg r0.x, r1.x
                lt r2.y, r0.x, r1.x
                mul r0.x, r2.y, (0.400000006)
                mul r0.z, r2.y, (0)
                mov c1.x, r2.y
                neg r1.x, r0.x
                neg r1.z, r0.z
                add r0.y, r1.x, (0.349999994)
                add r0.w, r1.z, (0.850000024)
                mul r1.x, r0.y, r2.x
                mul r1.z, r0.w, r2.x
                add c13.x, r0.x, r1.x
                add c13.z, r0.z, r1.z
                neg r0.x, c1.x
                max r1.x, r0.x, c1.x
                neg r0.x, r1.x
                ge c9.x, r0.x, r1.x
                add r0.x, c1.x, (-2)
                neg r1.x, r0.x
                max r2.x, r0.x, r1.x
                neg r0.x, r2.x
                ge c8.x, r0.x, r2.x
                neg r0.x, c2.x
                max r1.x, r0.x, c2.x
                neg r0.x, r1.x
                lt c12.x, r0.x, r1.x
                mul c11.x, c0.x, (0.100000001)
                mov c13.y, (0)
            
            // approximately 38 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //   float Time;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c14      4
            //   Time                         c18      1
            //   Fog_Density                  c19      1
            //   Eye                          c20      1
            //   TexelOffset                  c21      1
            //   EyeSign                      c22      1
            //   LevelCenter                  c23      1
            //
            
                vs_3_0
                def c24, 0.577350259, 1.44269502, 0.75, 0
                def c25, 4.36681223, -0.397887349, -0.795774698, 0.5
                def c26, 6.28318548, -3.14159274, 0.159154937, 0.5
                def c27, 0.125, 1, 0, -1
                def c28, 0.707106769, 0.408248305, -0.707106769, -0.816496611
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord2 v3
                dcl_texcoord3 v4
                dcl_texcoord o0.xyz
                dcl_texcoord1 o1.x
                dcl_texcoord2 o2.xy
                dcl_texcoord3 o3.x
                dcl_texcoord4 o4
                dcl_position o5
                mad r0.x, v3.w, c26.z, c26.w
                frc r0.x, r0.x
                mad r0.x, r0.x, c26.x, c26.y
                sincos r1.xy, r0.x
                mul r0.xyz, r1.xxyw, c27.yzyw
                mov r0.w, -r0.z
                mov r2.x, c25.x
                mad r1.z, v4.x, r2.x, c18.x
                mad r1.w, r1.z, c25.z, c25.w
                mul r1.z, r1.z, c25.y
                frc r1.zw, r1
                slt r1.z, r1.z, c27.x
                mad r1.w, r1.w, c26.x, c26.y
                sincos r3.xy, r1.w
                mul r4.z, -r3.y, r3.x
                mul r4.xy, r3, r3
                mov r5.xy, r4.zyzw
                mov r5.z, r3.x
                add r2.yzw, -r0.xwyx, r5.xxyz
                mul r2.yzw, r1.z, r2
                mul r2.yzw, r2, c1.x
                mad r2.yzw, r0.xzyx, c27.xwyy, r2
                mad r3.zw, r1.xyyx, -c27.y, r3.xyyx
                mul r5.yz, r1.z, r3.xzww
                max r0.w, r3.y, c27.z
                dp3 r1.w, v0, c27.y
                mul_sat r1.w, r1.w, c25.w
                mul r6.x, r0.w, r1.w
                mov r6.yz, c27.z
                mov r5.x, c27.z
                add r5.xyz, r5, r6
                mad r5.xyz, c1.x, r5, r0.yzxw
                mul r6, r5.zyyz, c28.xyzy
                mad r7.xy, r5.zyzw, c28.zxzw, r6.ywzw
                add r6.xy, r6.ywzw, r6.xzzw
                mul r3.zw, r5.xyyz, c28.w
                mov o4.w, r5.x
                mov r7.w, r3.w
                mov r6.z, r3.z
                mov r7.z, r6.y
                lrp r5.xyz, c3.x, r7.zwyw, r2.yzww
                mov r6.w, r7.x
                add r5.w, c25.w, v3.z
                dp4 r7.z, v0, r5
                dp3 o0.z, v1, r5
                mov r4.w, r3.y
                add r2.yz, r3.xyxw, -c27.xzyw
                mul r3.xy, r1.z, r2.yzzw
                mad r1.xyw, r1.xxzy, -c27.yzzy, r4.xzzw
                mul r1.xyz, r1.xyww, r1.z
                mad r0.xyz, c1.x, r1, r0
                lrp r1.xyz, c3.x, r6.xzww, r0
                add r1.w, c25.w, v3.x
                dp4 r7.x, v0, r1
                dp3 o0.x, v1, r1
                mov r3.z, c27.z
                mov r0.yz, c27
                mad r0.xzw, c1.x, r3.xyyz, r0.zyyz
                add r1.xyz, -r0.xzww, c24.x
                mad r1.xyz, c3.x, r1, r0.xzww
                add r1.w, c25.w, v3.y
                dp4 r7.y, v0, r1
                dp3 o0.y, v1, r1
                add r0.xzw, r7.xyyz, -c23.xyyz
                dp3 r0.x, r0.xzww, c20
                mad r1.xyz, r0.x, c22, r7
                mov r1.w, v0.w
                dp4 o5.z, r1, c16
                dp4 r3.x, r1, c14
                dp4 r3.y, r1, c15
                dp4 r0.x, r1, c17
                mad o5.xy, c21, r0.x, r3
                mul r0.z, r0.x, c19.x
                mov o5.w, r0.x
                mul r0.x, r0.z, r0.z
                mul r0.x, r0.x, r0.z
                mul r0.x, r0.x, c24.y
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c8.x
                mad r0.x, r0.x, r1.x, c9.x
                add_sat o1.x, -r0.x, c27.y
                mad r0.x, v4.x, r2.x, c11.x
                frc r0.x, r0.x
                slt r0.x, r0.x, c24.z
                add r0.x, r0.x, c27.w
                mad o3.x, c12.x, r0.x, r0.y
                mov o2.xy, v2
                mov o4.xyz, c13
            
            // approximately 103 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   BaseAmbient  c1       1
            //
            
                preshader
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AtlasSampler;
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c2       1
            //   BaseAmbient  c3       1
            //   AtlasSampler s0       1
            //
            
                ps_3_0
                def c4, 1, 0.00999999978, 0.600000024, 0.300000012
                def c5, 0.5, 0, 0, 0
                dcl_texcoord v0.xyz
                dcl_texcoord1 v1.x
                dcl_texcoord2 v2.xy
                dcl_texcoord3 v3.x
                dcl_texcoord4 v4.xy
                dcl_2d s0
                texld r0, v2, s0
                add r0.xy, r0.w, v4.yxzw
                add_sat r0.yzw, r0.y, c3.xxyz
                mul r1.xyz, r0.x, c1
                mul r1.xyz, r1, v3.x
                dp3_sat r0.x, v0, c4.x
                mad r0.xyz, r0.x, c0, r0.yzww
                mul r2.xyz, c0, v0_abs.z
                mad r2.xyz, r2, c4.z, r0
                add r3.xy, c4.y, v0.zxzw
                cmp r0.xyz, r3.x, r0, r2
                mul r2.xyz, c0, v0_abs.x
                mad r2.xyz, r2, c4.w, r0
                cmp_sat r0.xyz, r3.y, r0, r2
                mad r0.xyz, r0, c2, r1
                lrp r1.xyz, v1.x, c4.x, r0
                mul oC0.xyz, r1, c5.x
                mov oC0.w, c4.x
            
            // approximately 18 instruction slots used (1 texture, 17 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Blink;
            //   float Fog_Type;
            //   float Shiny;
            //   float TiltTwoAxis;
            //   float Time;
            //   float Unstable;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Time         c0       1
            //   Fog_Type     c1       1
            //   Blink        c2       1
            //   Unstable     c3       1
            //   TiltTwoAxis  c4       1
            //   Shiny        c5       1
            //
            
                preshader
                neg r0.x, c4.x
                max r1.x, r0.x, c4.x
                neg r0.x, r1.x
                lt c3.x, r0.x, r1.x
                neg r0.x, c5.x
                max r1.x, r0.x, c5.x
                neg r0.x, r1.x
                lt r2.x, r0.x, r1.x
                neg r0.x, c3.x
                max r1.x, r0.x, c3.x
                neg r0.x, r1.x
                lt r2.y, r0.x, r1.x
                mul r0.x, r2.y, (0.400000006)
                mul r0.z, r2.y, (0)
                mov c1.x, r2.y
                neg r1.x, r0.x
                neg r1.z, r0.z
                add r0.y, r1.x, (0.349999994)
                add r0.w, r1.z, (0.850000024)
                mul r1.x, r0.y, r2.x
                mul r1.z, r0.w, r2.x
                add c13.x, r0.x, r1.x
                add c13.z, r0.z, r1.z
                neg r0.x, c1.x
                max r1.x, r0.x, c1.x
                neg r0.x, r1.x
                ge c9.x, r0.x, r1.x
                add r0.x, c1.x, (-2)
                neg r1.x, r0.x
                max r2.x, r0.x, r1.x
                neg r0.x, r2.x
                ge c8.x, r0.x, r2.x
                neg r0.x, c2.x
                max r1.x, r0.x, c2.x
                neg r0.x, r1.x
                lt c12.x, r0.x, r1.x
                mul c11.x, c0.x, (0.100000001)
                mov c13.y, (0)
            
            // approximately 38 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //   float Time;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c14      4
            //   Time                         c18      1
            //   Fog_Density                  c19      1
            //   Eye                          c20      1
            //   TexelOffset                  c21      1
            //   EyeSign                      c22      1
            //   LevelCenter                  c23      1
            //
            
                vs_3_0
                def c24, 0.577350259, 1.44269502, 0.75, 0
                def c25, 4.36681223, -0.397887349, -0.795774698, 0.5
                def c26, 6.28318548, -3.14159274, 0.159154937, 0.5
                def c27, 0.125, 1, 0, -1
                def c28, 0.707106769, 0.408248305, -0.707106769, -0.816496611
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord2 v3
                dcl_texcoord3 v4
                dcl_texcoord o0.xyz
                dcl_texcoord1 o1.x
                dcl_texcoord2 o2.xy
                dcl_texcoord3 o3.x
                dcl_texcoord4 o4
                dcl_position o5
                mad r0.x, v3.w, c26.z, c26.w
                frc r0.x, r0.x
                mad r0.x, r0.x, c26.x, c26.y
                sincos r1.xy, r0.x
                mul r0.xyz, r1.xxyw, c27.yzyw
                mov r0.w, -r0.z
                mov r2.x, c25.x
                mad r1.z, v4.x, r2.x, c18.x
                mad r1.w, r1.z, c25.z, c25.w
                mul r1.z, r1.z, c25.y
                frc r1.zw, r1
                slt r1.z, r1.z, c27.x
                mad r1.w, r1.w, c26.x, c26.y
                sincos r3.xy, r1.w
                mul r4.z, -r3.y, r3.x
                mul r4.xy, r3, r3
                mov r5.xy, r4.zyzw
                mov r5.z, r3.x
                add r2.yzw, -r0.xwyx, r5.xxyz
                mul r2.yzw, r1.z, r2
                mul r2.yzw, r2, c1.x
                mad r2.yzw, r0.xzyx, c27.xwyy, r2
                mad r3.zw, r1.xyyx, -c27.y, r3.xyyx
                mul r5.yz, r1.z, r3.xzww
                max r0.w, r3.y, c27.z
                dp3 r1.w, v0, c27.y
                mul_sat r1.w, r1.w, c25.w
                mul r6.x, r0.w, r1.w
                mov r6.yz, c27.z
                mov r5.x, c27.z
                add r5.xyz, r5, r6
                mad r5.xyz, c1.x, r5, r0.yzxw
                mul r6, r5.zyyz, c28.xyzy
                mad r7.xy, r5.zyzw, c28.zxzw, r6.ywzw
                add r6.xy, r6.ywzw, r6.xzzw
                mul r3.zw, r5.xyyz, c28.w
                mov o4.w, r5.x
                mov r7.w, r3.w
                mov r6.z, r3.z
                mov r7.z, r6.y
                lrp r5.xyz, c3.x, r7.zwyw, r2.yzww
                mov r6.w, r7.x
                add r5.w, c25.w, v3.z
                dp4 r7.z, v0, r5
                dp3 o0.z, v1, r5
                mov r4.w, r3.y
                add r2.yz, r3.xyxw, -c27.xzyw
                mul r3.xy, r1.z, r2.yzzw
                mad r1.xyw, r1.xxzy, -c27.yzzy, r4.xzzw
                mul r1.xyz, r1.xyww, r1.z
                mad r0.xyz, c1.x, r1, r0
                lrp r1.xyz, c3.x, r6.xzww, r0
                add r1.w, c25.w, v3.x
                dp4 r7.x, v0, r1
                dp3 o0.x, v1, r1
                mov r3.z, c27.z
                mov r0.yz, c27
                mad r0.xzw, c1.x, r3.xyyz, r0.zyyz
                add r1.xyz, -r0.xzww, c24.x
                mad r1.xyz, c3.x, r1, r0.xzww
                add r1.w, c25.w, v3.y
                dp4 r7.y, v0, r1
                dp3 o0.y, v1, r1
                add r0.xzw, r7.xyyz, -c23.xyyz
                dp3 r0.x, r0.xzww, c20
                mad r1.xyz, r0.x, c22, r7
                mov r1.w, v0.w
                dp4 o5.z, r1, c16
                dp4 r3.x, r1, c14
                dp4 r3.y, r1, c15
                dp4 r0.x, r1, c17
                mad o5.xy, c21, r0.x, r3
                mul r0.z, r0.x, c19.x
                mov o5.w, r0.x
                mul r0.x, r0.z, r0.z
                mul r0.x, r0.x, r0.z
                mul r0.x, r0.x, c24.y
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c8.x
                mad r0.x, r0.x, r1.x, c9.x
                add_sat o1.x, -r0.x, c27.y
                mad r0.x, v4.x, r2.x, c11.x
                frc r0.x, r0.x
                slt r0.x, r0.x, c24.z
                add r0.x, r0.x, c27.w
                mad o3.x, c12.x, r0.x, r0.y
                mov o2.xy, v2
                mov o4.xyz, c13
            
            // approximately 103 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float3 Eye;
            //   float ForceShading;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   DiffuseLight     c0       1
            //   BaseAmbient      c1       1
            //   Eye              c2       1
            //   Material_Opacity c3       1
            //   ForceShading     c4       1
            //
            
                preshader
                add c0.xyz, c2.xyz, (-0, -0.25, -0)
                neg r0.x, c4.x
                max c1.x, r0.x, c4.x
                neg r0.xyz, c1.xyz
                add c2.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c3.xyz, (1, 1, 1), r0.xyz
                mov c4.x, c3.x
            
            // approximately 8 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AtlasSampler;
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float3 Fog_Color;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c5       1
            //   Fog_Color    c6       1
            //   BaseAmbient  c7       1
            //   AtlasSampler s0       1
            //
            
                ps_3_0
                def c8, 1, 0.00999999978, 0.600000024, 0.300000012
                dcl_texcoord v0.xyz
                dcl_texcoord1 v1.x
                dcl_texcoord2 v2.xy
                dcl_texcoord3 v3.x
                dcl_texcoord4 v4
                dcl_2d s0
                texld r0, v2, s0
                add r1.x, r0.w, v4.x
                add r0, r0, v4.wwwy
                add_sat r1.xyz, r1.x, c7
                dp3_sat r1.w, v0, c8.x
                mad r1.xyz, r1.w, c2, r1
                mul r2.xyz, c2, v0_abs.z
                mad r2.xyz, r2, c8.z, r1
                add r3.xy, c8.y, v0.zxzw
                cmp r1.xyz, r3.x, r1, r2
                mul r2.xyz, c2, v0_abs.x
                mad r2.xyz, r2, c8.w, r1
                cmp_sat r1.xyz, r3.y, r1, r2
                mul r2.xyz, r0.w, c3
                mul r2.xyz, r2, v3.x
                mad r1.xyz, r1, c5, r2
                dp3 r0.w, c0, v0
                mul r0.w, r0.w, r0.w
                mul r0.w, r0.w, r0.w
                mul_sat r0.w, r0.w, r0.w
                mad r0.xyz, r0.w, v4.z, r0
                mul r1.xyz, r1, r0
                cmp r0.xyz, -c1.x, r0, r1
                add r1.xyz, -r0, c6
                mad oC0.xyz, v1.x, r1, r0
                mov oC0.w, c4.x
            
            // approximately 26 instruction slots used (1 texture, 25 arithmetic)
            };
    }
}

