// HwTrixelParticleEffect
// 4A4BD6EB0E30FE770E35FE9BD0EE69B4DFC0CA8BFDD76EFA0A96548A30BD8C3E

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Eye                          c4       1
            //   TexelOffset                  c5       1
            //   EyeSign                      c6       1
            //   LevelCenter                  c7       1
            //
            
                vs_3_0
                def c8, 1, 0, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord2 v3
                dcl_texcoord3 v4
                dcl_texcoord4 v5
                dcl_texcoord5 v6
                dcl_texcoord o0.xy
                dcl_texcoord1 o1
                dcl_texcoord2 o2.xyz
                dcl_position o3
                mov r0, v6
                mad o0.xy, v2, r0, r0.zwzw
                mul r0.xy, c8, v4.x
                mov r0.w, v3.x
                dp4 r0.x, v0, r0.xyyw
                mul r1.xy, c8.yxzw, v4
                mov r1.w, v3.y
                dp4 r0.y, v0.xzyw, r1.xxyw
                mul r1.xz, c8.yyxw, v4
                mov r1.w, v3.z
                dp4 r0.z, v0, r1.xxzw
                add r1.xyz, r0, -c7
                dp3 r0.w, r1, c4
                mad r0.xyz, r0.w, c6, r0
                mov r0.w, v0.w
                dp4 o3.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad o3.xy, c5, r0.x, r1
                mov o3.w, r0.x
                mov o1, v5
                mov o2.xyz, v1
            
            // approximately 23 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   BaseAmbient  c1       1
            //
            
                preshader
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D BaseSampler;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c2       1
            //   BaseAmbient  c3       1
            //   BaseSampler  s0       1
            //
            
                ps_3_0
                def c4, -1, 1, 0.00999999978, 0.600000024
                def c5, 0.300000012, 0.5, 0, 0
                dcl_texcoord v0.xy
                dcl_texcoord1 v1
                dcl_texcoord2 v2.xyz
                dcl_2d s0
                mul r0.xyz, c0, v2_abs.z
                dp3_sat r0.w, v2, c4.y
                add_sat r1.xyz, c4.x, v1
                add_sat r2.xyz, r1.x, c3
                mul r1.xyz, r1, c1
                mad r2.xyz, r0.w, c0, r2
                mad r0.xyz, r0, c4.w, r2
                add r3.xy, c4.z, v2.zxzw
                cmp r0.xyz, r3.x, r2, r0
                mul r2.xyz, c0, v2_abs.x
                mad r2.xyz, r2, c5.x, r0
                cmp_sat r0.xyz, r3.y, r0, r2
                mul r0.xyz, r0, c2
                mad oC0.xyz, r0, c5.y, r1
                texld r0, v0, s0
                add r0.x, -r0.w, c4.y
                mul oC0.w, r0.x, v1.w
            
            // approximately 17 instruction slots used (1 texture, 16 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Eye                          c4       1
            //   TexelOffset                  c5       1
            //   EyeSign                      c6       1
            //   LevelCenter                  c7       1
            //
            
                vs_3_0
                def c8, 1, 0, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord2 v3
                dcl_texcoord3 v4
                dcl_texcoord4 v5
                dcl_texcoord5 v6
                dcl_texcoord o0.xy
                dcl_texcoord1 o1
                dcl_texcoord2 o2.xyz
                dcl_position o3
                mov r0, v6
                mad o0.xy, v2, r0, r0.zwzw
                mul r0.xy, c8, v4.x
                mov r0.w, v3.x
                dp4 r0.x, v0, r0.xyyw
                mul r1.xy, c8.yxzw, v4
                mov r1.w, v3.y
                dp4 r0.y, v0.xzyw, r1.xxyw
                mul r1.xz, c8.yyxw, v4
                mov r1.w, v3.z
                dp4 r0.z, v0, r1.xxzw
                add r1.xyz, r0, -c7
                dp3 r0.w, r1, c4
                mad r0.xyz, r0.w, c6, r0
                mov r0.w, v0.w
                dp4 o3.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad o3.xy, c5, r0.x, r1
                mov o3.w, r0.x
                mov o1, v5
                mov o2.xyz, v1
            
            // approximately 23 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_3_0
                def c0, 1, 0, 0, 0
                dcl_texcoord v0.xy
                dcl_texcoord1 v1
                dcl_2d s0
                texld r0, v0, s0
                mul oC0.xyz, r0, v1
                add r0.x, -r0.w, c0.x
                mul oC0.w, r0.x, v1.w
            
            // approximately 4 instruction slots used (1 texture, 3 arithmetic)
            };
    }
}

