// InstancedAnimatedPlaneEffect
// F02CFF9DEBF7418D09E7EC5BA6E9B2EB3E2D1D6C541B959857C10A14BBA80748

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float2 FrameScale;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //   FrameScale   c2       1
            //
            
                preshader
                mul r0.x, c1.x, c1.x
                neg r1.x, r0.x
                lt c238.x, r1.x, r0.x
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c237.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c236.x, r0.x, r1.x
                mov c239.x, c2.y
            
            // approximately 11 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float2 FrameScale;
            //   float4x4 InstanceData[58];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     232
            //   Matrices_WorldViewProjection c232     4
            //   Fog_Density                  c240     1
            //   Eye                          c241     1
            //   TexelOffset                  c242     1
            //   EyeSign                      c243     1
            //   LevelCenter                  c244     1
            //   FrameScale                   c245     1
            //
            
                vs_2_0
                def c246, 4, 2, -1, 0.5
                def c247, 0.5, 0.25, 0.125, 0.0625
                def c248, 2, 1, 1.44269502, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord1 v3
                slt r0.x, v3.x, -v3.x
                frc r0.y, v3.x
                add r0.z, -r0.y, v3.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0.x, r0.x, c246.x
                mova a0.x, r0.x
                frc r0.x, c3[a0.x].z
                add r0.y, -r0.x, c3[a0.x].z
                slt r0.x, -r0.x, r0.x
                slt r0.z, c3[a0.x].z, -c3[a0.x].z
                mad r0.x, r0.z, r0.x, r0.y
                mul r0, r0.x, c247
                abs r1, r0
                sge r0, r0, -r0
                frc r1, r1
                lrp r2, r0, r1, -r1
                sge r0.yzw, r2, c246.w
                mad r1.x, r2.x, c246.y, c246.z
                mul r1.x, r1.x, r1.x
                sge r0.x, -r1.x, r1.x
                mov oT4.xy, r0.xwzw
                add r0.xy, r0.zwzw, r0.y
                slt r0.xy, -r0, r0
                mov r1.yz, c0[a0.x]
                lrp r2.x, r0.x, r1.z, -c246.z
                mul r0.x, r2.x, v2.x
                mov r2.xy, c3[a0.x]
                mad oT0.x, r0.x, c245.x, r2.x
                mov r3.yz, c1[a0.x]
                lrp r1.x, r0.y, r3.z, -c246.z
                mul r0.x, r1.x, v2.y
                mov r0.z, c2[a0.x].z
                mad oT0.y, r0.x, c245.y, r0.z
                mul r0.x, c2[a0.x].y, c2[a0.x].y
                mad r0.x, c1[a0.x].y, c1[a0.x].y, r0.x
                mad r0.x, r0.x, -c248.x, c248.y
                mul r1.x, r2.y, c2[a0.x].y
                mad r1.z, r1.y, c1[a0.x].y, -r1.x
                mad r1.x, r1.y, c1[a0.x].y, r1.x
                add r4.x, r1.x, r1.x
                add r0.y, r1.z, r1.z
                mul r1.x, r2.y, c1[a0.x].y
                mad r1.z, c2[a0.x].y, r1.y, r1.x
                mad r1.x, c2[a0.x].y, r1.y, -r1.x
                add r2.x, r1.x, r1.x
                add r0.z, r1.z, r1.z
                dp3 oT1.x, v1, r0
                mul r0.x, r0.x, c0[a0.x].z
                mul r0.y, r0.y, c1[a0.x].z
                mul r1.x, c0[a0.x].y, c0[a0.x].y
                mad r1.z, c2[a0.x].y, c2[a0.x].y, r1.x
                mad r1.x, c1[a0.x].y, c1[a0.x].y, r1.x
                mad r2.z, r1.x, -c248.x, c248.y
                mad r4.y, r1.z, -c248.x, c248.y
                mul r1.x, r1.y, c3[a0.x].y
                mad r1.y, r3.y, c2[a0.x].y, -r1.x
                mad r1.x, r3.y, c2[a0.x].y, r1.x
                add r2.y, r1.x, r1.x
                add r4.z, r1.y, r1.y
                dp3 oT1.y, v1, r4
                mul r4.y, r4.y, c1[a0.x].z
                mul r4.x, r4.x, c0[a0.x].z
                dp3 oT1.z, v1, r2
                mul r2.x, r2.x, c0[a0.x].z
                mul r2.y, r2.y, c1[a0.x].z
                mov r0.w, c0[a0.x].x
                dp4 r0.x, v0, r0
                mov r4.w, c1[a0.x].x
                dp4 r0.y, v0, r4
                mov r2.w, c2[a0.x].x
                dp4 r0.z, v0, r2
                add r1.xyz, r0, -c244
                dp3 r0.w, r1, c241
                mad r0.xyz, r0.w, c243, r0
                mov r0.w, v0.w
                dp4 oPos.z, r0, c234
                dp4 r1.x, r0, c232
                dp4 r1.y, r0, c233
                dp4 r0.x, r0, c235
                mad oPos.xy, c242, r0.x, r1
                mul r0.y, r0.x, c240.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c248.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c236.x
                mad r0.x, r0.x, r1.x, c237.x
                add r0.x, -r0.x, -c246.z
                max r0.x, r0.x, c248.w
                min r0.x, r0.x, -c246.z
                mad oT2.x, c238.x, -r0.x, r0.x
                mov oT3.x, c0[a0.x].w
                mov oT3.y, c1[a0.x].w
                mov oT3.z, c2[a0.x].w
                mov oT3.w, c3[a0.x].w
                mov oT5.x, c2[a0.x].z
                mov oT5.y, c239.x
            
            // approximately 100 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float IgnoreShading;
            //   float SewerHax;
            //
            //
            // Registers:
            //
            //   Name          Reg   Size
            //   ------------- ----- ----
            //   DiffuseLight  c0       1
            //   BaseAmbient   c1       1
            //   IgnoreShading c2       1
            //   SewerHax      c3       1
            //
            
                preshader
                mul c0.x, c2.x, c2.x
                neg r0.xyz, c1.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c2.xyz, (1, 1, 1), r0.xyz
                mul c3.x, c3.x, c3.x
            
            // approximately 6 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AnimatedSampler;
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   DiffuseLight    c4       1
            //   BaseAmbient     c5       1
            //   AnimatedSampler s0       1
            //
            
                ps_2_0
                def c6, 1, 0.00999999978, 0.600000024, 0.300000012
                def c7, -0.00390625, 0.75, 0, 1
                def c8, 0.5, 0, 0, 0
                dcl t0.xy
                dcl t1.xyz
                dcl t2.x
                dcl t3
                dcl t4.xy
                dcl t5.xy
                dcl_2d s0
                mov r0.w, t5.x
                add r0.x, -r0.w, t0.y
                rcp r0.y, t5.y
                mul r0.x, r0.y, r0.x
                frc r0.x, r0.x
                mad r0.x, r0.x, t5.y, t5.x
                mov r1.xy, t4
                cmp r0.y, -r1.y, t0.y, r0.x
                mov r0.x, t0.x
                texld r0, r0, s0
                mad r2, t3.w, r0.w, c7.x
                texkill r2
                abs r0.y, t1.z
                mul r1.yzw, r0.y, c1.wzyx
                mov r2.x, c6.x
                cmp r0.y, -c0.x, r1.x, r2.x
                add_sat r2.xyz, r0.y, c5
                dp3_sat r2.w, t1, c6.x
                mad r2.xyz, r2.w, c1, r2
                mad r1.xyz, r1.wzyx, c6.z, r2
                add r1.w, t1.z, c6.y
                cmp r1.xyz, r1.w, r2, r1
                abs r1.w, t1.x
                mul r2.xyz, r1.w, c1
                mad r2.xyz, r2, c6.w, r1
                add r1.w, t1.x, c6.y
                cmp_sat r1.xyz, r1.w, r1, r2
                mul r2.xyz, t4.x, c2
                mad r1.xyz, r1, c4, r2
                lrp r2.xyz, t2.x, c6.x, r1
                add r2.w, -r0.x, c7.y
                mul r0.w, r0.w, t3.w
                cmp r2.w, r2.w, c7.z, c7.w
                cmp r1.xyz, -c3.x, r2, r2.w
                mul r0.xyz, r1, c8.x
                mov oC0, r0
            
            // approximately 36 instruction slots used (1 texture, 35 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float2 FrameScale;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //   FrameScale   c2       1
            //
            
                preshader
                mul r0.x, c1.x, c1.x
                neg r1.x, r0.x
                lt c238.x, r1.x, r0.x
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c237.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c236.x, r0.x, r1.x
                mov c239.x, c2.y
            
            // approximately 11 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float2 FrameScale;
            //   float4x4 InstanceData[58];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     232
            //   Matrices_WorldViewProjection c232     4
            //   Fog_Density                  c240     1
            //   Eye                          c241     1
            //   TexelOffset                  c242     1
            //   EyeSign                      c243     1
            //   LevelCenter                  c244     1
            //   FrameScale                   c245     1
            //
            
                vs_2_0
                def c246, 4, 2, -1, 0.5
                def c247, 0.5, 0.25, 0.125, 0.0625
                def c248, 2, 1, 1.44269502, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord1 v3
                slt r0.x, v3.x, -v3.x
                frc r0.y, v3.x
                add r0.z, -r0.y, v3.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0.x, r0.x, c246.x
                mova a0.x, r0.x
                frc r0.x, c3[a0.x].z
                add r0.y, -r0.x, c3[a0.x].z
                slt r0.x, -r0.x, r0.x
                slt r0.z, c3[a0.x].z, -c3[a0.x].z
                mad r0.x, r0.z, r0.x, r0.y
                mul r0, r0.x, c247
                abs r1, r0
                sge r0, r0, -r0
                frc r1, r1
                lrp r2, r0, r1, -r1
                sge r0.yzw, r2, c246.w
                mad r1.x, r2.x, c246.y, c246.z
                mul r1.x, r1.x, r1.x
                sge r0.x, -r1.x, r1.x
                mov oT4.xy, r0.xwzw
                add r0.xy, r0.zwzw, r0.y
                slt r0.xy, -r0, r0
                mov r1.yz, c0[a0.x]
                lrp r2.x, r0.x, r1.z, -c246.z
                mul r0.x, r2.x, v2.x
                mov r2.xy, c3[a0.x]
                mad oT0.x, r0.x, c245.x, r2.x
                mov r3.yz, c1[a0.x]
                lrp r1.x, r0.y, r3.z, -c246.z
                mul r0.x, r1.x, v2.y
                mov r0.z, c2[a0.x].z
                mad oT0.y, r0.x, c245.y, r0.z
                mul r0.x, c2[a0.x].y, c2[a0.x].y
                mad r0.x, c1[a0.x].y, c1[a0.x].y, r0.x
                mad r0.x, r0.x, -c248.x, c248.y
                mul r1.x, r2.y, c2[a0.x].y
                mad r1.z, r1.y, c1[a0.x].y, -r1.x
                mad r1.x, r1.y, c1[a0.x].y, r1.x
                add r4.x, r1.x, r1.x
                add r0.y, r1.z, r1.z
                mul r1.x, r2.y, c1[a0.x].y
                mad r1.z, c2[a0.x].y, r1.y, r1.x
                mad r1.x, c2[a0.x].y, r1.y, -r1.x
                add r2.x, r1.x, r1.x
                add r0.z, r1.z, r1.z
                dp3 oT1.x, v1, r0
                mul r0.x, r0.x, c0[a0.x].z
                mul r0.y, r0.y, c1[a0.x].z
                mul r1.x, c0[a0.x].y, c0[a0.x].y
                mad r1.z, c2[a0.x].y, c2[a0.x].y, r1.x
                mad r1.x, c1[a0.x].y, c1[a0.x].y, r1.x
                mad r2.z, r1.x, -c248.x, c248.y
                mad r4.y, r1.z, -c248.x, c248.y
                mul r1.x, r1.y, c3[a0.x].y
                mad r1.y, r3.y, c2[a0.x].y, -r1.x
                mad r1.x, r3.y, c2[a0.x].y, r1.x
                add r2.y, r1.x, r1.x
                add r4.z, r1.y, r1.y
                dp3 oT1.y, v1, r4
                mul r4.y, r4.y, c1[a0.x].z
                mul r4.x, r4.x, c0[a0.x].z
                dp3 oT1.z, v1, r2
                mul r2.x, r2.x, c0[a0.x].z
                mul r2.y, r2.y, c1[a0.x].z
                mov r0.w, c0[a0.x].x
                dp4 r0.x, v0, r0
                mov r4.w, c1[a0.x].x
                dp4 r0.y, v0, r4
                mov r2.w, c2[a0.x].x
                dp4 r0.z, v0, r2
                add r1.xyz, r0, -c244
                dp3 r0.w, r1, c241
                mad r0.xyz, r0.w, c243, r0
                mov r0.w, v0.w
                dp4 oPos.z, r0, c234
                dp4 r1.x, r0, c232
                dp4 r1.y, r0, c233
                dp4 r0.x, r0, c235
                mad oPos.xy, c242, r0.x, r1
                mul r0.y, r0.x, c240.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c248.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c236.x
                mad r0.x, r0.x, r1.x, c237.x
                add r0.x, -r0.x, -c246.z
                max r0.x, r0.x, c248.w
                min r0.x, r0.x, -c246.z
                mad oT2.x, c238.x, -r0.x, r0.x
                mov oT3.x, c0[a0.x].w
                mov oT3.y, c1[a0.x].w
                mov oT3.z, c2[a0.x].w
                mov oT3.w, c3[a0.x].w
                mov oT5.x, c2[a0.x].z
                mov oT5.y, c239.x
            
            // approximately 100 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AnimatedSampler;
            //   float3 Fog_Color;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   Fog_Color       c0       1
            //   AnimatedSampler s0       1
            //
            
                ps_2_0
                def c1, -0.00390625, 0, 0, 0
                dcl t0.xy
                dcl t2.x
                dcl t3
                dcl t5.xy
                dcl_2d s0
                mov r0.w, t5.x
                add r0.x, -r0.w, t0.y
                rcp r0.y, t5.y
                mul r0.x, r0.y, r0.x
                frc r0.x, r0.x
                mad r0.y, r0.x, t5.y, t5.x
                mov r0.x, t0.x
                texld r0, r0, s0
                mad r1, t3.w, r0.w, c1.x
                texkill r1
                mul r1.xyz, r0, t3
                mad r0.xyz, r0, -t3, c0
                mul r2.w, r0.w, t3.w
                mad r2.xyz, t2.x, r0, r1
                mov oC0, r2
            
            // approximately 15 instruction slots used (1 texture, 14 arithmetic)
            };
    }
}

