// InstancedStaticPlaneEffect
// 39BAA693E665A43A94CC188B9CA4CA3DDE0EA913CAFA01392E4157B784EFAC53

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //
            
                preshader
                mul r0.x, c1.x, c1.x
                neg r1.x, r0.x
                lt c242.x, r1.x, r0.x
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c241.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c240.x, r0.x, r1.x
            
            // approximately 10 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float4x4 InstanceData[59];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     236
            //   Matrices_WorldViewProjection c236     4
            //   Fog_Density                  c243     1
            //   Eye                          c244     1
            //   TexelOffset                  c245     1
            //   EyeSign                      c246     1
            //   LevelCenter                  c247     1
            //
            
                vs_2_0
                def c248, 4, 2, -1, 0.5
                def c249, 0.5, 0.25, 0.125, 0.0625
                def c250, 2, 1, 1.44269502, 0
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord1 v2
                slt r0.x, v2.x, -v2.x
                frc r0.y, v2.x
                add r0.z, -r0.y, v2.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0.x, r0.x, c248.x
                mova a0.x, r0.x
                frc r0.x, c3[a0.x].z
                add r0.y, -r0.x, c3[a0.x].z
                slt r0.x, -r0.x, r0.x
                slt r0.z, c3[a0.x].z, -c3[a0.x].z
                mad r0.x, r0.z, r0.x, r0.y
                mul r0, r0.x, c249
                abs r1, r0
                sge r0, r0, -r0
                frc r1, r1
                lrp r2, r0, r1, -r1
                mad r0.x, r2.x, c248.y, c248.z
                sge r0.yzw, r2, c248.w
                add r0.yz, r0.xzww, r0.y
                slt r0.yz, -r0, r0
                mul r0.x, r0.x, r0.x
                sge oT4.x, -r0.x, r0.x
                mov r1.yz, c0[a0.x]
                lrp r2.x, r0.y, r1.z, -c248.z
                mul oT0.x, r2.x, v1.x
                mov r2.yz, c1[a0.x]
                lrp r1.x, r0.z, r2.z, -c248.z
                mul oT0.y, r1.x, v1.y
                mul r0.x, c2[a0.x].y, c2[a0.x].y
                mad r0.x, c1[a0.x].y, c1[a0.x].y, r0.x
                mad r0.x, r0.x, -c250.x, c250.y
                mul r0.x, r0.x, c0[a0.x].z
                mov r3.y, c2[a0.x].y
                mul r1.x, r3.y, c3[a0.x].y
                mad r1.z, r1.y, c1[a0.x].y, -r1.x
                mad r1.x, r1.y, c1[a0.x].y, r1.x
                add r1.x, r1.x, r1.x
                mul r3.x, r1.x, c0[a0.x].z
                add r1.x, r1.z, r1.z
                mul r0.y, r1.x, c1[a0.x].z
                mul r1.x, r2.y, c3[a0.x].y
                mad r1.z, c2[a0.x].y, r1.y, r1.x
                mad r1.x, c2[a0.x].y, r1.y, -r1.x
                add r1.x, r1.x, r1.x
                mul r4.x, r1.x, c0[a0.x].z
                add r5.x, r1.z, r1.z
                mul r0.z, r5.x, c2[a0.x].z
                mov r0.w, c0[a0.x].x
                dp4 r0.x, v0, r0
                mul r0.w, c0[a0.x].y, c0[a0.x].y
                mad r1.x, c2[a0.x].y, c2[a0.x].y, r0.w
                mad r0.w, c1[a0.x].y, c1[a0.x].y, r0.w
                mad r5.z, r0.w, -c250.x, c250.y
                mad r0.w, r1.x, -c250.x, c250.y
                mul r3.y, r0.w, c1[a0.x].z
                mul r0.w, r1.y, c3[a0.x].y
                mad r1.x, r2.y, c2[a0.x].y, -r0.w
                mad r0.w, r2.y, c2[a0.x].y, r0.w
                add r0.w, r0.w, r0.w
                mul r4.y, r0.w, c1[a0.x].z
                add r5.y, r1.x, r1.x
                mul r3.z, r5.y, c2[a0.x].z
                mov oT1.xyz, r5
                mul r4.z, r5.z, c2[a0.x].z
                mov r3.w, c1[a0.x].x
                dp4 r0.y, v0, r3
                mov r4.w, c2[a0.x].x
                dp4 r0.z, v0, r4
                add r1.xyz, r0, -c247
                dp3 r0.w, r1, c244
                mad r0.xyz, r0.w, c246, r0
                mov r0.w, v0.w
                dp4 oPos.z, r0, c238
                dp4 r1.x, r0, c236
                dp4 r1.y, r0, c237
                dp4 r0.x, r0, c239
                mad oPos.xy, c245, r0.x, r1
                mul r0.y, r0.x, c243.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c250.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c240.x
                mad r0.x, r0.x, r1.x, c241.x
                add r0.x, -r0.x, -c248.z
                max r0.x, r0.x, c250.w
                min r0.x, r0.x, -c248.z
                mad oT2.x, c242.x, -r0.x, r0.x
                mov oT3.x, c0[a0.x].w
                mov oT3.y, c1[a0.x].w
                mov oT3.z, c2[a0.x].w
                mov oT3.w, c3[a0.x].w
            
            // approximately 95 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float SewerHax;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   BaseAmbient  c1       1
            //   SewerHax     c2       1
            //
            
                preshader
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
                mul c2.x, c2.x, c2.x
            
            // approximately 5 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D BaseSampler;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c3       1
            //   BaseAmbient  c4       1
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c5, 1, 0.00999999978, 0.600000024, 0.300000012
                def c6, -0.00390625, 0.75, 0, 1
                def c7, 0.5, 0, 0, 0
                dcl t0.xy
                dcl t1.xyz
                dcl t2.x
                dcl t3
                dcl t4.x
                dcl_2d s0
                texld r0, t0, s0
                mad r1, t3.w, r0.w, c6.x
                texkill r1
                abs r0.y, t1.z
                mul r1.xyz, r0.y, c0
                add_sat r2.xyz, t4.x, c4
                dp3_sat r1.w, t1, c5.x
                mad r2.xyz, r1.w, c0, r2
                mad r1.xyz, r1, c5.z, r2
                add r1.w, t1.z, c5.y
                cmp r1.xyz, r1.w, r2, r1
                abs r1.w, t1.x
                mul r2.xyz, r1.w, c0
                mad r2.xyz, r2, c5.w, r1
                add r1.w, t1.x, c5.y
                cmp_sat r1.xyz, r1.w, r1, r2
                mul r2.xyz, t4.x, c1
                mad r1.xyz, r1, c3, r2
                lrp r2.xyz, t2.x, c5.x, r1
                add r2.w, -r0.x, c6.y
                mul r0.w, r0.w, t3.w
                cmp r2.w, r2.w, c6.z, c6.w
                cmp r1.xyz, -c2.x, r2, r2.w
                mul r0.xyz, r1, c7.x
                mov oC0, r0
            
            // approximately 25 instruction slots used (1 texture, 24 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //
            
                preshader
                mul r0.x, c1.x, c1.x
                neg r1.x, r0.x
                lt c242.x, r1.x, r0.x
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c241.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c240.x, r0.x, r1.x
            
            // approximately 10 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float4x4 InstanceData[59];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     236
            //   Matrices_WorldViewProjection c236     4
            //   Fog_Density                  c243     1
            //   Eye                          c244     1
            //   TexelOffset                  c245     1
            //   EyeSign                      c246     1
            //   LevelCenter                  c247     1
            //
            
                vs_2_0
                def c248, 4, 2, -1, 0.5
                def c249, 0.5, 0.25, 0.125, 0.0625
                def c250, 2, 1, 1.44269502, 0
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord1 v2
                slt r0.x, v2.x, -v2.x
                frc r0.y, v2.x
                add r0.z, -r0.y, v2.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0.x, r0.x, c248.x
                mova a0.x, r0.x
                frc r0.x, c3[a0.x].z
                add r0.y, -r0.x, c3[a0.x].z
                slt r0.x, -r0.x, r0.x
                slt r0.z, c3[a0.x].z, -c3[a0.x].z
                mad r0.x, r0.z, r0.x, r0.y
                mul r0, r0.x, c249
                abs r1, r0
                sge r0, r0, -r0
                frc r1, r1
                lrp r2, r0, r1, -r1
                mad r0.x, r2.x, c248.y, c248.z
                sge r0.yzw, r2, c248.w
                add r0.yz, r0.xzww, r0.y
                slt r0.yz, -r0, r0
                mul r0.x, r0.x, r0.x
                sge oT4.x, -r0.x, r0.x
                mov r1.yz, c0[a0.x]
                lrp r2.x, r0.y, r1.z, -c248.z
                mul oT0.x, r2.x, v1.x
                mov r2.yz, c1[a0.x]
                lrp r1.x, r0.z, r2.z, -c248.z
                mul oT0.y, r1.x, v1.y
                mul r0.x, c2[a0.x].y, c2[a0.x].y
                mad r0.x, c1[a0.x].y, c1[a0.x].y, r0.x
                mad r0.x, r0.x, -c250.x, c250.y
                mul r0.x, r0.x, c0[a0.x].z
                mov r3.y, c2[a0.x].y
                mul r1.x, r3.y, c3[a0.x].y
                mad r1.z, r1.y, c1[a0.x].y, -r1.x
                mad r1.x, r1.y, c1[a0.x].y, r1.x
                add r1.x, r1.x, r1.x
                mul r3.x, r1.x, c0[a0.x].z
                add r1.x, r1.z, r1.z
                mul r0.y, r1.x, c1[a0.x].z
                mul r1.x, r2.y, c3[a0.x].y
                mad r1.z, c2[a0.x].y, r1.y, r1.x
                mad r1.x, c2[a0.x].y, r1.y, -r1.x
                add r1.x, r1.x, r1.x
                mul r4.x, r1.x, c0[a0.x].z
                add r5.x, r1.z, r1.z
                mul r0.z, r5.x, c2[a0.x].z
                mov r0.w, c0[a0.x].x
                dp4 r0.x, v0, r0
                mul r0.w, c0[a0.x].y, c0[a0.x].y
                mad r1.x, c2[a0.x].y, c2[a0.x].y, r0.w
                mad r0.w, c1[a0.x].y, c1[a0.x].y, r0.w
                mad r5.z, r0.w, -c250.x, c250.y
                mad r0.w, r1.x, -c250.x, c250.y
                mul r3.y, r0.w, c1[a0.x].z
                mul r0.w, r1.y, c3[a0.x].y
                mad r1.x, r2.y, c2[a0.x].y, -r0.w
                mad r0.w, r2.y, c2[a0.x].y, r0.w
                add r0.w, r0.w, r0.w
                mul r4.y, r0.w, c1[a0.x].z
                add r5.y, r1.x, r1.x
                mul r3.z, r5.y, c2[a0.x].z
                mov oT1.xyz, r5
                mul r4.z, r5.z, c2[a0.x].z
                mov r3.w, c1[a0.x].x
                dp4 r0.y, v0, r3
                mov r4.w, c2[a0.x].x
                dp4 r0.z, v0, r4
                add r1.xyz, r0, -c247
                dp3 r0.w, r1, c244
                mad r0.xyz, r0.w, c246, r0
                mov r0.w, v0.w
                dp4 oPos.z, r0, c238
                dp4 r1.x, r0, c236
                dp4 r1.y, r0, c237
                dp4 r0.x, r0, c239
                mad oPos.xy, c245, r0.x, r1
                mul r0.y, r0.x, c243.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c250.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c240.x
                mad r0.x, r0.x, r1.x, c241.x
                add r0.x, -r0.x, -c248.z
                max r0.x, r0.x, c250.w
                min r0.x, r0.x, -c248.z
                mad oT2.x, c242.x, -r0.x, r0.x
                mov oT3.x, c0[a0.x].w
                mov oT3.y, c1[a0.x].w
                mov oT3.z, c2[a0.x].w
                mov oT3.w, c3[a0.x].w
            
            // approximately 95 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float3 Fog_Color;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Color    c0       1
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c1, -0.00390625, 0, 0, 0
                dcl t0.xy
                dcl t2.x
                dcl t3
                dcl_2d s0
                texld r0, t0, s0
                mad r1, t3.w, r0.w, c1.x
                texkill r1
                mul r1.xyz, r0, t3
                mad r0.xyz, r0, -t3, c0
                mul r2.w, r0.w, t3.w
                mad r2.xyz, t2.x, r0, r1
                mov oC0, r2
            
            // approximately 8 instruction slots used (1 texture, 7 arithmetic)
            };
    }
}

