// InstancedDotEffect
// 10D2DCA87CBA95704DA5676D0049E03CEC15582FD44B342E0F487665254336B1

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float EightShapeStep;
            //   float Material_Opacity;
            //   float Theta;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c0       1
            //   Theta            c1       1
            //   EightShapeStep   c2       1
            //
            
                preshader
                mul c229.x, c1.x, (0.100000001)
                mul c230.x, c2.x, (1.33333337)
                mov c231.x, c0.x
            
            // approximately 3 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float DistanceFactor;
            //   float EightShapeStep;
            //   float ImmobilityFactor;
            //   float4 InstanceData[225];
            //   float3 Material_Diffuse;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //   float Theta;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     225
            //   Matrices_WorldViewProjection c225     4
            //   TexelOffset                  c232     1
            //   Material_Diffuse             c233     1
            //   Theta                        c234     1
            //   EightShapeStep               c235     1
            //   DistanceFactor               c236     1
            //   ImmobilityFactor             c237     1
            //
            
                vs_2_0
                def c238, 6, 1, 12, -6
                def c239, -1, -2, -3, -4
                def c240, -0.408248305, 0.816496611, 0.408248305, 0.349999994
                def c241, 0.333333343, 0.5, 0.200000003, 1
                def c242, 0.159154937, 0.5, 6.28318548, -3.14159274
                def c243, 0.707106769, 0, 0.577350259, -0.577350259
                def c244, 1, 0, -1, 0.333333343
                def c245, -1.55009923e-006, -2.17013894e-005, 0.00260416674, 0.00026041668
                def c246, -0.020833334, -0.125, 1, 0.5
                dcl_position v0
                dcl_color v1
                dcl_texcoord v2
                slt r0.x, v2.x, -v2.x
                frc r0.y, v2.x
                add r0.z, -r0.y, v2.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mova a0.x, r0.x
                mov r0.w, c0[a0.x].w
                add r0.x, r0.w, c234.x
                mad r0.x, r0.x, c242.x, c242.y
                frc r0.x, r0.x
                mad r0.x, r0.x, c242.z, c242.w
                sincos r1.xy, r0.x, c245, c246
                mul r2, r1.yxxx, c244.xyyx
                mul r1, r1.xxxy, c244.xyyz
                dp4 r0.x, v0, r1
                dp4 r1.x, v0, r2
                add r1.x, r1.x, c238.y
                mad r1.x, r1.x, c241.x, c241.y
                mul r1.x, r1.x, c244.w
                mov r0.yz, v0
                mul r0.xyz, r0, r1.x
                add r1.x, r0.w, c230.x
                mad r1.x, r1.x, c242.x, c242.y
                frc r1.x, r1.x
                mad r1.x, r1.x, c242.z, c242.w
                sincos r2.y, r1.x, c245, c246
                mad r1.x, r2.y, c241.z, c241.w
                mov r1.y, c238.y
                mad r1.x, r1.x, c236.x, -r1.y
                mad r1.x, c237.x, r1.x, r1.y
                mul r0.xyz, r0, r1.x
                dp3 r1.x, r0.xzyw, c243.xxyw
                dp3 r1.y, r0, c243.zzww
                dp3 r1.z, r0, c240
                add r0.xyz, r1, c0[a0.x]
                add r1.x, r0.w, c235.x
                add r0.w, r0.w, c229.x
                add r0.w, r0.w, v1.x
                mad r1.x, r1.x, c242.x, c242.y
                frc r1.x, r1.x
                mad r1.x, r1.x, c242.z, c242.w
                sincos r2.xy, r1.x, c245, c246
                mul r1, r2.yyxx, c244.yxxy
                add r1.xyz, r1.zwww, r1.xyxw
                mad r1.xyz, r1, c237.x, r0
                mov r1.w, c238.y
                dp4 oPos.z, r1, c227
                dp4 r0.x, r1, c225
                dp4 r0.y, r1, c226
                dp4 r0.z, r1, c228
                mad oPos.xy, c232, r0.z, r0
                mov oPos.w, r0.z
                mul r0.x, r0.w, c238.x
                frc r0.y, r0.x
                add r0.x, -r0.y, r0.x
                mul r0.y, r0.x, c238.x
                sge r0.y, r0.y, -r0.y
                mad r0.y, r0.y, c238.z, c238.w
                rcp r0.z, r0.y
                mul r0.z, r0.z, r0.x
                mad r0.x, r0.w, c238.x, -r0.x
                frc r0.z, r0.z
                mul r0.y, r0.z, r0.y
                frc r0.z, r0.y
                add r0.w, r0.y, -r0.z
                slt r0.y, r0.y, -r0.y
                slt r0.z, -r0.z, r0.z
                mad r0.y, r0.y, r0.z, r0.w
                add r1, r0.y, c239
                mul r0.y, r0.y, r0.y
                sge r0.y, -r0.y, r0.y
                mul r1, r1, r1
                sge r1, -r1, r1
                add r0.z, -r0.x, c238.y
                mad r0.x, r0.x, -v1.y, c238.y
                mul r2.x, r0.x, v1.z
                mad r0.x, r0.z, -v1.y, c238.y
                mul r0.x, r0.x, v1.z
                mov r2.w, r0.x
                mov r0.z, v1.z
                mov r2.y, v1.z
                lrp r3.xz, r1.w, r0, r2.yyxw
                add r0.x, -v1.y, c238.y
                mul r3.y, r0.x, v1.z
                mov r2.z, r3.y
                lrp r0.xzw, r1.z, r2.zyxy, r3.xyyz
                lrp r3.xyz, r1.y, r2.zyww, r0.xzww
                lrp r0.xzw, r1.x, r2.xyyz, r3.xyyz
                lrp r1.xyz, r0.y, r2.ywzw, r0.xzww
                mul r0.xyz, r1, c233
                mul oT0.xyz, r0, c240.w
                mov oT0.w, c231.x
            
            // approximately 113 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                dcl t0
                mov oC0, t0
            
            // approximately 1 instruction slot used
            };
    }
}

