// InstancedBlackHoleEffect
// 114B5D3E88D90F7E4DD43E17063685643CB380F20ED4982A0F9F479C67763477

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Body
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 InstanceData[60];
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     240
            //   Matrices_WorldViewProjection c240     4
            //   TexelOffset                  c244     1
            //
            
                vs_2_0
                def c245, 4, 0, 1, 0
                dcl_position v0
                dcl_texcoord v1
                frc r0.x, v1.x
                add r0.x, -r0.x, v1.x
                mul r0.x, r0.x, c245.x
                mova a0.x, r0.x
                mov r0.yz, c245
                mad r1, c0[a0.x].x, r0.yyyz, r0.zyyy
                dp4 r1.x, v0, r1
                mad r2, c1[a0.x].x, r0.yyyz, r0.yzyy
                dp4 r1.y, v0, r2
                mad r0, c2[a0.x].x, r0.yyyz, r0.yyzy
                dp4 r1.z, v0, r0
                mov r1.w, v0.w
                dp4 oPos.z, r1, c242
                dp4 r0.x, r1, c240
                dp4 r0.y, r1, c241
                dp4 r0.z, r1, c243
                mad oPos.xy, c244, r0.z, r0
                mov oPos.w, r0.z
                mov oT0.xy, c245.y
                mov oT1.x, c0[a0.x].y
                mov oT1.y, c1[a0.x].y
                mov oT1.z, c2[a0.x].y
                mov oT2.x, v1.x
            
            // approximately 23 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float IsTextureEnabled;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   IsTextureEnabled c0       1
            //
            
                preshader
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                mov c0.x, r0.x
                cmp c1.x, r1.x, (0), (1)
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c2, -0.00390625, 1, 0, 0
                dcl t0.xy
                dcl t1.xyz
                dcl_2d s0
                texld r0, t0, s0
                add r1.w, r0.w, c2.x
                mul r1, r1.w, c1.x
                texkill r1
                mul r0.xyz, r0, t1
                mov r1.xyz, t1
                mov r1.w, c2.y
                cmp r0, -c0.x, r1, r0
                mov oC0, r0
            
            // approximately 9 instruction slots used (1 texture, 8 arithmetic)
            };
    }
    pass Fringe
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 InstanceData[60];
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     240
            //   Matrices_WorldViewProjection c240     4
            //   TexelOffset                  c244     1
            //
            
                vs_2_0
                def c245, 4, 1, 0, 0
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord1 v2
                mad r0.xyz, v1.xyxw, c245.yyzw, c245.zzyw
                frc r0.w, v2.x
                add r0.w, -r0.w, v2.x
                mul r0.w, r0.w, c245.x
                mova a0.x, r0.w
                mov r1.yz, c245
                mul r2.xyz, r1.yzyw, c0[a0.x].wwzw
                dp3 oT0.x, r0, r2
                mov r0.xy, v1
                mov r0.z, c1[a0.x].z
                mad r2.xyz, c1[a0.x].w, r1.zyzw, r1.zzyw
                dp3 oT0.y, r0, r2
                mad r0, c0[a0.x].wwwx, r1.zzzy, r1.yzzz
                dp4 r0.x, v0, r0
                mad r2, c1[a0.x].wwwx, r1.zzzy, r1.zyzz
                dp4 r0.y, v0, r2
                mad r1, c2[a0.x].x, r1.zzzy, r1.zzyz
                dp4 r0.z, v0, r1
                mov r0.w, v0.w
                dp4 oPos.z, r0, c242
                dp4 r1.x, r0, c240
                dp4 r1.y, r0, c241
                dp4 r0.x, r0, c243
                mad oPos.xy, c244, r0.x, r1
                mov oPos.w, r0.x
                mov oT1.x, c0[a0.x].y
                mov oT1.y, c1[a0.x].y
                mov oT1.z, c2[a0.x].y
                mov oT2.x, v2.x
            
            // approximately 29 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float IsTextureEnabled;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   IsTextureEnabled c0       1
            //
            
                preshader
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                mov c0.x, r0.x
                cmp c1.x, r1.x, (0), (1)
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c2, -0.00390625, 1, 0, 0
                dcl t0.xy
                dcl t1.xyz
                dcl_2d s0
                texld r0, t0, s0
                add r1.w, r0.w, c2.x
                mul r1, r1.w, c1.x
                texkill r1
                mul r0.xyz, r0, t1
                mov r1.xyz, t1
                mov r1.w, c2.y
                cmp r0, -c0.x, r1, r0
                mov oC0, r0
            
            // approximately 9 instruction slots used (1 texture, 8 arithmetic)
            };
    }
}

