// InstancedArtObjectEffect
// F83086F4868F72E7C5F94C135921BE80C1209885934393B253BDD15E14EE6D06

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //
            
                preshader
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c245.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c244.x, r0.x, r1.x
            
            // approximately 7 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float4x4 InstanceData[60];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     240
            //   Matrices_WorldViewProjection c240     4
            //   Fog_Density                  c246     1
            //   Eye                          c247     1
            //   TexelOffset                  c248     1
            //   EyeSign                      c249     1
            //   LevelCenter                  c250     1
            //
            
                vs_2_0
                def c251, 4, 2, 1, 1.44269502
                def c252, 0.5, -2, 1, -0.5
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord1 v3
                slt r0.x, v3.x, -v3.x
                frc r0.y, v3.x
                add r0.z, -r0.y, v3.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0.x, r0.x, c251.x
                mova a0.x, r0.x
                mov r0.z, c2[a0.x].z
                mul r0.x, r0.z, c3[a0.x].z
                mov r1.z, c1[a0.x].z
                mad r0.y, c0[a0.x].z, r1.z, r0.x
                mad r0.x, c0[a0.x].z, r1.z, -r0.x
                add r2.y, r0.x, r0.x
                add r3.x, r0.y, r0.y
                mov r4.z, c0[a0.x].z
                mul r0.x, r4.z, c3[a0.x].z
                mad r0.y, c1[a0.x].z, r0.z, -r0.x
                mad r0.x, c1[a0.x].z, r0.z, r0.x
                add r4.y, r0.x, r0.x
                add r3.z, r0.y, r0.y
                mul r0.xy, c0[a0.x].zwzw, c0[a0.x].zwzw
                mad r0.w, c2[a0.x].z, c2[a0.x].z, r0.x
                mad r3.y, r0.w, -c251.y, c251.z
                dp3 oT0.y, v1, r3
                mul r5.x, r3.x, c0[a0.x].y
                mul r5.z, r3.z, c2[a0.x].y
                mul r5.y, r3.y, c1[a0.x].y
                mul r1.xy, c2[a0.x].zwzw, c2[a0.x].zwzw
                mad r0.w, c1[a0.x].z, c1[a0.x].z, r1.x
                slt r1.x, -r1.y, r1.y
                mad r2.x, r0.w, -c251.y, c251.z
                mul r3.x, r2.x, c0[a0.x].y
                mul r0.w, r1.z, c3[a0.x].z
                mad r1.y, r0.z, c0[a0.x].z, r0.w
                mad r0.z, r0.z, c0[a0.x].z, -r0.w
                add r4.x, r0.z, r0.z
                add r2.z, r1.y, r1.y
                mul r3.z, r2.z, c2[a0.x].y
                dp3 r2.x, v1, r2
                mul r3.y, r2.y, c1[a0.x].y
                mov r3.w, c0[a0.x].x
                dp4 r3.x, v0, r3
                mad r0.x, c1[a0.x].z, c1[a0.x].z, r0.x
                mad r4.z, r0.x, -c251.y, c251.z
                mul r6.z, r4.z, c2[a0.x].y
                dp3 r2.z, v1, r4
                mul r6.x, r4.x, c0[a0.x].y
                mul r6.y, r4.y, c1[a0.x].y
                mov r6.w, c2[a0.x].x
                dp4 r3.z, v0, r6
                mov r5.w, c1[a0.x].x
                dp4 r3.y, v0, r5
                add r0.xzw, r3.xyyz, -c250.xyyz
                dp3 r0.x, r0.xzww, c247
                mad r3.xyz, r0.x, c249, r3
                mov r3.w, v0.w
                dp4 oPos.z, r3, c242
                dp4 r4.x, r3, c240
                dp4 r4.y, r3, c241
                dp4 r0.x, r3, c243
                mad oPos.xy, c248, r0.x, r4
                mul r0.z, r0.x, c246.x
                mov oPos.w, r0.x
                mul r0.x, r0.z, r0.z
                mul r0.x, r0.x, r0.z
                mul r0.x, r0.x, c251.w
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r3.x, c244.x
                mad r0.x, r0.x, r3.x, c245.x
                add oT1.x, -r0.x, c251.z
                mul r0.x, c1[a0.x].w, c1[a0.x].w
                slt r0.xy, -r0, r0
                slt r0.zw, c252.x, r2.xyzx
                mul r0.xy, r0.wzzw, r0
                mad r0.y, r0.y, c252.y, c252.z
                lrp r1.y, r0.x, -c251.z, r0.y
                slt r0.xy, r2.zxzw, c252.w
                mov oT0.xz, r2
                mul r0.x, r0.x, r1.x
                lrp r2.x, r0.x, -c251.z, r1.y
                add r0.x, -r2.x, -c251.z
                mul r0.zw, c3[a0.x].xywy, c3[a0.x].xywy
                mov oT4.x, c3[a0.x].x
                slt r0.z, -r0.z, r0.z
                slt oT5.x, -r0.w, r0.w
                mul r0.y, r0.y, r0.z
                mad oT3.x, r0.y, r0.x, r2.x
                mov oT2.xy, v2
            
            // approximately 89 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   BaseAmbient  c1       1
            //
            
                preshader
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D CubemapSampler;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name           Reg   Size
            //   -------------- ----- ----
            //   DiffuseLight   c2       1
            //   BaseAmbient    c3       1
            //   CubemapSampler s0       1
            //
            
                ps_2_0
                def c4, -0.00390625, 1, 0.00999999978, 0.600000024
                def c5, 0.300000012, 0.5, 0, 0
                dcl t0.xyz
                dcl t1.x
                dcl t2.xy
                dcl t3.x
                dcl t4.x
                dcl_2d s0
                mov r0, t3.x
                add r1, t4.x, c4.x
                texkill r0
                texkill r1
                texld r0, t2, s0
                abs r0.x, t0.z
                mul r0.xyz, r0.x, c0
                dp3_sat r1.x, t0, c4.y
                add_sat r1.yzw, r0.w, c3.wzyx
                mul r2.xyz, r0.w, c1
                mad r1.xyz, r1.x, c0, r1.wzyx
                mad r0.xyz, r0, c4.w, r1
                add r0.w, t0.z, c4.z
                cmp r0.xyz, r0.w, r1, r0
                abs r0.w, t0.x
                mul r1.xyz, r0.w, c0
                mad r1.xyz, r1, c5.x, r0
                add r0.w, t0.x, c4.z
                cmp_sat r0.xyz, r0.w, r0, r1
                mad r0.xyz, r0, c2, r2
                lrp r1.xyz, t1.x, c4.y, r0
                mul r0.xyz, r1, c5.y
                mov r0.w, t4.x
                mov oC0, r0
            
            // approximately 24 instruction slots used (1 texture, 23 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //
            
                preshader
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c245.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c244.x, r0.x, r1.x
            
            // approximately 7 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float4x4 InstanceData[60];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     240
            //   Matrices_WorldViewProjection c240     4
            //   Fog_Density                  c246     1
            //   Eye                          c247     1
            //   TexelOffset                  c248     1
            //   EyeSign                      c249     1
            //   LevelCenter                  c250     1
            //
            
                vs_2_0
                def c251, 4, 2, 1, 1.44269502
                def c252, 0.5, -2, 1, -0.5
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord1 v3
                slt r0.x, v3.x, -v3.x
                frc r0.y, v3.x
                add r0.z, -r0.y, v3.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0.x, r0.x, c251.x
                mova a0.x, r0.x
                mov r0.z, c2[a0.x].z
                mul r0.x, r0.z, c3[a0.x].z
                mov r1.z, c1[a0.x].z
                mad r0.y, c0[a0.x].z, r1.z, r0.x
                mad r0.x, c0[a0.x].z, r1.z, -r0.x
                add r2.y, r0.x, r0.x
                add r3.x, r0.y, r0.y
                mov r4.z, c0[a0.x].z
                mul r0.x, r4.z, c3[a0.x].z
                mad r0.y, c1[a0.x].z, r0.z, -r0.x
                mad r0.x, c1[a0.x].z, r0.z, r0.x
                add r4.y, r0.x, r0.x
                add r3.z, r0.y, r0.y
                mul r0.xy, c0[a0.x].zwzw, c0[a0.x].zwzw
                mad r0.w, c2[a0.x].z, c2[a0.x].z, r0.x
                mad r3.y, r0.w, -c251.y, c251.z
                dp3 oT0.y, v1, r3
                mul r5.x, r3.x, c0[a0.x].y
                mul r5.z, r3.z, c2[a0.x].y
                mul r5.y, r3.y, c1[a0.x].y
                mul r1.xy, c2[a0.x].zwzw, c2[a0.x].zwzw
                mad r0.w, c1[a0.x].z, c1[a0.x].z, r1.x
                slt r1.x, -r1.y, r1.y
                mad r2.x, r0.w, -c251.y, c251.z
                mul r3.x, r2.x, c0[a0.x].y
                mul r0.w, r1.z, c3[a0.x].z
                mad r1.y, r0.z, c0[a0.x].z, r0.w
                mad r0.z, r0.z, c0[a0.x].z, -r0.w
                add r4.x, r0.z, r0.z
                add r2.z, r1.y, r1.y
                mul r3.z, r2.z, c2[a0.x].y
                dp3 r2.x, v1, r2
                mul r3.y, r2.y, c1[a0.x].y
                mov r3.w, c0[a0.x].x
                dp4 r3.x, v0, r3
                mad r0.x, c1[a0.x].z, c1[a0.x].z, r0.x
                mad r4.z, r0.x, -c251.y, c251.z
                mul r6.z, r4.z, c2[a0.x].y
                dp3 r2.z, v1, r4
                mul r6.x, r4.x, c0[a0.x].y
                mul r6.y, r4.y, c1[a0.x].y
                mov r6.w, c2[a0.x].x
                dp4 r3.z, v0, r6
                mov r5.w, c1[a0.x].x
                dp4 r3.y, v0, r5
                add r0.xzw, r3.xyyz, -c250.xyyz
                dp3 r0.x, r0.xzww, c247
                mad r3.xyz, r0.x, c249, r3
                mov r3.w, v0.w
                dp4 oPos.z, r3, c242
                dp4 r4.x, r3, c240
                dp4 r4.y, r3, c241
                dp4 r0.x, r3, c243
                mad oPos.xy, c248, r0.x, r4
                mul r0.z, r0.x, c246.x
                mov oPos.w, r0.x
                mul r0.x, r0.z, r0.z
                mul r0.x, r0.x, r0.z
                mul r0.x, r0.x, c251.w
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r3.x, c244.x
                mad r0.x, r0.x, r3.x, c245.x
                add oT1.x, -r0.x, c251.z
                mul r0.x, c1[a0.x].w, c1[a0.x].w
                slt r0.xy, -r0, r0
                slt r0.zw, c252.x, r2.xyzx
                mul r0.xy, r0.wzzw, r0
                mad r0.y, r0.y, c252.y, c252.z
                lrp r1.y, r0.x, -c251.z, r0.y
                slt r0.xy, r2.zxzw, c252.w
                mov oT0.xz, r2
                mul r0.x, r0.x, r1.x
                lrp r2.x, r0.x, -c251.z, r1.y
                add r0.x, -r2.x, -c251.z
                mul r0.zw, c3[a0.x].xywy, c3[a0.x].xywy
                mov oT4.x, c3[a0.x].x
                slt r0.z, -r0.z, r0.z
                slt oT5.x, -r0.w, r0.w
                mul r0.y, r0.y, r0.z
                mad oT3.x, r0.y, r0.x, r2.x
                mov oT2.xy, v2
            
            // approximately 89 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   BaseAmbient  c1       1
            //
            
                preshader
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D CubemapSampler;
            //   float3 DiffuseLight;
            //   float3 Fog_Color;
            //
            //
            // Registers:
            //
            //   Name           Reg   Size
            //   -------------- ----- ----
            //   DiffuseLight   c2       1
            //   Fog_Color      c3       1
            //   BaseAmbient    c4       1
            //   CubemapSampler s0       1
            //
            
                ps_2_0
                def c5, -0.00390625, 1, 0.00999999978, 0.600000024
                def c6, 0.300000012, 0, 0, 0
                dcl t0.xyz
                dcl t1.x
                dcl t2.xy
                dcl t3.x
                dcl t4.x
                dcl t5.x
                dcl_2d s0
                mov r0, t3.x
                add r1, t4.x, c5.x
                texkill r0
                texkill r1
                texld r0, t2, s0
                abs r1.x, t0.x
                mul r1.xyz, r1.x, c0
                add r1.w, t0.z, c5.z
                abs r2.w, t0.z
                mul r2.xyz, r2.w, c0
                dp3_sat r2.w, t0, c5.y
                add_sat r3.xyz, r0.w, c4
                mad r3.xyz, r2.w, c0, r3
                mad r2.xyz, r2, c5.w, r3
                cmp r2.xyz, r1.w, r3, r2
                mad r1.xyz, r1, c6.x, r2
                add r1.w, t0.x, c5.z
                cmp_sat r1.xyz, r1.w, r2, r1
                mul r2.xyz, r0.w, c1
                mad r1.xyz, r1, c2, r2
                mul r1.xyz, r0, r1
                cmp r0.xyz, -t5.x, r0, r1
                lrp r1.xyz, t1.x, c3, r0
                mov r1.w, t4.x
                mov oC0, r1
            
            // approximately 25 instruction slots used (1 texture, 24 arithmetic)
            };
    }
}

