// InstancedMapEffect
// 6F8EC2821399F1EFF02414B6C388A3D83713560588F2C5BDA0AEB0153A36DA3A

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Billboard;
            //   float4x4 CameraRotation;
            //
            //
            // Registers:
            //
            //   Name           Reg   Size
            //   -------------- ----- ----
            //   CameraRotation c0       4
            //   Billboard      c4       1
            //
            
                preshader
                add r0, c0, (-1, -0, -0, -0)
                mul r1.x, c4.x, c4.x
                neg r2.x, r1.x
                lt r3.x, r2.x, r1.x
                mul r1, r3.x, r0
                add r0, r1, (1, 0, 0, 0)
                mov c232.x, r0.x
                add r1.x, c1.x, (-0)
                add r1.y, c1.y, (-1)
                add r1.z, c1.z, (-0)
                add r1.w, c1.w, (-0)
                mul r2, r3.x, r1
                add r1.x, r2.x, (0)
                add r1.y, r2.y, (1)
                add r1.z, r2.z, (0)
                add r1.w, r2.w, (0)
                mov c233.x, r1.x
                add r2.x, c2.x, (-0)
                add r2.y, c2.y, (-0)
                add r2.z, c2.z, (-1)
                add r2.w, c2.w, (-0)
                mul r4, r3.x, r2
                add r2.x, r4.x, (0)
                add r2.y, r4.y, (0)
                add r2.z, r4.z, (1)
                add r2.w, r4.w, (0)
                mov c234.x, r2.x
                add r4.x, c3.x, (-0)
                add r4.y, c3.y, (-0)
                add r4.z, c3.z, (-0)
                add r4.w, c3.w, (-1)
                mul r5, r3.x, r4
                mov c245.x, r3.x
                add r3.x, r5.x, (0)
                add r3.y, r5.y, (0)
                add r3.z, r5.z, (0)
                add r3.w, r5.w, (1)
                mov c235.x, r3.x
                mov c236.x, r0.y
                mov c237.x, r1.y
                mov c238.x, r2.y
                mov c239.x, r3.y
                mov c240.x, r0.z
                mov c244.x, r0.w
                mov c241.x, r1.z
                mov c244.y, r1.w
                mov c242.x, r2.z
                mov c244.z, r2.w
                mov c243.x, r3.z
                mov c244.w, r3.w
            
            // approximately 50 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 InstanceData[58];
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     232
            //   Matrices_WorldViewProjection c246     4
            //   TexelOffset                  c250     1
            //
            
                vs_2_0
                def c251, 4, 0, 1, 0
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord1 v2
                slt r0.x, v2.x, -v2.x
                frc r0.y, v2.x
                add r0.z, -r0.y, v2.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0.x, r0.x, c251.x
                mova a0.x, r0.x
                mov r0.xzw, c0[a0.x]
                mul r1.y, r0.z, c232.x
                mul r1.z, r0.z, c233.x
                mul r1.w, r0.z, c234.x
                mul r1.x, r0.z, c235.x
                mad r2, r0.x, c251.yyyz, c251.zyyy
                dp4 r3.x, r1.yzwx, r2.xzzw
                mov r4.xzw, c1[a0.x]
                mul r5.x, r4.z, c236.x
                mul r5.y, r4.z, c237.x
                mul r5.z, r4.z, c238.x
                mul r5.w, r4.z, c239.x
                dp4 r3.y, r5, r2.xzzw
                mov r0.xz, c2[a0.x]
                mul r6.x, r0.z, c240.x
                mul r6.y, r0.z, c241.x
                mul r6.z, r0.z, c242.x
                mul r6.w, r0.z, c243.x
                dp4 r3.z, r6, r2.xzzw
                dp4 r3.w, c244, r2
                dp4 r2.x, v0, r3
                mad r3, r4.x, c251.yyyz, c251.yzyy
                dp4 r7.x, r1.zywx, r3.yzzw
                dp4 r7.y, r5.yxzw, r3.yzzw
                dp4 r7.z, r6.yxzw, r3.yzzw
                dp4 r7.w, c244, r3
                dp4 r2.y, v0, r7
                mad r3, r0.x, c251.yyyz, c251.yyzy
                dp4 r7.x, r1.yzwx, r3
                dp4 r7.y, r5, r3
                mov r1.y, r5.w
                dp4 r7.z, r6, r3
                mov r1.z, r6.w
                dp4 r7.w, c244, r3
                dp4 r2.z, v0, r7
                mov r1.w, c244.w
                dp4 r2.w, v0, r1
                dp4 oPos.z, r2, c248
                dp4 r0.x, r2, c246
                dp4 r0.y, r2, c247
                dp4 r0.z, r2, c249
                mad oPos.xy, c250, r0.z, r0
                mov oPos.w, r0.z
                mov r0.x, c0[a0.x].y
                mov r0.y, c1[a0.x].y
                mov r0.z, c2[a0.x].y
                add r1.xyz, -r0, c251.z
                mad oT0.xyz, c245.x, r1, r0
                mad oT1.x, v1.x, c2[a0.x].w, r0.w
                mad oT1.y, v1.y, c3[a0.x].w, r4.w
                mov oT0.w, c3[a0.x].y
            
            // approximately 58 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Billboard;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Billboard    c0       1
            //
            
                preshader
                mul c0.x, c0.x, c0.x
            
            // approximately 1 instruction used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c1, -0.00999999978, 1, 0, 0
                dcl t0
                dcl t1.xy
                dcl_2d s0
                add r0, t0.w, c1.x
                texkill r0
                texld r0, t1, s0
                mov r1.w, c1.y
                cmp r0, -c0.x, r1.w, r0
                mul r0, r0, t0
                mov oC0, r0
            
            // approximately 7 instruction slots used (1 texture, 6 arithmetic)
            };
    }
}

