// InvertEffect
// E94EB3BCECA416B9C2B0D70DF3DBDCBABC8A22D5441D37BADEEFFC1DF1995876

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelOffset  c0       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_texcoord v1
                mad oPos.xy, c0, v0.w, v0
                mov oT0.xy, v1
                mov oPos.zw, v0
            
            // approximately 3 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c0, 1, 0, 0, 0
                dcl t0.xy
                dcl_2d s0
                texld r0, t0, s0
                add r0.xyz, -r0, c0.x
                mov r0.w, c0.x
                mov oC0, r0
            
            // approximately 4 instruction slots used (1 texture, 3 arithmetic)
            };
    }
}

