// LightmapEffect
// 0F1710E96C68066CEB9D0F033D365109C9F0F144B91244E7DEFB8E0749B64FF5

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Shadows
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Matrices_Texture c0       2
            //   TexelOffset      c2       1
            //
            
                vs_2_0
                def c3, 1, 0, 0, 0
                dcl_position v0
                dcl_texcoord v1
                mad oPos.xy, c2, v0.w, v0
                mad r0.xyz, v1.xyxw, c3.xxyw, c3.yyxw
                dp3 oT0.x, r0, c0
                dp3 oT0.y, r0, c1
                mov oPos.zw, v0
            
            // approximately 5 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float ShadowPass;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   ShadowPass   c0       1
            //
            
                preshader
                mul c0.x, c0.x, c0.x
            
            // approximately 1 instruction used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c1, -0.5, 4, 1, 0
                dcl t0.xy
                dcl_2d s0
                texld r0, t0, s0
                add_sat r1.xyz, r0, c1.x
                add_sat r0.xyz, r0, r0
                mad r1.xyz, r1, c1.y, c1.z
                cmp r0.xyz, -c0.x, r1, r0
                mov r0.w, c1.z
                mov oC0, r0
            
            // approximately 7 instruction slots used (1 texture, 6 arithmetic)
            };
    }
}

