// LightingPostEffect
// AE3D5D93B0B2479B818BDE0123631CCB0288F7FFEE2DB8DE3641A35C67AA5D90

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Dawn
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelOffset  c0       1
            //
            
                vs_2_0
                dcl_position v0
                mad oPos.xy, c0, v0.w, v0
                mov oPos.zw, v0
            
            // approximately 2 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float DawnContribution;
            //   float3 Fog_Color;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Fog_Color        c0       1
            //   DawnContribution c1       1
            //
            
                preshader
                mul r0.xyz, c1.x, c0.xyz
                mul c0.xyz, (0.200000003, 0.200000003, 0.200000003), r0.xyz
                mov c0.w, (1)
            
            // approximately 3 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                mov oC0, c0
            
            // approximately 1 instruction slot used
            };
    }
    pass Dusk_Multiply
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelOffset  c0       1
            //
            
                vs_2_0
                dcl_position v0
                mad oPos.xy, c0, v0.w, v0
                mov oPos.zw, v0
            
            // approximately 2 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float DuskContribution;
            //   float3 Fog_Color;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Fog_Color        c0       1
            //   DuskContribution c1       1
            //
            
                preshader
                add r0.xyz, c0.xyz, c0.xyz
                add r1.xyz, (-1, -1, -1), r0.xyz
                mul r0.x, c1.x, (0.200000003)
                mul r2.xyz, r0.x, r1.xyz
                add c0.xyz, (1, 1, 1), r2.xyz
                mov c0.w, (1)
            
            // approximately 6 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                mov oC0, c0
            
            // approximately 1 instruction slot used
            };
    }
    pass Dusk_Screen
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelOffset  c0       1
            //
            
                vs_2_0
                dcl_position v0
                mad oPos.xy, c0, v0.w, v0
                mov oPos.zw, v0
            
            // approximately 2 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float DuskContribution;
            //   float3 Fog_Color;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Fog_Color        c0       1
            //   DuskContribution c1       1
            //
            
                preshader
                add r0.xyz, (-0.5, -0.5, -0.5), c0.xyz
                add r1.xyz, r0.xyz, r0.xyz
                max r0.xyz, (0, 0, 0), r1.xyz
                min r1.xyz, (1, 1, 1), r0.xyz
                mul r0.xyz, c1.x, r1.xyz
                mul c0.xyz, (0.200000003, 0.200000003, 0.200000003), r0.xyz
                mov c0.w, (1)
            
            // approximately 7 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                mov oC0, c0
            
            // approximately 1 instruction slot used
            };
    }
    pass Night
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelOffset  c0       1
            //
            
                vs_2_0
                dcl_position v0
                mad oPos.xy, c0, v0.w, v0
                mov oPos.zw, v0
            
            // approximately 2 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Fog_Color;
            //   float NightContribution;
            //
            //
            // Registers:
            //
            //   Name              Reg   Size
            //   ----------------- ----- ----
            //   Fog_Color         c0       1
            //   NightContribution c1       1
            //
            
                preshader
                neg r0.x, c0.z
                add r1.x, r0.x, c0.y
                cmp r0.x, r1.x, c0.y, c0.z
                neg r1.x, r0.x
                add r0.y, r1.x, c0.x
                cmp r1.x, r0.y, c0.x, r0.x
                rcp r0.x, r1.x
                mul r1.xyz, r0.x, c0.xyz
                add r0.xyz, (-1, -1, -1), r1.xyz
                mul r0.w, c1.x, (0.125)
                mul r1.xyz, r0.w, r0.xyz
                add c0.xyz, (1, 1, 1), r1.xyz
                mov c0.w, (1)
            
            // approximately 13 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                mov oC0, c0
            
            // approximately 1 instruction slot used
            };
    }
}

