// MapEffect
// 4FE19FCEEC9263809FBE71E54A752676CE32719076062E7B3F7605BA4FA22E8A

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c4       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_color v1
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c4, r0.z, r0
                mov oPos.w, r0.z
                mov oT0, v1
            
            // approximately 7 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   Material_Opacity c1       1
            //
            
                ps_2_0
                def c2, -0.00999999978, 0, 0, 0
                dcl t0
                mov r0.w, c1.x
                mad r0, r0.w, t0.w, c2.x
                texkill r0
                mul r0.x, t0.w, c1.x
                mul r0.w, r0.x, c1.x
                mul r0.xyz, t0, c0
                mov oC0, r0
            
            // approximately 7 instruction slots used
            };
    }
}

