// MatrixEffect
// FF3080A9952F5C24037F19E24B6EC9141060CE0376DB2DEAE2FAAC20EF86FF14

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c4       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_texcoord v1
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c4, r0.z, r0
                mov oPos.w, r0.z
                mov oT1.xy, v1
            
            // approximately 7 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Material_Diffuse;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //
            
                preshader
                mul r0.xyz, (0.75, 0.75, 0.75), c0.xyz
                add c1.xyz, (0.5, 0.5, 0.5), r0.xyz
            
            // approximately 2 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c0       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c2, -0.00390625, 0, 0, 0
                dcl t1.xy
                dcl_2d s0
                texld r0, t1, s0
                mov r1.w, c0.x
                mad r1, r1.w, r0.w, c2.x
                texkill r1
                mul r1.xyz, r0, c1
                mul r1.w, r0.w, c0.x
                mov oC0, r1
            
            // approximately 7 instruction slots used (1 texture, 6 arithmetic)
            };
    }
}

