// PlaneParticleEffect
// 7DC84D4ABFEEEFF37A79FB1C4AD9DD6BDC187243DF68E3EFF0BA6207B95FBDB5

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float4x4 InstanceData[60];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     240
            //   Matrices_WorldViewProjection c240     4
            //   Eye                          c244     1
            //   TexelOffset                  c245     1
            //   EyeSign                      c246     1
            //   LevelCenter                  c247     1
            //
            
                vs_2_0
                def c248, 4, 0.159154937, 0.5, 0
                def c249, 6.28318548, -3.14159274, 0, 1
                def c250, -1.55009923e-006, -2.17013894e-005, 0.00260416674, 0.00026041668
                def c251, -0.020833334, -0.125, 1, 0.5
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord1 v2
                slt r0.x, v2.x, -v2.x
                frc r0.y, v2.x
                add r0.z, -r0.y, v2.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0.x, r0.x, c248.x
                mova a0.x, r0.x
                mov r0.yz, c248
                mad r0.x, c3[a0.x].x, r0.y, r0.z
                frc r0.x, r0.x
                mad r0.x, r0.x, c249.x, c249.y
                sincos r1.xy, r0.x, c250, c251
                mul r0.x, -r1.y, c0[a0.x].y
                mul r2.yz, r1.xyxw, c2[a0.x].y
                mul r2.x, r1.x, c0[a0.x].y
                mov r0.y, r2.z
                mov r0.z, c2[a0.x].x
                dp3 r0.z, v0.xzww, r0
                mov r2.w, c0[a0.x].x
                dp3 r0.x, v0.xzww, r2.xyww
                mov r1.zw, c249
                mul r1, r1.zwzw, c1[a0.x].yyyx
                dp4 r0.y, v0, r1
                add r1.xyz, r0, -c247
                dp3 r0.w, r1, c244
                mad r0.xyz, r0.w, c246, r0
                mov r0.w, v0.w
                dp4 oPos.z, r0, c242
                dp4 r1.x, r0, c240
                dp4 r1.y, r0, c241
                dp4 r0.x, r0, c243
                mad oPos.xy, c245, r0.x, r1
                mov oPos.w, r0.x
                mov oT0.xy, v1
                mov oT1.x, c0[a0.x].z
                mov oT1.y, c1[a0.x].z
                mov oT1.z, c2[a0.x].z
                mov oT1.w, c3[a0.x].z
            
            // approximately 45 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Additive;
            //   float3 DiffuseLight;
            //   float Fullbright;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   Fullbright   c1       1
            //   Additive     c2       1
            //
            
                preshader
                mul c0.x, c2.x, c2.x
                neg r0.xyz, c0.xyz
                add r1.xyz, (1, 1, 1), r0.xyz
                mul r0.xyz, c1.x, r1.xyz
                add c1.xyz, r0.xyz, c0.xyz
            
            // approximately 5 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float Fullbright;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fullbright   c2       1
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c3, 1, 0.5, 0.5, 0.5
                dcl t0.xy
                dcl t1
                dcl_2d s0
                texld r0, t0, s0
                mul r0, r0, t1
                mul r0.xyz, r0, c2.x
                mov r1.w, c0.x
                cmp r1.xyz, -r1.w, c1, r0
                mov r0.x, c3.x
                cmp r1.w, -c0.x, r0.w, r0.x
                mul r0, r1, c3.wzyx
                mov oC0, r0
            
            // approximately 9 instruction slots used (1 texture, 8 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float4x4 InstanceData[60];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     240
            //   Matrices_WorldViewProjection c240     4
            //   Eye                          c244     1
            //   TexelOffset                  c245     1
            //   EyeSign                      c246     1
            //   LevelCenter                  c247     1
            //
            
                vs_2_0
                def c248, 4, 0.159154937, 0.5, 0
                def c249, 6.28318548, -3.14159274, 0, 1
                def c250, -1.55009923e-006, -2.17013894e-005, 0.00260416674, 0.00026041668
                def c251, -0.020833334, -0.125, 1, 0.5
                dcl_position v0
                dcl_texcoord v1
                dcl_texcoord1 v2
                slt r0.x, v2.x, -v2.x
                frc r0.y, v2.x
                add r0.z, -r0.y, v2.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0.x, r0.x, c248.x
                mova a0.x, r0.x
                mov r0.yz, c248
                mad r0.x, c3[a0.x].x, r0.y, r0.z
                frc r0.x, r0.x
                mad r0.x, r0.x, c249.x, c249.y
                sincos r1.xy, r0.x, c250, c251
                mul r0.x, -r1.y, c0[a0.x].y
                mul r2.yz, r1.xyxw, c2[a0.x].y
                mul r2.x, r1.x, c0[a0.x].y
                mov r0.y, r2.z
                mov r0.z, c2[a0.x].x
                dp3 r0.z, v0.xzww, r0
                mov r2.w, c0[a0.x].x
                dp3 r0.x, v0.xzww, r2.xyww
                mov r1.zw, c249
                mul r1, r1.zwzw, c1[a0.x].yyyx
                dp4 r0.y, v0, r1
                add r1.xyz, r0, -c247
                dp3 r0.w, r1, c244
                mad r0.xyz, r0.w, c246, r0
                mov r0.w, v0.w
                dp4 oPos.z, r0, c242
                dp4 r1.x, r0, c240
                dp4 r1.y, r0, c241
                dp4 r0.x, r0, c243
                mad oPos.xy, c245, r0.x, r1
                mov oPos.w, r0.x
                mov oT0.xy, v1
                mov oT1.x, c0[a0.x].z
                mov oT1.y, c1[a0.x].z
                mov oT1.z, c2[a0.x].z
                mov oT1.w, c3[a0.x].z
            
            // approximately 45 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c0, -0.00390625, 0, 0, 0
                dcl t0.xy
                dcl t1
                dcl_2d s0
                texld r0, t0, s0
                mad r1, t1.w, r0.w, c0.x
                mul r0, r0, t1
                mov oC0, r0
                texkill r1
            
            // approximately 5 instruction slots used (1 texture, 4 arithmetic)
            };
    }
}

