// PointsFromLinesEffect
// 9D7C1C7A57A5F76C011AA57BE9E305BEE55943580BB06F0CBCADF866DA6A843E

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c0       1
            //
            
                preshader
                mov c5.x, c0.x
            
            // approximately 1 instruction used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c4       1
            //
            
                vs_2_0
                def c6, 4, 0, 0, 0
                dcl_position v0
                dcl_color v1
                dp4 oPos.z, v0, c2
                dp4 oPos.w, v0, c3
                slt r0.x, -v1.w, v1.w
                slt r0.y, v1.w, -v1.w
                add r0.x, -r0.y, r0.x
                mul r0.x, r0.x, -c4.x
                mul r0.x, r0.x, c6.x
                dp4 r1.x, v0, c0
                dp4 r1.y, v0, c1
                mov r0.y, c6.y
                add oPos.xy, r0, r1
                mov oD0.xyz, v1
                mov oD0.w, c5.x
            
            // approximately 13 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                dcl v0
                mov oC0, v0
            
            // approximately 1 instruction slot used
            };
    }
}

