// ProjectedNodeEffect
// 2E32EF0C6F1391B858E068D8A1CA520A4605641726F6F3721EF96E1EB9450FDB

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 CubeOffset;
            //   float4x4 Matrices_ViewProjection;
            //
            //
            // Registers:
            //
            //   Name                    Reg   Size
            //   ----------------------- ----- ----
            //   Matrices_ViewProjection c0       4
            //   CubeOffset              c4       1
            //
            
                preshader
                mov r0.xyz, c4.xyz
                mov r0.w, (1)
                dot c8, r0, c0
                dot c8.yzwx, r0, c1
                dot c8.zwxy, r0, c2
                dot c8.wxyz, r0, c3
            
            // approximately 6 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float4x4 Matrices_WorldViewProjection;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldViewProjection   c0       4
            //   Matrices_WorldInverseTranspose c4       4
            //
            
                vs_2_0
                dcl_position v0
                dcl_normal v1
                dp3 oT0.x, v1, c4
                dp3 oT0.y, v1, c5
                dp3 oT0.z, v1, c6
                dp3 oT0.w, v1, c7
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c2
                dp4 r0.w, v0, c3
                mov oT1, r0
                mov oPos, r0
                mov oT2, c8
            
            // approximately 11 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float Complete;
            //   float Material_Opacity;
            //   float NoTexture;
            //   float2 TextureSize;
            //   float2 ViewportSize;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   BaseAmbient      c0       1
            //   Material_Opacity c1       1
            //   ViewportSize     c2       1
            //   TextureSize      c3       1
            //   NoTexture        c4       1
            //   Complete         c5       1
            //
            
                preshader
                rcp r0.x, c3.x
                rcp r0.y, c3.y
                mul c0.xy, r0.xy, c2.xy
                rcp r0.x, c2.x
                rcp r0.y, c2.y
                mul c1.xy, (0.5, 0.5), r0.xy
                mul c2.x, c4.x, c4.x
                mul c3.x, c5.x, c5.x
                max r0.x, c0.x, (0)
                min c5.x, r0.x, (1)
                neg r0.x, c0.x
                add c4.x, r0.x, (1)
                mov c6.x, c1.x
            
            // approximately 13 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float PixelsPerTrixel;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   PixelsPerTrixel c7       1
            //   BaseSampler     s0       1
            //
            
                ps_2_0
                def c8, 0.166666672, 0.5, 0.25, 1
                def c9, 1, 0.745098054, 0.141176477, 0.00999999978
                def c10, 0.600000024, 0.200000003, 0.400000006, 0.100000001
                def c11, 0.75, 0, 0, 0
                dcl t0.xyz
                dcl t1
                dcl t2
                dcl_2d s0
                add r0.w, -t0.x, c9.w
                abs r0.x, t0.x
                mul r0.x, r0.x, c4.x
                dp3_sat r0.y, t0, c8.w
                mov r1.w, c4.x
                mad r0.y, r0.y, r1.w, c5.x
                mad r0.z, r0.x, -c10.y, r0.y
                cmp r0.z, r0.w, r0.y, r0.z
                add r0.w, t0.z, c9.w
                abs r1.x, t0.z
                mul r1.x, r1.x, c4.x
                mad r0.y, r1.x, c10.x, r0.y
                cmp r0.y, r0.w, r0.z, r0.y
                mad r0.x, r0.x, c10.z, r0.y
                add r0.z, t0.x, c9.w
                cmp r0.x, r0.z, r0.y, r0.x
                abs r0.y, t0.y
                mul r0.y, r0.y, c4.x
                mad r0.y, r0.y, -c10.w, r0.x
                add r0.z, -t0.y, c9.w
                cmp_sat r0.x, r0.z, r0.x, r0.y
                pow r1.x, r0.x, c11.x
                rcp r0.x, t2.w
                mul r2.x, r0.x, t2.x
                mul r2.y, r0.x, -t2.y
                mul r0.xy, r2, c7.x
                rcp r0.z, t1.w
                mul r2.x, r0.z, t1.x
                mul r2.y, r0.z, -t1.y
                mad r0.xy, r2, c7.x, -r0
                mul r0.xy, r0, c0
                mad r0.xy, r0, c8.x, c8.y
                add r0.xy, r0, c1
                texld r0, r0, s0
                mov r0.w, c8.z
                cmp r0.xyz, -c2.x, r0, r0.w
                mul r1.yzw, r0.wzyx, c9.wzyx
                cmp r0.xyz, -c3.x, r0, r1.wzyx
                mul r0.xyz, r1.x, r0
                mov r0.w, c6.x
                mov oC0, r0
            
            // approximately 43 instruction slots used (1 texture, 42 arithmetic)
            };
    }
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 CubeOffset;
            //   float4x4 Matrices_ViewProjection;
            //
            //
            // Registers:
            //
            //   Name                    Reg   Size
            //   ----------------------- ----- ----
            //   Matrices_ViewProjection c0       4
            //   CubeOffset              c4       1
            //
            
                preshader
                mov r0.xyz, c4.xyz
                mov r0.w, (1)
                dot c8, r0, c0
                dot c8.yzwx, r0, c1
                dot c8.zwxy, r0, c2
                dot c8.wxyz, r0, c3
            
            // approximately 6 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float4x4 Matrices_WorldViewProjection;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldViewProjection   c0       4
            //   Matrices_WorldInverseTranspose c4       4
            //
            
                vs_2_0
                dcl_position v0
                dcl_normal v1
                dp3 oT0.x, v1, c4
                dp3 oT0.y, v1, c5
                dp3 oT0.z, v1, c6
                dp3 oT0.w, v1, c7
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c2
                dp4 r0.w, v0, c3
                mov oT1, r0
                mov oPos, r0
                mov oT2, c8
            
            // approximately 11 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c0       1
            //
            
                preshader
                add c0.x, c0.x, (-0.00999999978)
            
            // approximately 1 instruction used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                ps_2_0
                def c1, 0.5, 0.5, 0.5, 1
                mov r0, c0.x
                texkill r0
                mov oC0, c1
            
            // approximately 3 instruction slots used
            };
    }
}

