// ScanlineEffect
// 4C93D5D8870A4D52F2543721E17AD048345A450510250B93276564CAECC992BC

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelOffset  c0       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_texcoord v1
                mad oPos.xy, c0, v0.w, v0
                mov oT0.xy, v1
                mov oPos.zw, v0
            
            // approximately 3 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Material_Opacity;
            //   float Time;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Time             c0       1
            //   Material_Opacity c1       1
            //
            
                preshader
                add c2.x, c0.x, c0.x
                mov c3.x, c1.x
            
            // approximately 2 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float3x3 Matrices_Texture;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Matrices_Texture c0       2
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c4, -0.5, 0, 1.5, -2
                def c5, 0.0416666418, 0.5, 0.800000012, 0
                def c6, 1, 942.477844, 0.159154937, 0.25
                def c7, 0, 1, 2, -0.00138883968
                def c8, 6.28318548, -3.14159274, -2.52398507e-007, 2.47609005e-005
                dcl t0.xy
                dcl_2d s0
                add r0.xy, t0, c4.x
                dp2add r0.z, r0, r0, c4.y
                mad r0.xy, r0, -c4.w, -c4.x
                pow r1.w, r0.z, c4.z
                lrp r2.xy, r1.w, r0, t0
                mov r2.z, c6.x
                dp3 r0.x, r2, c0
                dp3 r0.y, r2, c1
                mov r1.y, c6.y
                mad r0.z, r0.y, r1.y, c2.x
                add r1.xyz, r0.z, c7
                mad r1.xyz, r1, c6.z, c6.w
                frc r1.xyz, r1
                mad r1.xyz, r1, c8.x, c8.y
                mul r1.xyz, r1, r1
                texld r0, r0, s0
                mad r2.xyz, r1, c8.z, c8.w
                mad r2.xyz, r1, r2, c7.w
                mad r2.xyz, r1, r2, c5.x
                mad r2.xyz, r1, r2, c4.x
                mad r1.xyz, r1, r2, c6.x
                mad r1.xyz, r1, c5.y, c5.z
                mul r0.xyz, r0, r1
                mov r0.w, c3.x
                mov oC0, r0
            
            // approximately 28 instruction slots used (1 texture, 27 arithmetic)
            };
    }
}

