// ScreenSpaceFisheye
// AB01A8FB53AE054E345AEEF1E5BAFA5B3699B9E7B787BEA9AD4FDEDB16693A99

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Matrices_Texture c0       2
            //   TexelOffset      c2       1
            //
            
                vs_2_0
                def c3, 1, 0, 0, 0
                dcl_position v0
                dcl_texcoord v1
                mad oPos.xy, c2, v0.w, v0
                mad r0.xyz, v1.xyxw, c3.xxyw, c3.yyxw
                dp3 oT0.x, r0, c0
                dp3 oT0.y, r0, c1
                mov oPos.zw, v0
            
            // approximately 5 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float2 Intensity;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Intensity    c0       1
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c1, -0.5, 1, 0, 0
                dcl t0.xy
                dcl_2d s0
                add r0.xy, t0, c1.x
                add r0.xy, r0, r0
                mad r0.z, r0.y, -r0.y, c1.y
                mul r0.z, r0.z, c0.y
                mul r1.x, r0.x, r0.z
                mad r0.x, r0.x, -r0.x, c1.y
                mul r0.x, r0.x, c0.x
                mul r1.y, r0.y, r0.x
                add r0.xy, -r1, t0
                texld r0, r0, s0
                mov r0.w, c1.y
                mov oC0, r0
            
            // approximately 12 instruction slots used (1 texture, 11 arithmetic)
            };
    }
}

