// SewerHaxEffect
// 794B81B88AEAFD49057C4E8CE8A7770B9BA4A0775C194B505162593EF4BC040F

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelOffset  c0       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_texcoord v1
                mad oPos.xy, c0, v0.w, v0
                mov oT0.xy, v1
                mov oPos.zw, v0
            
            // approximately 3 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c0, 0.125490203, 0.274509817, 0.192156866, 1
                def c1, 0.321568638, 0.498039216, 0.223529413, 1
                dcl t0.xy
                dcl_2d s0
                texld r0, t0, s0
                mul r0.x, r0.x, r0.x
                mov r1, c0
                cmp r0, -r0.x, r1, c1
                mov oC0, r0
            
            // approximately 5 instruction slots used (1 texture, 4 arithmetic)
            };
    }
}

