// ShimmeringPointsEffect
// 06A2B4ED26CB6EC662E30F24EBA840994F0CEF1F12B9654867AD06AF3DE4DA4C

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass P0
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_WorldViewProjection;
            //   float3 RandomSeed;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c4       1
            //   RandomSeed                   c5       1
            //
            
                vs_2_0
                def c6, 142857, 0.00249999994, 0, 4
                dcl_position v0
                dcl_color v1
                mul r0.xyz, v0, c5
                mul r0.xyz, r0, c6.x
                frc r0.xyz, r0
                mul r0.xyz, r0, c6.y
                mov r0.w, c6.z
                add r0, r0, v0
                dp4 oPos.z, r0, c2
                dp4 r1.x, r0, c0
                dp4 r1.y, r0, c1
                dp4 r0.x, r0, c3
                mad r0.yz, c4.xxyw, r0.x, r1.xxyw
                mov oPos.w, r0.x
                slt r0.x, -v1.w, v1.w
                slt r0.w, v1.w, -v1.w
                add r0.x, -r0.w, r0.x
                mul r0.x, r0.x, -c4.x
                mul r1.x, r0.x, c6.w
                mov r1.y, c6.z
                add oPos.xy, r0.yzzw, r1
                mov oT0, v1
            
            // approximately 20 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //   float Saturation;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   Material_Opacity c1       1
            //   Saturation       c2       1
            //
            
                ps_2_0
                def c3, -1, 1, 0, 0
                dcl t0
                mov r0.xy, c3
                mad r1.xyz, t0, c0, r0.x
                mad r0.xyz, c2.x, r1, r0.y
                mul r0.w, t0.w, c1.x
                mov oC0, r0
            
            // approximately 5 instruction slots used
            };
    }
}

