// SkyEffect
// 2BA9F71DF6B17F7E30630C8079588F10747B57CD4E4EC15878B11359EA6F62B7

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass P0
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 CenterPosition;
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_World;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Matrices_World               c4       2
            //   Matrices_Texture             c6       2
            //   CenterPosition               c8       1
            //   TexelOffset                  c9       1
            //
            
                vs_2_0
                def c10, 1, 0, 0.0119047621, 0
                dcl_position v0
                dcl_texcoord v1
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c9, r0.z, r0
                mov oPos.w, r0.z
                mad r0.xyz, v1.xyxw, c10.xxyw, c10.yyxw
                dp3 oT0.x, r0, c6
                dp3 oT0.y, r0, c7
                dp4 r0.x, v0, c5
                add r0.x, r0.x, -c8.y
                abs r0.x, r0.x
                mul r0.x, r0.x, c10.z
                mul r0.x, r0.x, r0.x
                min r0.x, r0.x, c10.x
                add oT1.x, -r0.x, c10.x
            
            // approximately 16 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c0       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                dcl t0.xy
                dcl t1.x
                dcl_2d s0
                texld r0, t0, s0
                mul r0.x, r0.w, c0.x
                mul r0, r0.x, t1.x
                mov oC0, r0
            
            // approximately 4 instruction slots used (1 texture, 3 arithmetic)
            };
    }
}

