// SplitCollectorEffect
// 52B68E022A1F74CD272C86E9C5E13418C9FA76F29BA56F2D0B33A593FFFD1B0C

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float4x4 Matrices_ViewProjection;
            //   float4x4 Matrices_World;
            //   float Offset;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                    Reg   Size
            //   ----------------------- ----- ----
            //   Matrices_World          c0       4
            //   Matrices_ViewProjection c4       4
            //   TexelOffset             c8       1
            //   Offset                  c9       1
            //
            
                vs_2_0
                def c10, 2, -1, 1, 0
                dcl_position v0
                dcl_color v1
                mad r0.xyz, v1, c10.x, c10.y
                dp4 r1.x, v0, c0
                dp4 r1.y, v0, c1
                dp4 r1.z, v0, c2
                mad r0.xyz, c9.x, r0, r1
                dp4 r0.w, v0, c3
                dp4 oPos.z, r0, c6
                dp4 r1.x, r0, c4
                dp4 r1.y, r0, c5
                dp4 r0.x, r0, c7
                mad oPos.xy, c8, r0.x, r1
                mov oPos.w, r0.x
                mad oT0, v1, c10.xxxz, c10.yyyw
            
            // approximately 13 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //   float VaryingOpacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   Material_Opacity c1       1
            //   VaryingOpacity   c2       1
            //
            
                preshader
                mul r0.x, c1.x, c2.x
                max r1.x, r0.x, (0)
                min c2.x, r1.x, (1)
                mul r0.x, c1.x, (0.125)
                mul r1.x, r0.x, c2.x
                max r1.y, r0.x, (0)
                min c0.x, r1.y, (1)
                max r0.x, r1.x, (0)
                min c1.x, r0.x, (1)
                mov c3.xyz, c0.xyz
            
            // approximately 10 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c4       1
            //
            
                ps_2_0
                def c5, -0.25, -0.5, -0.75, 0
                dcl t0
                add r0.w, t0.w, c5.z
                mov r0.x, c4.x
                cmp r0.x, r0.w, r0.x, c0.x
                add r0.y, t0.w, c5.y
                cmp r0.x, r0.y, r0.x, c1.x
                add r0.y, t0.w, c5.x
                cmp r0.w, r0.y, r0.x, c2.x
                mov r0.xyz, c3
                mov oC0, r0
            
            // approximately 9 instruction slots used
            };
    }
}

