// StarsEffect
// F39B3FC8087BC6BC9181EC58F48FD5E12D25A2F67721965490F15F44C930E46C

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass P0
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   Matrices_Texture             c4       2
            //   TexelOffset                  c6       1
            //
            
                vs_2_0
                def c7, 1, 0, 0.0500000007, 16
                dcl_position v0
                dcl_texcoord v1
                dp4 oPos.z, v0, c2
                dp4 r0.x, v0, c0
                dp4 r0.y, v0, c1
                dp4 r0.z, v0, c3
                mad oPos.xy, c6, r0.z, r0
                mov oPos.w, r0.z
                mad r0.xyz, v1.xyxw, c7.xxyw, c7.yyxw
                dp3 oT0.x, r0, c4
                dp3 oT0.y, r0, c5
                add r0.x, v0.y, c7.z
                mul oT1.x, r0.x, c7.w
            
            // approximately 11 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c0       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c1, 1, 0, 0, 0
                dcl t0.xy
                dcl t1.x
                dcl_2d s0
                texld r0, t0, s0
                mul r0.xyz, r0, c0.x
                mul r0.xyz, r0, t1.x
                mov r0.w, c1.x
                mov oC0, r0
            
            // approximately 5 instruction slots used (1 texture, 4 arithmetic)
            };
    }
}

