// StaticPlaneEffect
// 0169CD775004E50AE43B2C740F06597A2D2B10CEE1405B4516E823A807704655

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //
            
                preshader
                mul r0.x, c1.x, c1.x
                neg r1.x, r0.x
                lt c14.x, r1.x, r0.x
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c13.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c12.x, r0.x, r1.x
            
            // approximately 10 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_ViewProjection;
            //   float4x4 Matrices_World;
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldInverseTranspose c0       4
            //   Matrices_World                 c4       4
            //   Matrices_ViewProjection        c8       4
            //   Matrices_Texture               c15      2
            //   Fog_Density                    c17      1
            //   Eye                            c18      1
            //   TexelOffset                    c19      1
            //   EyeSign                        c20      1
            //   LevelCenter                    c21      1
            //
            
                vs_2_0
                def c22, 1, 0, 1.44269502, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dp4 r0.x, v0, c4
                dp4 r0.y, v0, c5
                dp4 r0.z, v0, c6
                add r1.xyz, r0, -c21
                dp3 r0.w, r1, c18
                mad r0.xyz, r0.w, c20, r0
                dp4 r0.w, v0, c7
                dp4 oPos.z, r0, c10
                dp4 r1.x, r0, c8
                dp4 r1.y, r0, c9
                dp4 r0.x, r0, c11
                mad oPos.xy, c19, r0.x, r1
                mad r0.yzw, v2.xxyx, c22.xxxy, c22.xyyx
                dp3 oT0.x, r0.yzww, c15
                dp3 oT0.y, r0.yzww, c16
                dp3 oT1.x, v1, c0
                dp3 oT1.y, v1, c1
                dp3 oT1.z, v1, c2
                dp3 oT1.w, v1, c3
                mul r0.y, r0.x, c17.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c22.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c12.x
                mad r0.x, r0.x, r1.x, c13.x
                add r0.x, -r0.x, c22.x
                max r0.x, r0.x, c22.y
                min r0.x, r0.x, c22.x
                mad oT2.x, c14.x, -r0.x, r0.x
            
            // approximately 32 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float Fullbright;
            //   float SewerHax;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   DiffuseLight    c0       1
            //   BaseAmbient     c1       1
            //   Fullbright      c2       1
            //   AlphaIsEmissive c3       1
            //   SewerHax        c4       1
            //
            
                preshader
                mul r0.x, c2.x, c2.x
                neg r1.x, r0.x
                cmp c1.x, r1.x, (0), (1)
                neg r0.xyz, c1.xyz
                add c2.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c3.xyz, (1, 1, 1), r0.xyz
                mul r0.x, c4.x, c4.x
                neg r1.x, r0.x
                mul r0.x, c3.x, c3.x
                neg r1.y, r0.x
                mov c0.x, r0.x
                cmp r0.x, r1.y, (-1), (-0)
                cmp c5.x, r1.x, (0), r0.x
            
            // approximately 14 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D BaseSampler;
            //   float3 DiffuseLight;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   DiffuseLight     c6       1
            //   BaseAmbient      c7       1
            //   Material_Opacity c8       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                def c9, 1, 0.00999999978, 0.600000024, 0.300000012
                def c10, 0.75, 0, 1, 0.5
                dcl t0.xy
                dcl t1.xyz
                dcl t2.x
                dcl_2d s0
                texld r0, t0, s0
                abs r0.y, t1.z
                mul r1.xyz, r0.y, c2
                mul r1.w, r0.w, c8.x
                mul r1.w, r1.w, c1.x
                cmp r1.w, -c0.x, r1.w, r0.w
                add r0.x, -r0.x, c10.x
                cmp r0.x, r0.x, c10.y, c10.z
                add_sat r0.yzw, r1.w, c7.wzyx
                mul r2.xyz, r1.w, c3
                dp3_sat r1.w, t1, c9.x
                mad r0.yzw, r1.w, c2.wzyx, r0
                mad r1.xyz, r1, c9.z, r0.wzyx
                add r1.w, t1.z, c9.y
                cmp r0.yzw, r1.w, r0, r1.wzyx
                abs r2.w, t1.x
                mul r1.xyz, r2.w, c2
                mad r1.xyz, r1, c9.w, r0.wzyx
                add r1.w, t1.x, c9.y
                cmp_sat r0.yzw, r1.w, r0, r1.wzyx
                mad r0.yzw, r0, c6.wzyx, r2.wzyx
                lrp r1.xyz, t2.x, c9.x, r0.wzyx
                cmp r0.xyz, c5.x, r1, r0.x
                mul r0.xyz, r0, c10.w
                mov r0.w, c9.x
                mov oC0, r0
            
            // approximately 26 instruction slots used (1 texture, 25 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Fog_Type;
            //   float IgnoreFog;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Fog_Type     c0       1
            //   IgnoreFog    c1       1
            //
            
                preshader
                mul r0.x, c1.x, c1.x
                neg r1.x, r0.x
                lt c14.x, r1.x, r0.x
                mul r0.x, c0.x, c0.x
                neg r1.x, r0.x
                ge c13.x, r1.x, r0.x
                add r0.x, c0.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c12.x, r0.x, r1.x
            
            // approximately 10 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float3 LevelCenter;
            //   float3x3 Matrices_Texture;
            //   float4x4 Matrices_ViewProjection;
            //   float4x4 Matrices_World;
            //   float4x4 Matrices_WorldInverseTranspose;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                           Reg   Size
            //   ------------------------------ ----- ----
            //   Matrices_WorldInverseTranspose c0       4
            //   Matrices_World                 c4       4
            //   Matrices_ViewProjection        c8       4
            //   Matrices_Texture               c15      2
            //   Fog_Density                    c17      1
            //   Eye                            c18      1
            //   TexelOffset                    c19      1
            //   EyeSign                        c20      1
            //   LevelCenter                    c21      1
            //
            
                vs_2_0
                def c22, 1, 0, 1.44269502, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dp4 r0.x, v0, c4
                dp4 r0.y, v0, c5
                dp4 r0.z, v0, c6
                add r1.xyz, r0, -c21
                dp3 r0.w, r1, c18
                mad r0.xyz, r0.w, c20, r0
                dp4 r0.w, v0, c7
                dp4 oPos.z, r0, c10
                dp4 r1.x, r0, c8
                dp4 r1.y, r0, c9
                dp4 r0.x, r0, c11
                mad oPos.xy, c19, r0.x, r1
                mad r0.yzw, v2.xxyx, c22.xxxy, c22.xyyx
                dp3 oT0.x, r0.yzww, c15
                dp3 oT0.y, r0.yzww, c16
                dp3 oT1.x, v1, c0
                dp3 oT1.y, v1, c1
                dp3 oT1.z, v1, c2
                dp3 oT1.w, v1, c3
                mul r0.y, r0.x, c17.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c22.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c12.x
                mad r0.x, r0.x, r1.x, c13.x
                add r0.x, -r0.x, c22.x
                max r0.x, r0.x, c22.y
                min r0.x, r0.x, c22.x
                mad oT2.x, c14.x, -r0.x, r0.x
            
            // approximately 32 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float AlphaIsEmissive;
            //
            //
            // Registers:
            //
            //   Name            Reg   Size
            //   --------------- ----- ----
            //   AlphaIsEmissive c0       1
            //
            
                preshader
                mul c3.x, c0.x, c0.x
            
            // approximately 1 instruction used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //   float3 Fog_Color;
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Fog_Color        c0       1
            //   Material_Diffuse c1       1
            //   Material_Opacity c2       1
            //   BaseSampler      s0       1
            //
            
                ps_2_0
                dcl t0.xy
                dcl t2.x
                dcl_2d s0
                texld r0, t0, s0
                mul r1.xyz, r0, c1
                mov r2.xyz, c1
                mad r0.xyz, r0, -r2, c0
                mul r0.w, r0.w, c2.x
                mov r1.w, c2.x
                cmp r2.w, -c3.x, r0.w, r1.w
                mad r2.xyz, t2.x, r0, r1
                mov oC0, r2
            
            // approximately 9 instruction slots used (1 texture, 8 arithmetic)
            };
    }
}

