// TrileEffect
// C2D791A5F8E6FB5DDC0436E7391C04BB122CBA71828FE6528FBADD9BA48A3AC8

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Blink;
            //   float Fog_Type;
            //   float Shiny;
            //   float TiltTwoAxis;
            //   float Time;
            //   float Unstable;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Time         c0       1
            //   Fog_Type     c1       1
            //   Blink        c2       1
            //   Unstable     c3       1
            //   TiltTwoAxis  c4       1
            //   Shiny        c5       1
            //
            
                preshader
                mul r0.x, c4.x, c4.x
                neg r1.x, r0.x
                lt c203.x, r1.x, r0.x
                mul r0.x, c5.x, c5.x
                neg r1.x, r0.x
                lt r2.x, r1.x, r0.x
                mul r0.x, c3.x, c3.x
                neg r1.x, r0.x
                lt r2.y, r1.x, r0.x
                mul r0.x, r2.y, (0.400000006)
                mul r0.z, r2.y, (0)
                mov c201.x, r2.y
                neg r1.x, r0.x
                neg r1.z, r0.z
                add r0.y, r1.x, (0.349999994)
                add r0.w, r1.z, (0.850000024)
                mul r1.x, r0.y, r2.x
                mul r1.z, r0.w, r2.x
                add c213.x, r0.x, r1.x
                add c213.z, r0.z, r1.z
                mul r0.x, c1.x, c1.x
                neg r1.x, r0.x
                ge c209.x, r1.x, r0.x
                add r0.x, c1.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c208.x, r0.x, r1.x
                mul r0.x, c2.x, c2.x
                neg r1.x, r0.x
                lt c212.x, r1.x, r0.x
                mul c211.x, c0.x, (0.100000001)
                mov c213.y, (0)
            
            // approximately 32 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float4 InstanceData[200];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //   float Time;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     200
            //   Matrices_WorldViewProjection c214     4
            //   Time                         c218     1
            //   Fog_Density                  c219     1
            //   Eye                          c220     1
            //   TexelOffset                  c221     1
            //   EyeSign                      c222     1
            //   LevelCenter                  c223     1
            //
            
                vs_2_0
                def c224, 0.577350259, 1.44269502, 0.75, 0
                def c225, 4.36681223, -0.397887349, -0.795774698, 0.5
                def c226, 6.28318548, -3.14159274, 0.159154937, 0.5
                def c227, 0.125, 1, 0, -1
                def c228, 0.707106769, 0.408248305, -0.707106769, -0.816496611
                def c229, -1.55009923e-006, -2.17013894e-005, 0.00260416674, 0.00026041668
                def c230, -0.020833334, -0.125, 1, 0.5
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord1 v3
                slt r0.x, v3.x, -v3.x
                frc r0.y, v3.x
                add r0.z, -r0.y, v3.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mov r1.xw, c225
                mad r0.y, r0.x, r1.x, c218.x
                mul r0.z, r0.y, c225.y
                mad r0.y, r0.y, c225.z, c225.w
                frc r0.y, r0.y
                mad r0.y, r0.y, c226.x, c226.y
                sincos r2.xy, r0.y, c229, c230
                frc r0.y, r0.z
                slt r0.y, r0.y, c227.x
                mul r3.z, -r2.y, r2.x
                mul r3.xy, r2, r2
                mov r4.xy, r3.zyzw
                mov r4.z, r2.x
                mova a0.x, r0.x
                mad r0.x, r0.x, r1.x, c211.x
                frc r0.x, r0.x
                slt r0.x, r0.x, c224.z
                add r0.x, r0.x, c227.w
                mov r1.yz, c227
                mad oT3.x, c212.x, r0.x, r1.y
                mov r0.zw, c226
                mad r0.x, c0[a0.x].w, r0.z, r0.w
                frc r0.x, r0.x
                mad r0.x, r0.x, c226.x, c226.y
                sincos r5.xy, r0.x, c229, c230
                mul r6.xyz, r5.xxyw, c227.yzyw
                mov r6.w, -r6.z
                add r0.xzw, r4.xyyz, -r6.wyyx
                mul r0.xzw, r0, r0.y
                mul r0.xzw, r0, c201.x
                mad r0.xzw, r6.zyyx, c227.wyyy, r0
                dp3 r1.x, v0, c227.y
                mul r1.x, r1.x, c225.w
                max r1.x, r1.x, c227.z
                min r1.x, r1.x, c227.y
                max r2.z, r2.y, c227.z
                mul r4.x, r1.x, r2.z
                mad r2.zw, r5.xyyx, -c227.y, r2.xyyx
                mul r7.yz, r0.y, r2.xzww
                mov r4.yz, c227.z
                mov r7.x, c227.z
                add r4.xyz, r4, r7
                mad r4.xyz, c201.x, r4, r6.yzxw
                mul r7, r4.zyyz, c228.xyzy
                mad r8.xy, r4.zyzw, c228.zxzw, r7.ywzw
                add r7.xy, r7.ywzw, r7.xzzw
                mul r2.zw, r4.xyyz, c228.w
                mov oT4.w, r4.x
                mov r8.w, r2.w
                mov r7.z, r2.z
                mov r8.z, r7.y
                lrp r4.xyz, c203.x, r8.zwyw, r0.xzww
                mov r7.w, r8.x
                add r4.w, r1.w, c0[a0.x].z
                dp4 r8.z, v0, r4
                dp3 oT0.z, v1, r4
                mov r3.w, r2.y
                add r0.xz, r2.yyxw, -c227.zyyw
                mul r2.xy, r0.xzzw, r0.y
                mad r0.xzw, r5.xyxy, -c227.yyzy, r3
                mul r0.xyz, r0.xzww, r0.y
                mad r0.xyz, c201.x, r0, r6
                lrp r3.xyz, c203.x, r7.xzww, r0
                add r3.w, r1.w, c0[a0.x].x
                add r0.w, r1.w, c0[a0.x].y
                dp4 r8.x, v0, r3
                dp3 oT0.x, v1, r3
                mov r2.z, c227.z
                mad r1.xyz, c201.x, r2, r1.zyzw
                add r2.xyz, -r1, c224.x
                mad r0.xyz, c203.x, r2, r1
                dp4 r8.y, v0, r0
                dp3 oT0.y, v1, r0
                add r0.xyz, r8, -c223
                dp3 r0.x, r0, c220
                mad r0.xyz, r0.x, c222, r8
                mov r0.w, v0.w
                dp4 oPos.z, r0, c216
                dp4 r1.x, r0, c214
                dp4 r1.y, r0, c215
                dp4 r0.x, r0, c217
                mad oPos.xy, c221, r0.x, r1
                mul r0.y, r0.x, c219.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c224.y
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c208.x
                mad r0.x, r0.x, r1.x, c209.x
                add r0.x, -r0.x, c227.y
                max r0.x, r0.x, c227.z
                min oT1.x, r0.x, c227.y
                mov oT2.xy, v2
                mov oT4.xyz, c213
            
            // approximately 115 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   BaseAmbient  c1       1
            //
            
                preshader
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AtlasSampler;
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c2       1
            //   BaseAmbient  c3       1
            //   AtlasSampler s0       1
            //
            
                ps_2_0
                def c4, 1, 0.00999999978, 0.600000024, 0.300000012
                def c5, 0.5, 0, 0, 0
                dcl t0.xyz
                dcl t1.x
                dcl t2.xy
                dcl t3.x
                dcl t4.xy
                dcl_2d s0
                texld r0, t2, s0
                abs r0.x, t0.z
                mul r0.xyz, r0.x, c0
                add r1.w, r0.w, t4.x
                add r0.w, r0.w, t4.y
                mul r1.xyz, r0.w, c1
                mul r1.xyz, r1, t3.x
                add_sat r2.xyz, r1.w, c3
                dp3_sat r0.w, t0, c4.x
                mad r2.xyz, r0.w, c0, r2
                mad r0.xyz, r0, c4.z, r2
                add r0.w, t0.z, c4.y
                cmp r0.xyz, r0.w, r2, r0
                abs r0.w, t0.x
                mul r2.xyz, r0.w, c0
                mad r2.xyz, r2, c4.w, r0
                add r0.w, t0.x, c4.y
                cmp_sat r0.xyz, r0.w, r0, r2
                mad r0.xyz, r0, c2, r1
                lrp r1.xyz, t1.x, c4.x, r0
                mul r0.xyz, r1, c5.x
                mov r0.w, c4.x
                mov oC0, r0
            
            // approximately 23 instruction slots used (1 texture, 22 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Blink;
            //   float Fog_Type;
            //   float Shiny;
            //   float TiltTwoAxis;
            //   float Time;
            //   float Unstable;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Time         c0       1
            //   Fog_Type     c1       1
            //   Blink        c2       1
            //   Unstable     c3       1
            //   TiltTwoAxis  c4       1
            //   Shiny        c5       1
            //
            
                preshader
                mul r0.x, c4.x, c4.x
                neg r1.x, r0.x
                lt c203.x, r1.x, r0.x
                mul r0.x, c5.x, c5.x
                neg r1.x, r0.x
                lt r2.x, r1.x, r0.x
                mul r0.x, c3.x, c3.x
                neg r1.x, r0.x
                lt r2.y, r1.x, r0.x
                mul r0.x, r2.y, (0.400000006)
                mul r0.z, r2.y, (0)
                mov c201.x, r2.y
                neg r1.x, r0.x
                neg r1.z, r0.z
                add r0.y, r1.x, (0.349999994)
                add r0.w, r1.z, (0.850000024)
                mul r1.x, r0.y, r2.x
                mul r1.z, r0.w, r2.x
                add c213.x, r0.x, r1.x
                add c213.z, r0.z, r1.z
                mul r0.x, c1.x, c1.x
                neg r1.x, r0.x
                ge c209.x, r1.x, r0.x
                add r0.x, c1.x, (-2)
                mul r1.x, r0.x, r0.x
                neg r0.x, r1.x
                ge c208.x, r0.x, r1.x
                mul r0.x, c2.x, c2.x
                neg r1.x, r0.x
                lt c212.x, r1.x, r0.x
                mul c211.x, c0.x, (0.100000001)
                mov c213.y, (0)
            
            // approximately 32 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float Fog_Density;
            //   float4 InstanceData[200];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //   float Time;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     200
            //   Matrices_WorldViewProjection c214     4
            //   Time                         c218     1
            //   Fog_Density                  c219     1
            //   Eye                          c220     1
            //   TexelOffset                  c221     1
            //   EyeSign                      c222     1
            //   LevelCenter                  c223     1
            //
            
                vs_2_0
                def c224, 0.577350259, 1.44269502, 0.75, 0
                def c225, 4.36681223, -0.397887349, -0.795774698, 0.5
                def c226, 6.28318548, -3.14159274, 0.159154937, 0.5
                def c227, 0.125, 1, 0, -1
                def c228, 0.707106769, 0.408248305, -0.707106769, -0.816496611
                def c229, -1.55009923e-006, -2.17013894e-005, 0.00260416674, 0.00026041668
                def c230, -0.020833334, -0.125, 1, 0.5
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord1 v3
                slt r0.x, v3.x, -v3.x
                frc r0.y, v3.x
                add r0.z, -r0.y, v3.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mov r1.xw, c225
                mad r0.y, r0.x, r1.x, c218.x
                mul r0.z, r0.y, c225.y
                mad r0.y, r0.y, c225.z, c225.w
                frc r0.y, r0.y
                mad r0.y, r0.y, c226.x, c226.y
                sincos r2.xy, r0.y, c229, c230
                frc r0.y, r0.z
                slt r0.y, r0.y, c227.x
                mul r3.z, -r2.y, r2.x
                mul r3.xy, r2, r2
                mov r4.xy, r3.zyzw
                mov r4.z, r2.x
                mova a0.x, r0.x
                mad r0.x, r0.x, r1.x, c211.x
                frc r0.x, r0.x
                slt r0.x, r0.x, c224.z
                add r0.x, r0.x, c227.w
                mov r1.yz, c227
                mad oT3.x, c212.x, r0.x, r1.y
                mov r0.zw, c226
                mad r0.x, c0[a0.x].w, r0.z, r0.w
                frc r0.x, r0.x
                mad r0.x, r0.x, c226.x, c226.y
                sincos r5.xy, r0.x, c229, c230
                mul r6.xyz, r5.xxyw, c227.yzyw
                mov r6.w, -r6.z
                add r0.xzw, r4.xyyz, -r6.wyyx
                mul r0.xzw, r0, r0.y
                mul r0.xzw, r0, c201.x
                mad r0.xzw, r6.zyyx, c227.wyyy, r0
                dp3 r1.x, v0, c227.y
                mul r1.x, r1.x, c225.w
                max r1.x, r1.x, c227.z
                min r1.x, r1.x, c227.y
                max r2.z, r2.y, c227.z
                mul r4.x, r1.x, r2.z
                mad r2.zw, r5.xyyx, -c227.y, r2.xyyx
                mul r7.yz, r0.y, r2.xzww
                mov r4.yz, c227.z
                mov r7.x, c227.z
                add r4.xyz, r4, r7
                mad r4.xyz, c201.x, r4, r6.yzxw
                mul r7, r4.zyyz, c228.xyzy
                mad r8.xy, r4.zyzw, c228.zxzw, r7.ywzw
                add r7.xy, r7.ywzw, r7.xzzw
                mul r2.zw, r4.xyyz, c228.w
                mov oT4.w, r4.x
                mov r8.w, r2.w
                mov r7.z, r2.z
                mov r8.z, r7.y
                lrp r4.xyz, c203.x, r8.zwyw, r0.xzww
                mov r7.w, r8.x
                add r4.w, r1.w, c0[a0.x].z
                dp4 r8.z, v0, r4
                dp3 oT0.z, v1, r4
                mov r3.w, r2.y
                add r0.xz, r2.yyxw, -c227.zyyw
                mul r2.xy, r0.xzzw, r0.y
                mad r0.xzw, r5.xyxy, -c227.yyzy, r3
                mul r0.xyz, r0.xzww, r0.y
                mad r0.xyz, c201.x, r0, r6
                lrp r3.xyz, c203.x, r7.xzww, r0
                add r3.w, r1.w, c0[a0.x].x
                add r0.w, r1.w, c0[a0.x].y
                dp4 r8.x, v0, r3
                dp3 oT0.x, v1, r3
                mov r2.z, c227.z
                mad r1.xyz, c201.x, r2, r1.zyzw
                add r2.xyz, -r1, c224.x
                mad r0.xyz, c203.x, r2, r1
                dp4 r8.y, v0, r0
                dp3 oT0.y, v1, r0
                add r0.xyz, r8, -c223
                dp3 r0.x, r0, c220
                mad r0.xyz, r0.x, c222, r8
                mov r0.w, v0.w
                dp4 oPos.z, r0, c216
                dp4 r1.x, r0, c214
                dp4 r1.y, r0, c215
                dp4 r0.x, r0, c217
                mad oPos.xy, c221, r0.x, r1
                mul r0.y, r0.x, c219.x
                mov oPos.w, r0.x
                mul r0.x, r0.y, r0.y
                mul r0.x, r0.x, r0.y
                mul r0.x, r0.x, c224.y
                exp r0.x, r0.x
                rcp r0.x, r0.x
                mov r1.x, c208.x
                mad r0.x, r0.x, r1.x, c209.x
                add r0.x, -r0.x, c227.y
                max r0.x, r0.x, c227.z
                min oT1.x, r0.x, c227.y
                mov oT2.xy, v2
                mov oT4.xyz, c213
            
            // approximately 115 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float3 Eye;
            //   float ForceShading;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   DiffuseLight     c0       1
            //   BaseAmbient      c1       1
            //   Eye              c2       1
            //   Material_Opacity c3       1
            //   ForceShading     c4       1
            //
            
                preshader
                add c0.xyz, c2.xyz, (-0, -0.25, -0)
                mul c1.x, c4.x, c4.x
                neg r0.xyz, c1.xyz
                add c2.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c3.xyz, (1, 1, 1), r0.xyz
                mov c4.x, c3.x
            
            // approximately 7 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D AtlasSampler;
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //   float3 Fog_Color;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c5       1
            //   Fog_Color    c6       1
            //   BaseAmbient  c7       1
            //   AtlasSampler s0       1
            //
            
                ps_2_0
                def c8, 1, 0.00999999978, 0.600000024, 0.300000012
                dcl t0.xyz
                dcl t1.x
                dcl t2.xy
                dcl t3.x
                dcl t4
                dcl_2d s0
                texld r0, t2, s0
                abs r1.w, t0.x
                mul r1.xyz, r1.w, c2
                abs r1.w, t0.z
                mul r2.xyz, r1.w, c2
                dp3_sat r1.w, t0, c8.x
                add r2.w, r0.w, t4.x
                add_sat r3.xyz, r2.w, c7
                mad r3.xyz, r1.w, c2, r3
                mad r2.xyz, r2, c8.z, r3
                add r1.w, t0.z, c8.y
                cmp r2.xyz, r1.w, r3, r2
                mad r1.xyz, r1, c8.w, r2
                add r1.w, t0.x, c8.y
                cmp_sat r1.xyz, r1.w, r2, r1
                add r0.w, r0.w, t4.y
                add r0.xyz, r0, t4.w
                mul r2.xyz, r0.w, c3
                mul r2.xyz, r2, t3.x
                mad r1.xyz, r1, c5, r2
                dp3 r0.w, c0, t0
                mul r0.w, r0.w, r0.w
                mul r0.w, r0.w, r0.w
                mul_sat r0.w, r0.w, r0.w
                mad r0.xyz, r0.w, t4.z, r0
                mul r1.xyz, r1, r0
                cmp r0.xyz, -c1.x, r0, r1
                lrp r1.xyz, t1.x, c6, r0
                mov r1.w, c4.x
                mov oC0, r1
            
            // approximately 30 instruction slots used (1 texture, 29 arithmetic)
            };
    }
}

