// TrixelParticleEffect
// E073D61F2F55F5F1EF95ED05963B56B22572E4CA5C74E9D88594B1535E943DD3

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Pre
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float4x4 InstanceData[60];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     240
            //   Matrices_WorldViewProjection c240     4
            //   Eye                          c244     1
            //   TexelOffset                  c245     1
            //   EyeSign                      c246     1
            //   LevelCenter                  c247     1
            //
            
                vs_2_0
                def c248, 4, 1, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord1 v3
                slt r0.x, v3.x, -v3.x
                frc r0.y, v3.x
                add r0.z, -r0.y, v3.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0.x, r0.x, c248.x
                mova a0.x, r0.x
                mov r0.xyw, c0[a0.x]
                mad oT0.x, v2.x, r0.w, c2[a0.x].w
                mov r1.xyw, c1[a0.x]
                mad oT0.y, v2.y, r1.w, c3[a0.x].w
                mul r0, r0.yyyx, c248.yzzy
                dp4 r0.x, v0, r0
                mul r1, r1.yyyx, c248.zyzy
                dp4 r0.y, v0, r1
                mov r1.yz, c248
                mul r1, r1.zzyy, c2[a0.x].yyyx
                dp4 r0.z, v0, r1
                add r1.xyz, r0, -c247
                dp3 r0.w, r1, c244
                mad r0.xyz, r0.w, c246, r0
                mov r0.w, v0.w
                dp4 oPos.z, r0, c242
                dp4 r1.x, r0, c240
                dp4 r1.y, r0, c241
                dp4 r0.x, r0, c243
                mad oPos.xy, c245, r0.x, r1
                mov oPos.w, r0.x
                mov oT1.x, c0[a0.x].z
                mov oT1.y, c1[a0.x].z
                mov oT1.z, c2[a0.x].z
                mov oT1.w, c3[a0.x].z
                mov oT2.xyz, v1
            
            // approximately 33 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c0       1
            //   BaseAmbient  c1       1
            //
            
                preshader
                neg r0.xyz, c1.xyz
                add c0.xyz, (1, 1, 1), r0.xyz
                neg r0.xyz, c0.xyz
                add c1.xyz, (1, 1, 1), r0.xyz
            
            // approximately 4 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 BaseAmbient;
            //   sampler2D BaseSampler;
            //   float3 DiffuseLight;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   DiffuseLight c2       1
            //   BaseAmbient  c3       1
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c4, -1, 1, 0.00999999978, 0.600000024
                def c5, 0.300000012, 0.5, 0, 0
                dcl t0.xy
                dcl t1
                dcl t2.xyz
                dcl_2d s0
                texld r0, t0, s0
                abs r0.x, t2.z
                mul r0.xyz, r0.x, c0
                dp3_sat r1.w, t2, c4.y
                add_sat r1.xyz, t1, c4.x
                add_sat r2.xyz, r1.x, c3
                mul r1.xyz, r1, c1
                mad r2.xyz, r1.w, c0, r2
                mad r0.xyz, r0, c4.w, r2
                add r1.w, t2.z, c4.z
                cmp r0.xyz, r1.w, r2, r0
                abs r1.w, t2.x
                mul r2.xyz, r1.w, c0
                mad r2.xyz, r2, c5.x, r0
                add r1.w, t2.x, c4.z
                cmp_sat r0.xyz, r1.w, r0, r2
                mul r0.xyz, r0, c2
                mad r1.xyz, r0, c5.y, r1
                add r0.x, -r0.w, c4.y
                mul r1.w, r0.x, t1.w
                mov oC0, r1
            
            // approximately 21 instruction slots used (1 texture, 20 arithmetic)
            };
    }
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Eye;
            //   float3 EyeSign;
            //   float4x4 InstanceData[60];
            //   float3 LevelCenter;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   InstanceData                 c0     240
            //   Matrices_WorldViewProjection c240     4
            //   Eye                          c244     1
            //   TexelOffset                  c245     1
            //   EyeSign                      c246     1
            //   LevelCenter                  c247     1
            //
            
                vs_2_0
                def c248, 4, 1, 0, 0
                dcl_position v0
                dcl_normal v1
                dcl_texcoord v2
                dcl_texcoord1 v3
                slt r0.x, v3.x, -v3.x
                frc r0.y, v3.x
                add r0.z, -r0.y, v3.x
                slt r0.y, -r0.y, r0.y
                mad r0.x, r0.x, r0.y, r0.z
                mul r0.x, r0.x, c248.x
                mova a0.x, r0.x
                mov r0.xyw, c0[a0.x]
                mad oT0.x, v2.x, r0.w, c2[a0.x].w
                mov r1.xyw, c1[a0.x]
                mad oT0.y, v2.y, r1.w, c3[a0.x].w
                mul r0, r0.yyyx, c248.yzzy
                dp4 r0.x, v0, r0
                mul r1, r1.yyyx, c248.zyzy
                dp4 r0.y, v0, r1
                mov r1.yz, c248
                mul r1, r1.zzyy, c2[a0.x].yyyx
                dp4 r0.z, v0, r1
                add r1.xyz, r0, -c247
                dp3 r0.w, r1, c244
                mad r0.xyz, r0.w, c246, r0
                mov r0.w, v0.w
                dp4 oPos.z, r0, c242
                dp4 r1.x, r0, c240
                dp4 r1.y, r0, c241
                dp4 r0.x, r0, c243
                mad oPos.xy, c245, r0.x, r1
                mov oPos.w, r0.x
                mov oT1.x, c0[a0.x].z
                mov oT1.y, c1[a0.x].z
                mov oT1.z, c2[a0.x].z
                mov oT1.w, c3[a0.x].z
                mov oT2.xyz, v1
            
            // approximately 33 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   sampler2D BaseSampler;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   BaseSampler  s0       1
            //
            
                ps_2_0
                def c0, 1, 0, 0, 0
                dcl t0.xy
                dcl t1
                dcl_2d s0
                texld r0, t0, s0
                add r0.w, -r0.w, c0.x
                mul r1, r0, t1
                mov oC0, r1
            
            // approximately 4 instruction slots used (1 texture, 3 arithmetic)
            };
    }
}

