// VibratingEffect
// F63DDAEB6F6B5B082029F62DCAA69C022A1471FF07008024719A3CABCCA3886C

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Time;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   Time         c0       1
            //
            
                preshader
                mul c7.x, c0.x, (50)
            
            // approximately 1 instruction used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float FogDensity;
            //   float Intensity;
            //   float4x4 Matrices_WorldViewProjection;
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name                         Reg   Size
            //   ---------------------------- ----- ----
            //   Matrices_WorldViewProjection c0       4
            //   TexelOffset                  c4       1
            //   Intensity                    c5       1
            //   FogDensity                   c6       1
            //
            
                vs_2_0
                def c8, 6.28318548, 0.159154937, 0.5, -3.14159274
                def c9, 0.75, 0.125, 1.44269502, 1
                def c10, 0, 0, 0, 0
                def c11, -1.55009923e-006, -2.17013894e-005, 0.00260416674, 0.00026041668
                def c12, -0.020833334, -0.125, 1, 0.5
                dcl_position v0
                dcl_color v1
                mul r0.xyz, v1.yzxw, c7.x
                mad r0.y, v1.y, c8.x, -r0.y
                mad r0.xz, v1, c8.x, r0
                mad r0.xz, r0, c8.y, c8.z
                frc r0.xz, r0
                mad r0.xz, r0, c8.x, c8.w
                mad r0.y, r0.y, c8.y, c8.z
                frc r0.y, r0.y
                mad r0.y, r0.y, c8.x, c8.w
                sincos r1.y, r0.y, c11, c12
                mul r0.y, r1.y, c5.x
                mul r0.y, r0.y, v1.x
                mad r1.x, r0.y, c9.y, v0.x
                sincos r2.y, r0.x, c11, c12
                sincos r3.y, r0.z, c11, c12
                mul r0.x, r3.y, c5.x
                mul r0.x, r0.x, v1.y
                mad r1.z, r0.x, c9.y, v0.z
                mul r0.x, r2.y, c5.x
                mul r0.x, r0.x, v1.z
                mul r1.y, r0.x, c9.x
                mov r1.w, v0.w
                dp4 oPos.z, r1, c2
                dp4 r0.x, r1, c0
                dp4 r0.y, r1, c1
                dp4 r0.z, r1, c3
                mad oPos.xy, c4, r0.z, r0
                mul r0.x, r0.z, c6.x
                mov oPos.w, r0.z
                mul r0.y, r0.x, r0.x
                mul r0.x, r0.y, r0.x
                mul r0.x, r0.x, c9.z
                exp r0.x, r0.x
                rcp r0.x, r0.x
                add r0.x, -r0.x, c9.w
                max r0.x, r0.x, c10.x
                min oT1.x, r0.x, c9.w
                mov oT0, c9.w
            
            // approximately 59 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float3 Material_Diffuse;
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Diffuse c0       1
            //   Material_Opacity c1       1
            //
            
                ps_2_0
                def c2, 0.0588235296, 0.00392156886, 0.105882354, 0
                dcl t0
                dcl t1.x
                mul r0.xyz, t0, c0
                mov r1.xyz, c0
                mad r1.xyz, t0, -r1, c2
                mad r0.xyz, t1.x, r1, r0
                mul r0.w, t0.w, c1.x
                mov oC0, r0
            
            // approximately 6 instruction slots used
            };
    }
}

