// VignetteEffect
// 0215FF82383DB0B69F57EDCD929FEDC5EBC1B0182736D4C4F30E9F12C3816F49

//listing of all techniques and passes with embedded asm listings 

technique TSM2
{
    pass Main
    {
        vertexshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float2 TexelOffset;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   TexelOffset  c0       1
            //
            
                vs_2_0
                dcl_position v0
                dcl_texcoord v1
                mad oPos.xy, c0, v0.w, v0
                mov oT0.xy, v1
                mov oPos.zw, v0
            
            // approximately 3 instruction slots used
            };

        pixelshader = 
            asm {
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float SinceStarted;
            //
            //
            // Registers:
            //
            //   Name         Reg   Size
            //   ------------ ----- ----
            //   SinceStarted c0       1
            //
            
                preshader
                mul r0.x, c0.x, (3)
                log r1.x, r0.x
                mul r0.x, r1.x, (30)
                exp r1.x, r0.x
                add r0.x, r1.x, (-4)
                cmp r2.x, r0.x, r1.x, (4)
                add r0.x, r2.x, (-1000000)
                cmp c0.x, r0.x, (1000000), r2.x
                mul r0.x, c0.x, (10)
                log r1.x, r0.x
                mul r0.x, r1.x, (15)
                exp r1.x, r0.x
                add r0.x, r1.x, (-4)
                cmp r2.x, r0.x, r1.x, (4)
                add r0.x, r2.x, (-1000000)
                cmp c1.x, r0.x, (1000000), r2.x
            
            // approximately 16 instructions used
            //
            // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
            //
            // Parameters:
            //
            //   float Material_Opacity;
            //
            //
            // Registers:
            //
            //   Name             Reg   Size
            //   ---------------- ----- ----
            //   Material_Opacity c2       1
            //
            
                ps_2_0
                def c3, -0.5, 0.600000024, 1, -1
                dcl t0.xy
                add r0.xy, t0, c3.x
                mul r0.xy, r0, r0
                mad r0.y, r0.y, -c3.y, c3.z
                pow r1.w, r0.y, c1.x
                mad r0.x, r0.x, -c3.y, c3.z
                pow r1.x, r0.x, c0.x
                mad r0.x, r1.x, r1.w, c3.w
                mov r0.zw, c3.z
                mad r0.xyz, c2.x, r0.x, r0.z
                mov oC0, r0
            
            // approximately 14 instruction slots used
            };
    }
}

